// Code generated by jsonenums --type Mengenoperator; DO NOT EDIT.

package mengenoperator

import (
	"encoding/json"
	"fmt"
)

var (
	_MengenoperatorNameToValue = map[string]Mengenoperator{
		"KLEINER_ALS":  KLEINER_ALS,
		"GROESSER_ALS": GROESSER_ALS,
		"GLEICH":       GLEICH,
	}

	_MengenoperatorValueToName = map[Mengenoperator]string{
		KLEINER_ALS:  "KLEINER_ALS",
		GROESSER_ALS: "GROESSER_ALS",
		GLEICH:       "GLEICH",
	}
)

func init() {
	var v Mengenoperator
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_MengenoperatorNameToValue = map[string]Mengenoperator{
			interface{}(KLEINER_ALS).(fmt.Stringer).String():  KLEINER_ALS,
			interface{}(GROESSER_ALS).(fmt.Stringer).String(): GROESSER_ALS,
			interface{}(GLEICH).(fmt.Stringer).String():       GLEICH,
		}
	}
}

// MarshalJSON is generated so Mengenoperator satisfies json.Marshaler.
func (r Mengenoperator) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _MengenoperatorValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Mengenoperator: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Mengenoperator satisfies json.Unmarshaler.
func (r *Mengenoperator) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Mengenoperator should be a string, got %s", data)
	}
	v, ok := _MengenoperatorNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Mengenoperator %q", s)
	}
	*r = v
	return nil
}
