// Code generated by "stringer --type Mengenoperator"; DO NOT EDIT.

package mengenoperator

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KLEINER_ALS-1]
	_ = x[GROESSER_ALS-2]
	_ = x[GLEICH-3]
}

const _Mengenoperator_name = "KLEINER_ALSGROESSER_ALSGLEICH"

var _Mengenoperator_index = [...]uint8{0, 11, 23, 29}

func (i Mengenoperator) String() string {
	i -= 1
	if i < 0 || i >= Mengenoperator(len(_Mengenoperator_index)-1) {
		return "Mengenoperator(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Mengenoperator_name[_Mengenoperator_index[i]:_Mengenoperator_index[i+1]]
}
