package voraussetzungen

// Voraussetzungen Voraussetzungen, die erfüllt sein müssen, damit dieser Tarif zur Anwendung kommen kann.
//
//go:generate stringer --type Voraussetzungen
//go:generate jsonenums --type Voraussetzungen
type Voraussetzungen int

const (
	EINZUGSERMAECHTIGUNG Voraussetzungen = iota + 1
	ZEITPUNKT
	LIEFERANBINDUNG_EINE
	LIEFERANBINDUNG_ALLE
	GEWERBE
	LASTPROFIL
	ZAEHLERTYP_GROESSE
	AUSSCHLUSS_GROSSVERBRAUCHER
	NEUKUNDE
	BESTIMMTE_VERTRAGSFORMALITAETEN
	SELBSTABLESUNG
	ONLINEVORAUSSETZUNG
	MINDESTUMSATZ
	ZUSATZPRODUKT
	NEUKUNDE_MIT_VORAUSSETZUNGEN
	DIREKTVERTRIEB
	ANSCHLUSSART
	ANSCHLUSSWERT
	ALTER_KUNDENANLAGE
	ANLAGEBESCHAFFENHEIT
	BETRIEBSSTUNDENBEGRENZUNG
	FREIGABEZEITEN
	FAMILIENSTRUKTUR
	MITGLIEDSCHAFT
	STAATLICHE_FOERDERUNG
	BESONDERE_VERBRAUCHSSTELLE
	NIEDRIGENERGIE
	ORTSTEILE_LIEFERGEBIET
	WAERMEBEDARF_ERDGAS
	MAX_ZAEHLER_LIEFERSTELLEN
	LIEFERUNGSBESCHRAENKUNG_GASART
	KOMBI_BONI
	ALTVERTRAG
	VORGESCHRIEBENE_ZUSATZANLAGE
	MEHRERE_ZAEHLER_ABNAHMESTELLEN
	BESTIMMTER_ABNAHMEFALL
	ZUSATZMODALITAET
	NACHWEIS_ZAHLUNGSFAEHIGKEIT
	UMSTELLUNG_ENERGIEART
)
