// Code generated by jsonenums --type Voraussetzungen; DO NOT EDIT.

package voraussetzungen

import (
	"encoding/json"
	"fmt"
)

var (
	_VoraussetzungenNameToValue = map[string]Voraussetzungen{
		"EINZUGSERMAECHTIGUNG":            EINZUGSERMAECHTIGUNG,
		"ZEITPUNKT":                       ZEITPUNKT,
		"LIEFERANBINDUNG_EINE":            LIEFERANBINDUNG_EINE,
		"LIEFERANBINDUNG_ALLE":            LIEFERANBINDUNG_ALLE,
		"GEWERBE":                         GEWERBE,
		"LASTPROFIL":                      LASTPROFIL,
		"ZAEHLERTYP_GROESSE":              ZAEHLERTYP_GROESSE,
		"AUSSCHLUSS_GROSSVERBRAUCHER":     AUSSCHLUSS_GROSSVERBRAUCHER,
		"NEUKUNDE":                        NEUKUNDE,
		"BESTIMMTE_VERTRAGSFORMALITAETEN": BESTIMMTE_VERTRAGSFORMALITAETEN,
		"SELBSTABLESUNG":                  SELBSTABLESUNG,
		"ONLINEVORAUSSETZUNG":             ONLINEVORAUSSETZUNG,
		"MINDESTUMSATZ":                   MINDESTUMSATZ,
		"ZUSATZPRODUKT":                   ZUSATZPRODUKT,
		"NEUKUNDE_MIT_VORAUSSETZUNGEN":    NEUKUNDE_MIT_VORAUSSETZUNGEN,
		"DIREKTVERTRIEB":                  DIREKTVERTRIEB,
		"ANSCHLUSSART":                    ANSCHLUSSART,
		"ANSCHLUSSWERT":                   ANSCHLUSSWERT,
		"ALTER_KUNDENANLAGE":              ALTER_KUNDENANLAGE,
		"ANLAGEBESCHAFFENHEIT":            ANLAGEBESCHAFFENHEIT,
		"BETRIEBSSTUNDENBEGRENZUNG":       BETRIEBSSTUNDENBEGRENZUNG,
		"FREIGABEZEITEN":                  FREIGABEZEITEN,
		"FAMILIENSTRUKTUR":                FAMILIENSTRUKTUR,
		"MITGLIEDSCHAFT":                  MITGLIEDSCHAFT,
		"STAATLICHE_FOERDERUNG":           STAATLICHE_FOERDERUNG,
		"BESONDERE_VERBRAUCHSSTELLE":      BESONDERE_VERBRAUCHSSTELLE,
		"NIEDRIGENERGIE":                  NIEDRIGENERGIE,
		"ORTSTEILE_LIEFERGEBIET":          ORTSTEILE_LIEFERGEBIET,
		"WAERMEBEDARF_ERDGAS":             WAERMEBEDARF_ERDGAS,
		"MAX_ZAEHLER_LIEFERSTELLEN":       MAX_ZAEHLER_LIEFERSTELLEN,
		"LIEFERUNGSBESCHRAENKUNG_GASART":  LIEFERUNGSBESCHRAENKUNG_GASART,
		"KOMBI_BONI":                      KOMBI_BONI,
		"ALTVERTRAG":                      ALTVERTRAG,
		"VORGESCHRIEBENE_ZUSATZANLAGE":    VORGESCHRIEBENE_ZUSATZANLAGE,
		"MEHRERE_ZAEHLER_ABNAHMESTELLEN":  MEHRERE_ZAEHLER_ABNAHMESTELLEN,
		"BESTIMMTER_ABNAHMEFALL":          BESTIMMTER_ABNAHMEFALL,
		"ZUSATZMODALITAET":                ZUSATZMODALITAET,
		"NACHWEIS_ZAHLUNGSFAEHIGKEIT":     NACHWEIS_ZAHLUNGSFAEHIGKEIT,
		"UMSTELLUNG_ENERGIEART":           UMSTELLUNG_ENERGIEART,
	}

	_VoraussetzungenValueToName = map[Voraussetzungen]string{
		EINZUGSERMAECHTIGUNG:            "EINZUGSERMAECHTIGUNG",
		ZEITPUNKT:                       "ZEITPUNKT",
		LIEFERANBINDUNG_EINE:            "LIEFERANBINDUNG_EINE",
		LIEFERANBINDUNG_ALLE:            "LIEFERANBINDUNG_ALLE",
		GEWERBE:                         "GEWERBE",
		LASTPROFIL:                      "LASTPROFIL",
		ZAEHLERTYP_GROESSE:              "ZAEHLERTYP_GROESSE",
		AUSSCHLUSS_GROSSVERBRAUCHER:     "AUSSCHLUSS_GROSSVERBRAUCHER",
		NEUKUNDE:                        "NEUKUNDE",
		BESTIMMTE_VERTRAGSFORMALITAETEN: "BESTIMMTE_VERTRAGSFORMALITAETEN",
		SELBSTABLESUNG:                  "SELBSTABLESUNG",
		ONLINEVORAUSSETZUNG:             "ONLINEVORAUSSETZUNG",
		MINDESTUMSATZ:                   "MINDESTUMSATZ",
		ZUSATZPRODUKT:                   "ZUSATZPRODUKT",
		NEUKUNDE_MIT_VORAUSSETZUNGEN:    "NEUKUNDE_MIT_VORAUSSETZUNGEN",
		DIREKTVERTRIEB:                  "DIREKTVERTRIEB",
		ANSCHLUSSART:                    "ANSCHLUSSART",
		ANSCHLUSSWERT:                   "ANSCHLUSSWERT",
		ALTER_KUNDENANLAGE:              "ALTER_KUNDENANLAGE",
		ANLAGEBESCHAFFENHEIT:            "ANLAGEBESCHAFFENHEIT",
		BETRIEBSSTUNDENBEGRENZUNG:       "BETRIEBSSTUNDENBEGRENZUNG",
		FREIGABEZEITEN:                  "FREIGABEZEITEN",
		FAMILIENSTRUKTUR:                "FAMILIENSTRUKTUR",
		MITGLIEDSCHAFT:                  "MITGLIEDSCHAFT",
		STAATLICHE_FOERDERUNG:           "STAATLICHE_FOERDERUNG",
		BESONDERE_VERBRAUCHSSTELLE:      "BESONDERE_VERBRAUCHSSTELLE",
		NIEDRIGENERGIE:                  "NIEDRIGENERGIE",
		ORTSTEILE_LIEFERGEBIET:          "ORTSTEILE_LIEFERGEBIET",
		WAERMEBEDARF_ERDGAS:             "WAERMEBEDARF_ERDGAS",
		MAX_ZAEHLER_LIEFERSTELLEN:       "MAX_ZAEHLER_LIEFERSTELLEN",
		LIEFERUNGSBESCHRAENKUNG_GASART:  "LIEFERUNGSBESCHRAENKUNG_GASART",
		KOMBI_BONI:                      "KOMBI_BONI",
		ALTVERTRAG:                      "ALTVERTRAG",
		VORGESCHRIEBENE_ZUSATZANLAGE:    "VORGESCHRIEBENE_ZUSATZANLAGE",
		MEHRERE_ZAEHLER_ABNAHMESTELLEN:  "MEHRERE_ZAEHLER_ABNAHMESTELLEN",
		BESTIMMTER_ABNAHMEFALL:          "BESTIMMTER_ABNAHMEFALL",
		ZUSATZMODALITAET:                "ZUSATZMODALITAET",
		NACHWEIS_ZAHLUNGSFAEHIGKEIT:     "NACHWEIS_ZAHLUNGSFAEHIGKEIT",
		UMSTELLUNG_ENERGIEART:           "UMSTELLUNG_ENERGIEART",
	}
)

func init() {
	var v Voraussetzungen
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_VoraussetzungenNameToValue = map[string]Voraussetzungen{
			interface{}(EINZUGSERMAECHTIGUNG).(fmt.Stringer).String():            EINZUGSERMAECHTIGUNG,
			interface{}(ZEITPUNKT).(fmt.Stringer).String():                       ZEITPUNKT,
			interface{}(LIEFERANBINDUNG_EINE).(fmt.Stringer).String():            LIEFERANBINDUNG_EINE,
			interface{}(LIEFERANBINDUNG_ALLE).(fmt.Stringer).String():            LIEFERANBINDUNG_ALLE,
			interface{}(GEWERBE).(fmt.Stringer).String():                         GEWERBE,
			interface{}(LASTPROFIL).(fmt.Stringer).String():                      LASTPROFIL,
			interface{}(ZAEHLERTYP_GROESSE).(fmt.Stringer).String():              ZAEHLERTYP_GROESSE,
			interface{}(AUSSCHLUSS_GROSSVERBRAUCHER).(fmt.Stringer).String():     AUSSCHLUSS_GROSSVERBRAUCHER,
			interface{}(NEUKUNDE).(fmt.Stringer).String():                        NEUKUNDE,
			interface{}(BESTIMMTE_VERTRAGSFORMALITAETEN).(fmt.Stringer).String(): BESTIMMTE_VERTRAGSFORMALITAETEN,
			interface{}(SELBSTABLESUNG).(fmt.Stringer).String():                  SELBSTABLESUNG,
			interface{}(ONLINEVORAUSSETZUNG).(fmt.Stringer).String():             ONLINEVORAUSSETZUNG,
			interface{}(MINDESTUMSATZ).(fmt.Stringer).String():                   MINDESTUMSATZ,
			interface{}(ZUSATZPRODUKT).(fmt.Stringer).String():                   ZUSATZPRODUKT,
			interface{}(NEUKUNDE_MIT_VORAUSSETZUNGEN).(fmt.Stringer).String():    NEUKUNDE_MIT_VORAUSSETZUNGEN,
			interface{}(DIREKTVERTRIEB).(fmt.Stringer).String():                  DIREKTVERTRIEB,
			interface{}(ANSCHLUSSART).(fmt.Stringer).String():                    ANSCHLUSSART,
			interface{}(ANSCHLUSSWERT).(fmt.Stringer).String():                   ANSCHLUSSWERT,
			interface{}(ALTER_KUNDENANLAGE).(fmt.Stringer).String():              ALTER_KUNDENANLAGE,
			interface{}(ANLAGEBESCHAFFENHEIT).(fmt.Stringer).String():            ANLAGEBESCHAFFENHEIT,
			interface{}(BETRIEBSSTUNDENBEGRENZUNG).(fmt.Stringer).String():       BETRIEBSSTUNDENBEGRENZUNG,
			interface{}(FREIGABEZEITEN).(fmt.Stringer).String():                  FREIGABEZEITEN,
			interface{}(FAMILIENSTRUKTUR).(fmt.Stringer).String():                FAMILIENSTRUKTUR,
			interface{}(MITGLIEDSCHAFT).(fmt.Stringer).String():                  MITGLIEDSCHAFT,
			interface{}(STAATLICHE_FOERDERUNG).(fmt.Stringer).String():           STAATLICHE_FOERDERUNG,
			interface{}(BESONDERE_VERBRAUCHSSTELLE).(fmt.Stringer).String():      BESONDERE_VERBRAUCHSSTELLE,
			interface{}(NIEDRIGENERGIE).(fmt.Stringer).String():                  NIEDRIGENERGIE,
			interface{}(ORTSTEILE_LIEFERGEBIET).(fmt.Stringer).String():          ORTSTEILE_LIEFERGEBIET,
			interface{}(WAERMEBEDARF_ERDGAS).(fmt.Stringer).String():             WAERMEBEDARF_ERDGAS,
			interface{}(MAX_ZAEHLER_LIEFERSTELLEN).(fmt.Stringer).String():       MAX_ZAEHLER_LIEFERSTELLEN,
			interface{}(LIEFERUNGSBESCHRAENKUNG_GASART).(fmt.Stringer).String():  LIEFERUNGSBESCHRAENKUNG_GASART,
			interface{}(KOMBI_BONI).(fmt.Stringer).String():                      KOMBI_BONI,
			interface{}(ALTVERTRAG).(fmt.Stringer).String():                      ALTVERTRAG,
			interface{}(VORGESCHRIEBENE_ZUSATZANLAGE).(fmt.Stringer).String():    VORGESCHRIEBENE_ZUSATZANLAGE,
			interface{}(MEHRERE_ZAEHLER_ABNAHMESTELLEN).(fmt.Stringer).String():  MEHRERE_ZAEHLER_ABNAHMESTELLEN,
			interface{}(BESTIMMTER_ABNAHMEFALL).(fmt.Stringer).String():          BESTIMMTER_ABNAHMEFALL,
			interface{}(ZUSATZMODALITAET).(fmt.Stringer).String():                ZUSATZMODALITAET,
			interface{}(NACHWEIS_ZAHLUNGSFAEHIGKEIT).(fmt.Stringer).String():     NACHWEIS_ZAHLUNGSFAEHIGKEIT,
			interface{}(UMSTELLUNG_ENERGIEART).(fmt.Stringer).String():           UMSTELLUNG_ENERGIEART,
		}
	}
}

// MarshalJSON is generated so Voraussetzungen satisfies json.Marshaler.
func (r Voraussetzungen) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _VoraussetzungenValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Voraussetzungen: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Voraussetzungen satisfies json.Unmarshaler.
func (r *Voraussetzungen) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Voraussetzungen should be a string, got %s", data)
	}
	v, ok := _VoraussetzungenNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Voraussetzungen %q", s)
	}
	*r = v
	return nil
}
