// Code generated by jsonenums --type Tariftyp; DO NOT EDIT.

package tariftyp

import (
	"encoding/json"
	"fmt"
)

var (
	_TariftypNameToValue = map[string]Tariftyp{
		"GRUND_ERSATZVERSORGUNG": GRUND_ERSATZVERSORGUNG,
		"GRUNDVERSORGUNG":        GRUNDVERSORGUNG,
		"ERSATZVERSORGUNG":       ERSATZVERSORGUNG,
		"SONDERTARIF":            SONDERTARIF,
	}

	_TariftypValueToName = map[Tariftyp]string{
		GRUND_ERSATZVERSORGUNG: "GRUND_ERSATZVERSORGUNG",
		GRUNDVERSORGUNG:        "GRUNDVERSORGUNG",
		ERSATZVERSORGUNG:       "ERSATZVERSORGUNG",
		SONDERTARIF:            "SONDERTARIF",
	}
)

func init() {
	var v Tariftyp
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_TariftypNameToValue = map[string]Tariftyp{
			interface{}(GRUND_ERSATZVERSORGUNG).(fmt.Stringer).String(): GRUND_ERSATZVERSORGUNG,
			interface{}(GRUNDVERSORGUNG).(fmt.Stringer).String():        GRUNDVERSORGUNG,
			interface{}(ERSATZVERSORGUNG).(fmt.Stringer).String():       ERSATZVERSORGUNG,
			interface{}(SONDERTARIF).(fmt.Stringer).String():            SONDERTARIF,
		}
	}
}

// MarshalJSON is generated so Tariftyp satisfies json.Marshaler.
func (r Tariftyp) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _TariftypValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Tariftyp: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Tariftyp satisfies json.Unmarshaler.
func (r *Tariftyp) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Tariftyp should be a string, got %s", data)
	}
	v, ok := _TariftypNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Tariftyp %q", s)
	}
	*r = v
	return nil
}
