// Code generated by "stringer --type Tariftyp"; DO NOT EDIT.

package tariftyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GRUND_ERSATZVERSORGUNG-1]
	_ = x[GRUNDVERSORGUNG-2]
	_ = x[ERSATZVERSORGUNG-3]
	_ = x[SONDERTARIF-4]
}

const _Tariftyp_name = "GRUND_ERSATZVERSORGUNGGRUNDVERSORGUNGERSATZVERSORGUNGSONDERTARIF"

var _Tariftyp_index = [...]uint8{0, 22, 37, 53, 64}

func (i Tariftyp) String() string {
	i -= 1
	if i < 0 || i >= Tariftyp(len(_Tariftyp_index)-1) {
		return "Tariftyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Tariftyp_name[_Tariftyp_index[i]:_Tariftyp_index[i+1]]
}
