// Code generated by jsonenums --type Ausschreibungsportal; DO NOT EDIT.

package ausschreibungsportal

import (
	"encoding/json"
	"fmt"
)

var (
	_AusschreibungsportalNameToValue = map[string]Ausschreibungsportal{
		"ENPORTAL":             ENPORTAL,
		"ENERGIE_AGENTUR":      ENERGIE_AGENTUR,
		"BMWI":                 BMWI,
		"ENERGIE_HANDELSPLATZ": ENERGIE_HANDELSPLATZ,
		"BUND":                 BUND,
		"VERA_ONLINE":          VERA_ONLINE,
		"ISPEX":                ISPEX,
		"ENERGIEMARKTPLATZ":    ENERGIEMARKTPLATZ,
		"EVERGABE":             EVERGABE,
		"DTAD":                 DTAD,
	}

	_AusschreibungsportalValueToName = map[Ausschreibungsportal]string{
		ENPORTAL:             "ENPORTAL",
		ENERGIE_AGENTUR:      "ENERGIE_AGENTUR",
		BMWI:                 "BMWI",
		ENERGIE_HANDELSPLATZ: "ENERGIE_HANDELSPLATZ",
		BUND:                 "BUND",
		VERA_ONLINE:          "VERA_ONLINE",
		ISPEX:                "ISPEX",
		ENERGIEMARKTPLATZ:    "ENERGIEMARKTPLATZ",
		EVERGABE:             "EVERGABE",
		DTAD:                 "DTAD",
	}
)

func init() {
	var v Ausschreibungsportal
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_AusschreibungsportalNameToValue = map[string]Ausschreibungsportal{
			interface{}(ENPORTAL).(fmt.Stringer).String():             ENPORTAL,
			interface{}(ENERGIE_AGENTUR).(fmt.Stringer).String():      ENERGIE_AGENTUR,
			interface{}(BMWI).(fmt.Stringer).String():                 BMWI,
			interface{}(ENERGIE_HANDELSPLATZ).(fmt.Stringer).String(): ENERGIE_HANDELSPLATZ,
			interface{}(BUND).(fmt.Stringer).String():                 BUND,
			interface{}(VERA_ONLINE).(fmt.Stringer).String():          VERA_ONLINE,
			interface{}(ISPEX).(fmt.Stringer).String():                ISPEX,
			interface{}(ENERGIEMARKTPLATZ).(fmt.Stringer).String():    ENERGIEMARKTPLATZ,
			interface{}(EVERGABE).(fmt.Stringer).String():             EVERGABE,
			interface{}(DTAD).(fmt.Stringer).String():                 DTAD,
		}
	}
}

// MarshalJSON is generated so Ausschreibungsportal satisfies json.Marshaler.
func (r Ausschreibungsportal) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _AusschreibungsportalValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Ausschreibungsportal: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Ausschreibungsportal satisfies json.Unmarshaler.
func (r *Ausschreibungsportal) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Ausschreibungsportal should be a string, got %s", data)
	}
	v, ok := _AusschreibungsportalNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Ausschreibungsportal %q", s)
	}
	*r = v
	return nil
}
