// Code generated by "stringer --type Ausschreibungsportal"; DO NOT EDIT.

package ausschreibungsportal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ENPORTAL-1]
	_ = x[ENERGIE_AGENTUR-2]
	_ = x[BMWI-3]
	_ = x[ENERGIE_HANDELSPLATZ-4]
	_ = x[BUND-5]
	_ = x[VERA_ONLINE-6]
	_ = x[ISPEX-7]
	_ = x[ENERGIEMARKTPLATZ-8]
	_ = x[EVERGABE-9]
	_ = x[DTAD-10]
}

const _Ausschreibungsportal_name = "ENPORTALENERGIE_AGENTURBMWIENERGIE_HANDELSPLATZBUNDVERA_ONLINEISPEXENERGIEMARKTPLATZEVERGABEDTAD"

var _Ausschreibungsportal_index = [...]uint8{0, 8, 23, 27, 47, 51, 62, 67, 84, 92, 96}

func (i Ausschreibungsportal) String() string {
	i -= 1
	if i < 0 || i >= Ausschreibungsportal(len(_Ausschreibungsportal_index)-1) {
		return "Ausschreibungsportal(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Ausschreibungsportal_name[_Ausschreibungsportal_index[i]:_Ausschreibungsportal_index[i+1]]
}
