// Code generated by "stringer --type Gasqualitaet"; DO NOT EDIT.

package gasqualitaet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[H_GAS-1]
	_ = x[L_GAS-2]
}

const _Gasqualitaet_name = "H_GASL_GAS"

var _Gasqualitaet_index = [...]uint8{0, 5, 10}

func (i Gasqualitaet) String() string {
	i -= 1
	if i < 0 || i >= Gasqualitaet(len(_Gasqualitaet_index)-1) {
		return "Gasqualitaet(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Gasqualitaet_name[_Gasqualitaet_index[i]:_Gasqualitaet_index[i+1]]
}
