// Code generated by "stringer --type Gebiettyp"; DO NOT EDIT.

package gebiettyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[REGELZONE-1]
	_ = x[MARKTGEBIET-2]
	_ = x[BILANZIERUNGSGEBIET-3]
	_ = x[VERTEILNETZ-4]
	_ = x[TRANSPORTNETZ-5]
	_ = x[REGIONALNETZ-6]
	_ = x[AREALNETZ-7]
	_ = x[GRUNDVERSORGUNGSGEBIET-8]
	_ = x[VERSORGUNGSGEBIET-9]
}

const _Gebiettyp_name = "REGELZONEMARKTGEBIETBILANZIERUNGSGEBIETVERTEILNETZTRANSPORTNETZREGIONALNETZAREALNETZGRUNDVERSORGUNGSGEBIETVERSORGUNGSGEBIET"

var _Gebiettyp_index = [...]uint8{0, 9, 20, 39, 50, 63, 75, 84, 106, 123}

func (i Gebiettyp) String() string {
	i -= 1
	if i < 0 || i >= Gebiettyp(len(_Gebiettyp_index)-1) {
		return "Gebiettyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Gebiettyp_name[_Gebiettyp_index[i]:_Gebiettyp_index[i+1]]
}
