// Code generated by "stringer --type Gueltigkeitstyp"; DO NOT EDIT.

package gueltigkeitstyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NICHT_IN-1]
}

const _Gueltigkeitstyp_name = "NICHT_IN"

var _Gueltigkeitstyp_index = [...]uint8{0, 8}

func (i Gueltigkeitstyp) String() string {
	i -= 1
	if i < 0 || i >= Gueltigkeitstyp(len(_Gueltigkeitstyp_index)-1) {
		return "Gueltigkeitstyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Gueltigkeitstyp_name[_Gueltigkeitstyp_index[i]:_Gueltigkeitstyp_index[i+1]]
}
