// Code generated by "stringer --type Regionskriteriumtyp"; DO NOT EDIT.

package regionskriteriumtyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BUNDESLANDKENNZIFFER-1]
	_ = x[BUNDESLAND_NAME-2]
	_ = x[MARKTGEBIET_NUMMER-3]
	_ = x[MARKTGEBIET_NAME-4]
	_ = x[REGELGEBIET_NUMMER-5]
	_ = x[REGELGEBIET_NAME-6]
	_ = x[NETZBETREIBER_NUMMER-7]
	_ = x[NETZBETREIBER_NAME-8]
	_ = x[BILANZIERUNGS_GEBIET_NUMMER-9]
	_ = x[MSB_NUMMER-10]
	_ = x[MSB_NAME-11]
	_ = x[VERSORGER_NUMMER-12]
	_ = x[VERSORGER_NAME-13]
	_ = x[GRUNDVERSORGER_NUMMER-14]
	_ = x[GRUNDVERSORGER_NAME-15]
	_ = x[KREIS_NAME-16]
	_ = x[KREISKENNZIFFER-17]
	_ = x[GEMEINDE_NAME-18]
	_ = x[GEMEINDEKENNZIFFER-19]
	_ = x[POSTLEITZAHL-20]
	_ = x[ORT-21]
	_ = x[EINWOHNERZAHL_GEMEINDE-22]
	_ = x[EINWOHNERZAHL_ORT-23]
	_ = x[KM_UMKREIS-24]
	_ = x[BUNDESWEIT-25]
}

const _Regionskriteriumtyp_name = "BUNDESLANDKENNZIFFERBUNDESLAND_NAMEMARKTGEBIET_NUMMERMARKTGEBIET_NAMEREGELGEBIET_NUMMERREGELGEBIET_NAMENETZBETREIBER_NUMMERNETZBETREIBER_NAMEBILANZIERUNGS_GEBIET_NUMMERMSB_NUMMERMSB_NAMEVERSORGER_NUMMERVERSORGER_NAMEGRUNDVERSORGER_NUMMERGRUNDVERSORGER_NAMEKREIS_NAMEKREISKENNZIFFERGEMEINDE_NAMEGEMEINDEKENNZIFFERPOSTLEITZAHLORTEINWOHNERZAHL_GEMEINDEEINWOHNERZAHL_ORTKM_UMKREISBUNDESWEIT"

var _Regionskriteriumtyp_index = [...]uint16{0, 20, 35, 53, 69, 87, 103, 123, 141, 168, 178, 186, 202, 216, 237, 256, 266, 281, 294, 312, 324, 327, 349, 366, 376, 386}

func (i Regionskriteriumtyp) String() string {
	i -= 1
	if i < 0 || i >= Regionskriteriumtyp(len(_Regionskriteriumtyp_index)-1) {
		return "Regionskriteriumtyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Regionskriteriumtyp_name[_Regionskriteriumtyp_index[i]:_Regionskriteriumtyp_index[i+1]]
}
