package regionskriteriumtyp

// Regionskriteriumtyp is an enum
//
//go:generate stringer --type Regionskriteriumtyp
//go:generate jsonenums --type Regionskriteriumtyp
type Regionskriteriumtyp int

const (
	BUNDESLANDKENNZIFFER Regionskriteriumtyp = iota + 1
	BUNDESLAND_NAME
	MARKTGEBIET_NUMMER
	MARKTGEBIET_NAME
	REGELGEBIET_NUMMER
	REGELGEBIET_NAME
	NETZBETREIBER_NUMMER
	NETZBETREIBER_NAME
	BILANZIERUNGS_GEBIET_NUMMER
	MSB_NUMMER
	MSB_NAME
	VERSORGER_NUMMER
	VERSORGER_NAME
	GRUNDVERSORGER_NUMMER
	GRUNDVERSORGER_NAME
	KREIS_NAME
	KREISKENNZIFFER
	GEMEINDE_NAME
	GEMEINDEKENNZIFFER
	POSTLEITZAHL
	ORT
	EINWOHNERZAHL_GEMEINDE
	EINWOHNERZAHL_ORT
	KM_UMKREIS
	BUNDESWEIT
)
