// Code generated by jsonenums --type Regionskriteriumtyp; DO NOT EDIT.

package regionskriteriumtyp

import (
	"encoding/json"
	"fmt"
)

var (
	_RegionskriteriumtypNameToValue = map[string]Regionskriteriumtyp{
		"BUNDESLANDKENNZIFFER":        BUNDESLANDKENNZIFFER,
		"BUNDESLAND_NAME":             BUNDESLAND_NAME,
		"MARKTGEBIET_NUMMER":          MARKTGEBIET_NUMMER,
		"MARKTGEBIET_NAME":            MARKTGEBIET_NAME,
		"REGELGEBIET_NUMMER":          REGELGEBIET_NUMMER,
		"REGELGEBIET_NAME":            REGELGEBIET_NAME,
		"NETZBETREIBER_NUMMER":        NETZBETREIBER_NUMMER,
		"NETZBETREIBER_NAME":          NETZBETREIBER_NAME,
		"BILANZIERUNGS_GEBIET_NUMMER": BILANZIERUNGS_GEBIET_NUMMER,
		"MSB_NUMMER":                  MSB_NUMMER,
		"MSB_NAME":                    MSB_NAME,
		"VERSORGER_NUMMER":            VERSORGER_NUMMER,
		"VERSORGER_NAME":              VERSORGER_NAME,
		"GRUNDVERSORGER_NUMMER":       GRUNDVERSORGER_NUMMER,
		"GRUNDVERSORGER_NAME":         GRUNDVERSORGER_NAME,
		"KREIS_NAME":                  KREIS_NAME,
		"KREISKENNZIFFER":             KREISKENNZIFFER,
		"GEMEINDE_NAME":               GEMEINDE_NAME,
		"GEMEINDEKENNZIFFER":          GEMEINDEKENNZIFFER,
		"POSTLEITZAHL":                POSTLEITZAHL,
		"ORT":                         ORT,
		"EINWOHNERZAHL_GEMEINDE":      EINWOHNERZAHL_GEMEINDE,
		"EINWOHNERZAHL_ORT":           EINWOHNERZAHL_ORT,
		"KM_UMKREIS":                  KM_UMKREIS,
		"BUNDESWEIT":                  BUNDESWEIT,
	}

	_RegionskriteriumtypValueToName = map[Regionskriteriumtyp]string{
		BUNDESLANDKENNZIFFER:        "BUNDESLANDKENNZIFFER",
		BUNDESLAND_NAME:             "BUNDESLAND_NAME",
		MARKTGEBIET_NUMMER:          "MARKTGEBIET_NUMMER",
		MARKTGEBIET_NAME:            "MARKTGEBIET_NAME",
		REGELGEBIET_NUMMER:          "REGELGEBIET_NUMMER",
		REGELGEBIET_NAME:            "REGELGEBIET_NAME",
		NETZBETREIBER_NUMMER:        "NETZBETREIBER_NUMMER",
		NETZBETREIBER_NAME:          "NETZBETREIBER_NAME",
		BILANZIERUNGS_GEBIET_NUMMER: "BILANZIERUNGS_GEBIET_NUMMER",
		MSB_NUMMER:                  "MSB_NUMMER",
		MSB_NAME:                    "MSB_NAME",
		VERSORGER_NUMMER:            "VERSORGER_NUMMER",
		VERSORGER_NAME:              "VERSORGER_NAME",
		GRUNDVERSORGER_NUMMER:       "GRUNDVERSORGER_NUMMER",
		GRUNDVERSORGER_NAME:         "GRUNDVERSORGER_NAME",
		KREIS_NAME:                  "KREIS_NAME",
		KREISKENNZIFFER:             "KREISKENNZIFFER",
		GEMEINDE_NAME:               "GEMEINDE_NAME",
		GEMEINDEKENNZIFFER:          "GEMEINDEKENNZIFFER",
		POSTLEITZAHL:                "POSTLEITZAHL",
		ORT:                         "ORT",
		EINWOHNERZAHL_GEMEINDE:      "EINWOHNERZAHL_GEMEINDE",
		EINWOHNERZAHL_ORT:           "EINWOHNERZAHL_ORT",
		KM_UMKREIS:                  "KM_UMKREIS",
		BUNDESWEIT:                  "BUNDESWEIT",
	}
)

func init() {
	var v Regionskriteriumtyp
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_RegionskriteriumtypNameToValue = map[string]Regionskriteriumtyp{
			interface{}(BUNDESLANDKENNZIFFER).(fmt.Stringer).String():        BUNDESLANDKENNZIFFER,
			interface{}(BUNDESLAND_NAME).(fmt.Stringer).String():             BUNDESLAND_NAME,
			interface{}(MARKTGEBIET_NUMMER).(fmt.Stringer).String():          MARKTGEBIET_NUMMER,
			interface{}(MARKTGEBIET_NAME).(fmt.Stringer).String():            MARKTGEBIET_NAME,
			interface{}(REGELGEBIET_NUMMER).(fmt.Stringer).String():          REGELGEBIET_NUMMER,
			interface{}(REGELGEBIET_NAME).(fmt.Stringer).String():            REGELGEBIET_NAME,
			interface{}(NETZBETREIBER_NUMMER).(fmt.Stringer).String():        NETZBETREIBER_NUMMER,
			interface{}(NETZBETREIBER_NAME).(fmt.Stringer).String():          NETZBETREIBER_NAME,
			interface{}(BILANZIERUNGS_GEBIET_NUMMER).(fmt.Stringer).String(): BILANZIERUNGS_GEBIET_NUMMER,
			interface{}(MSB_NUMMER).(fmt.Stringer).String():                  MSB_NUMMER,
			interface{}(MSB_NAME).(fmt.Stringer).String():                    MSB_NAME,
			interface{}(VERSORGER_NUMMER).(fmt.Stringer).String():            VERSORGER_NUMMER,
			interface{}(VERSORGER_NAME).(fmt.Stringer).String():              VERSORGER_NAME,
			interface{}(GRUNDVERSORGER_NUMMER).(fmt.Stringer).String():       GRUNDVERSORGER_NUMMER,
			interface{}(GRUNDVERSORGER_NAME).(fmt.Stringer).String():         GRUNDVERSORGER_NAME,
			interface{}(KREIS_NAME).(fmt.Stringer).String():                  KREIS_NAME,
			interface{}(KREISKENNZIFFER).(fmt.Stringer).String():             KREISKENNZIFFER,
			interface{}(GEMEINDE_NAME).(fmt.Stringer).String():               GEMEINDE_NAME,
			interface{}(GEMEINDEKENNZIFFER).(fmt.Stringer).String():          GEMEINDEKENNZIFFER,
			interface{}(POSTLEITZAHL).(fmt.Stringer).String():                POSTLEITZAHL,
			interface{}(ORT).(fmt.Stringer).String():                         ORT,
			interface{}(EINWOHNERZAHL_GEMEINDE).(fmt.Stringer).String():      EINWOHNERZAHL_GEMEINDE,
			interface{}(EINWOHNERZAHL_ORT).(fmt.Stringer).String():           EINWOHNERZAHL_ORT,
			interface{}(KM_UMKREIS).(fmt.Stringer).String():                  KM_UMKREIS,
			interface{}(BUNDESWEIT).(fmt.Stringer).String():                  BUNDESWEIT,
		}
	}
}

// MarshalJSON is generated so Regionskriteriumtyp satisfies json.Marshaler.
func (r Regionskriteriumtyp) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _RegionskriteriumtypValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Regionskriteriumtyp: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Regionskriteriumtyp satisfies json.Unmarshaler.
func (r *Regionskriteriumtyp) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Regionskriteriumtyp should be a string, got %s", data)
	}
	v, ok := _RegionskriteriumtypNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Regionskriteriumtyp %q", s)
	}
	*r = v
	return nil
}
