// Code generated by jsonenums --type BDEWArtikelnummer; DO NOT EDIT.

package bdewartikelnummer

import (
	"encoding/json"
	"fmt"
)

var (
	_BDEWArtikelnummerNameToValue = map[string]BDEWArtikelnummer{
		"LEISTUNG":                                   LEISTUNG,
		"LEISTUNG_PAUSCHAL":                          LEISTUNG_PAUSCHAL,
		"GRUNDPREIS":                                 GRUNDPREIS,
		"REGELENERGIE_ARBEIT":                        REGELENERGIE_ARBEIT,
		"REGELENERGIE_LEISTUNG":                      REGELENERGIE_LEISTUNG,
		"NOTSTROMLIEFERUNG_ARBEIT":                   NOTSTROMLIEFERUNG_ARBEIT,
		"NOTSTROMLIEFERUNG_LEISTUNG":                 NOTSTROMLIEFERUNG_LEISTUNG,
		"RESERVENETZKAPAZITAET":                      RESERVENETZKAPAZITAET,
		"RESERVELEISTUNG":                            RESERVELEISTUNG,
		"ZUSAETZLICHE_ABLESUNG":                      ZUSAETZLICHE_ABLESUNG,
		"PRUEFGEBUEHREN_AUSSERPLANMAESSIG":           PRUEFGEBUEHREN_AUSSERPLANMAESSIG,
		"WIRKARBEIT":                                 WIRKARBEIT,
		"SINGULAER_GENUTZTE_BETRIEBSMITTEL":          SINGULAER_GENUTZTE_BETRIEBSMITTEL,
		"ABGABE_KWKG":                                ABGABE_KWKG,
		"ABSCHLAG":                                   ABSCHLAG,
		"KONZESSIONSABGABE":                          KONZESSIONSABGABE,
		"ENTGELT_FERNAUSLESUNG":                      ENTGELT_FERNAUSLESUNG,
		"UNTERMESSUNG":                               UNTERMESSUNG,
		"BLINDMEHRARBEIT":                            BLINDMEHRARBEIT,
		"ENTGELT_ABRECHNUNG":                         ENTGELT_ABRECHNUNG,
		"SPERRKOSTEN":                                SPERRKOSTEN,
		"ENTSPERRKOSTEN":                             ENTSPERRKOSTEN,
		"MAHNKOSTEN":                                 MAHNKOSTEN,
		"MEHR_MINDERMENGEN":                          MEHR_MINDERMENGEN,
		"INKASSOKOSTEN":                              INKASSOKOSTEN,
		"BLINDMEHRLEISTUNG":                          BLINDMEHRLEISTUNG,
		"ENTGELT_MESSUNG_ABLESUNG":                   ENTGELT_MESSUNG_ABLESUNG,
		"ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK": ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK,
		"AUSGLEICHSENERGIE":                          AUSGLEICHSENERGIE,
		"ZAEHLEINRICHTUNG":                           ZAEHLEINRICHTUNG,
		"WANDLER_MENGENUMWERTER":                     WANDLER_MENGENUMWERTER,
		"KOMMUNIKATIONSEINRICHTUNG":                  KOMMUNIKATIONSEINRICHTUNG,
		"TECHNISCHE_STEUEREINRICHTUNG":               TECHNISCHE_STEUEREINRICHTUNG,
		"PARAGRAF_19_STROM_NEV_UMLAGE":               PARAGRAF_19_STROM_NEV_UMLAGE,
		"BEFESTIGUNGSEINRICHTUNG":                    BEFESTIGUNGSEINRICHTUNG,
		"OFFSHORE_HAFTUNGSUMLAGE":                    OFFSHORE_HAFTUNGSUMLAGE,
		"FIXE_ARBEITSENTGELTKOMPONENTE":              FIXE_ARBEITSENTGELTKOMPONENTE,
		"FIXE_LEISTUNGSENTGELTKOMPONENTE":            FIXE_LEISTUNGSENTGELTKOMPONENTE,
		"UMLAGE_ABSCHALTBARE_LASTEN":                 UMLAGE_ABSCHALTBARE_LASTEN,
		"MEHRMENGE":                                  MEHRMENGE,
		"MINDERMENGE":                                MINDERMENGE,
		"ENERGIESTEUER":                              ENERGIESTEUER,
		"SMARTMETER_GATEWAY":                         SMARTMETER_GATEWAY,
		"STEUERBOX":                                  STEUERBOX,
		"MSB_INKL_MESSUNG":                           MSB_INKL_MESSUNG,
		"AUSGLEICHSENERGIE_UNTERDECKUNG":             AUSGLEICHSENERGIE_UNTERDECKUNG,
		"ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_1_MSBG": ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_1_MSBG,
		"ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_2_MSBG": ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_2_MSBG,
		"ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_3_MSBG": ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_3_MSBG,
		"ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_4_MSBG": ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_4_MSBG,
		"ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_5_MSBG": ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_5_MSBG,
		"ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_3_MSBG":   ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_3_MSBG,
		"EINBAU_IMS":                                 EINBAU_IMS,
		"EINBAU_KME_RLM":                             EINBAU_KME_RLM,
		"EINBAU_WANDLER":                             EINBAU_WANDLER,
		"WEITERE_ENERGIEFLUSSRICHTUNG":               WEITERE_ENERGIEFLUSSRICHTUNG,
		"VERGLEICHSMESSUNG":                          VERGLEICHSMESSUNG,
		"ÄNDERUNG_MESSEBENE":                         ÄNDERUNG_MESSEBENE,
		"EINBAU_STEUERBOX":                           EINBAU_STEUERBOX,
		"ANSCHLUSS_TR_STEUERBOX_SR":                  ANSCHLUSS_TR_STEUERBOX_SR,
		"SCHWACHLAST_KA":                             SCHWACHLAST_KA,
	}

	_BDEWArtikelnummerValueToName = map[BDEWArtikelnummer]string{
		LEISTUNG:                          "LEISTUNG",
		LEISTUNG_PAUSCHAL:                 "LEISTUNG_PAUSCHAL",
		GRUNDPREIS:                        "GRUNDPREIS",
		REGELENERGIE_ARBEIT:               "REGELENERGIE_ARBEIT",
		REGELENERGIE_LEISTUNG:             "REGELENERGIE_LEISTUNG",
		NOTSTROMLIEFERUNG_ARBEIT:          "NOTSTROMLIEFERUNG_ARBEIT",
		NOTSTROMLIEFERUNG_LEISTUNG:        "NOTSTROMLIEFERUNG_LEISTUNG",
		RESERVENETZKAPAZITAET:             "RESERVENETZKAPAZITAET",
		RESERVELEISTUNG:                   "RESERVELEISTUNG",
		ZUSAETZLICHE_ABLESUNG:             "ZUSAETZLICHE_ABLESUNG",
		PRUEFGEBUEHREN_AUSSERPLANMAESSIG:  "PRUEFGEBUEHREN_AUSSERPLANMAESSIG",
		WIRKARBEIT:                        "WIRKARBEIT",
		SINGULAER_GENUTZTE_BETRIEBSMITTEL: "SINGULAER_GENUTZTE_BETRIEBSMITTEL",
		ABGABE_KWKG:                       "ABGABE_KWKG",
		ABSCHLAG:                          "ABSCHLAG",
		KONZESSIONSABGABE:                 "KONZESSIONSABGABE",
		ENTGELT_FERNAUSLESUNG:             "ENTGELT_FERNAUSLESUNG",
		UNTERMESSUNG:                      "UNTERMESSUNG",
		BLINDMEHRARBEIT:                   "BLINDMEHRARBEIT",
		ENTGELT_ABRECHNUNG:                "ENTGELT_ABRECHNUNG",
		SPERRKOSTEN:                       "SPERRKOSTEN",
		ENTSPERRKOSTEN:                    "ENTSPERRKOSTEN",
		MAHNKOSTEN:                        "MAHNKOSTEN",
		MEHR_MINDERMENGEN:                 "MEHR_MINDERMENGEN",
		INKASSOKOSTEN:                     "INKASSOKOSTEN",
		BLINDMEHRLEISTUNG:                 "BLINDMEHRLEISTUNG",
		ENTGELT_MESSUNG_ABLESUNG:          "ENTGELT_MESSUNG_ABLESUNG",
		ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK: "ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK",
		AUSGLEICHSENERGIE:                          "AUSGLEICHSENERGIE",
		ZAEHLEINRICHTUNG:                           "ZAEHLEINRICHTUNG",
		WANDLER_MENGENUMWERTER:                     "WANDLER_MENGENUMWERTER",
		KOMMUNIKATIONSEINRICHTUNG:                  "KOMMUNIKATIONSEINRICHTUNG",
		TECHNISCHE_STEUEREINRICHTUNG:               "TECHNISCHE_STEUEREINRICHTUNG",
		PARAGRAF_19_STROM_NEV_UMLAGE:               "PARAGRAF_19_STROM_NEV_UMLAGE",
		BEFESTIGUNGSEINRICHTUNG:                    "BEFESTIGUNGSEINRICHTUNG",
		OFFSHORE_HAFTUNGSUMLAGE:                    "OFFSHORE_HAFTUNGSUMLAGE",
		FIXE_ARBEITSENTGELTKOMPONENTE:              "FIXE_ARBEITSENTGELTKOMPONENTE",
		FIXE_LEISTUNGSENTGELTKOMPONENTE:            "FIXE_LEISTUNGSENTGELTKOMPONENTE",
		UMLAGE_ABSCHALTBARE_LASTEN:                 "UMLAGE_ABSCHALTBARE_LASTEN",
		MEHRMENGE:                                  "MEHRMENGE",
		MINDERMENGE:                                "MINDERMENGE",
		ENERGIESTEUER:                              "ENERGIESTEUER",
		SMARTMETER_GATEWAY:                         "SMARTMETER_GATEWAY",
		STEUERBOX:                                  "STEUERBOX",
		MSB_INKL_MESSUNG:                           "MSB_INKL_MESSUNG",
		AUSGLEICHSENERGIE_UNTERDECKUNG:             "AUSGLEICHSENERGIE_UNTERDECKUNG",
		ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_1_MSBG: "ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_1_MSBG",
		ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_2_MSBG: "ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_2_MSBG",
		ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_3_MSBG: "ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_3_MSBG",
		ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_4_MSBG: "ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_4_MSBG",
		ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_5_MSBG: "ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_5_MSBG",
		ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_3_MSBG:   "ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_3_MSBG",
		EINBAU_IMS:                                 "EINBAU_IMS",
		EINBAU_KME_RLM:                             "EINBAU_KME_RLM",
		EINBAU_WANDLER:                             "EINBAU_WANDLER",
		WEITERE_ENERGIEFLUSSRICHTUNG:               "WEITERE_ENERGIEFLUSSRICHTUNG",
		VERGLEICHSMESSUNG:                          "VERGLEICHSMESSUNG",
		ÄNDERUNG_MESSEBENE:                         "ÄNDERUNG_MESSEBENE",
		EINBAU_STEUERBOX:                           "EINBAU_STEUERBOX",
		ANSCHLUSS_TR_STEUERBOX_SR:                  "ANSCHLUSS_TR_STEUERBOX_SR",
		SCHWACHLAST_KA:                             "SCHWACHLAST_KA",
	}
)

func init() {
	var v BDEWArtikelnummer
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_BDEWArtikelnummerNameToValue = map[string]BDEWArtikelnummer{
			interface{}(LEISTUNG).(fmt.Stringer).String():                                   LEISTUNG,
			interface{}(LEISTUNG_PAUSCHAL).(fmt.Stringer).String():                          LEISTUNG_PAUSCHAL,
			interface{}(GRUNDPREIS).(fmt.Stringer).String():                                 GRUNDPREIS,
			interface{}(REGELENERGIE_ARBEIT).(fmt.Stringer).String():                        REGELENERGIE_ARBEIT,
			interface{}(REGELENERGIE_LEISTUNG).(fmt.Stringer).String():                      REGELENERGIE_LEISTUNG,
			interface{}(NOTSTROMLIEFERUNG_ARBEIT).(fmt.Stringer).String():                   NOTSTROMLIEFERUNG_ARBEIT,
			interface{}(NOTSTROMLIEFERUNG_LEISTUNG).(fmt.Stringer).String():                 NOTSTROMLIEFERUNG_LEISTUNG,
			interface{}(RESERVENETZKAPAZITAET).(fmt.Stringer).String():                      RESERVENETZKAPAZITAET,
			interface{}(RESERVELEISTUNG).(fmt.Stringer).String():                            RESERVELEISTUNG,
			interface{}(ZUSAETZLICHE_ABLESUNG).(fmt.Stringer).String():                      ZUSAETZLICHE_ABLESUNG,
			interface{}(PRUEFGEBUEHREN_AUSSERPLANMAESSIG).(fmt.Stringer).String():           PRUEFGEBUEHREN_AUSSERPLANMAESSIG,
			interface{}(WIRKARBEIT).(fmt.Stringer).String():                                 WIRKARBEIT,
			interface{}(SINGULAER_GENUTZTE_BETRIEBSMITTEL).(fmt.Stringer).String():          SINGULAER_GENUTZTE_BETRIEBSMITTEL,
			interface{}(ABGABE_KWKG).(fmt.Stringer).String():                                ABGABE_KWKG,
			interface{}(ABSCHLAG).(fmt.Stringer).String():                                   ABSCHLAG,
			interface{}(KONZESSIONSABGABE).(fmt.Stringer).String():                          KONZESSIONSABGABE,
			interface{}(ENTGELT_FERNAUSLESUNG).(fmt.Stringer).String():                      ENTGELT_FERNAUSLESUNG,
			interface{}(UNTERMESSUNG).(fmt.Stringer).String():                               UNTERMESSUNG,
			interface{}(BLINDMEHRARBEIT).(fmt.Stringer).String():                            BLINDMEHRARBEIT,
			interface{}(ENTGELT_ABRECHNUNG).(fmt.Stringer).String():                         ENTGELT_ABRECHNUNG,
			interface{}(SPERRKOSTEN).(fmt.Stringer).String():                                SPERRKOSTEN,
			interface{}(ENTSPERRKOSTEN).(fmt.Stringer).String():                             ENTSPERRKOSTEN,
			interface{}(MAHNKOSTEN).(fmt.Stringer).String():                                 MAHNKOSTEN,
			interface{}(MEHR_MINDERMENGEN).(fmt.Stringer).String():                          MEHR_MINDERMENGEN,
			interface{}(INKASSOKOSTEN).(fmt.Stringer).String():                              INKASSOKOSTEN,
			interface{}(BLINDMEHRLEISTUNG).(fmt.Stringer).String():                          BLINDMEHRLEISTUNG,
			interface{}(ENTGELT_MESSUNG_ABLESUNG).(fmt.Stringer).String():                   ENTGELT_MESSUNG_ABLESUNG,
			interface{}(ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK).(fmt.Stringer).String(): ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK,
			interface{}(AUSGLEICHSENERGIE).(fmt.Stringer).String():                          AUSGLEICHSENERGIE,
			interface{}(ZAEHLEINRICHTUNG).(fmt.Stringer).String():                           ZAEHLEINRICHTUNG,
			interface{}(WANDLER_MENGENUMWERTER).(fmt.Stringer).String():                     WANDLER_MENGENUMWERTER,
			interface{}(KOMMUNIKATIONSEINRICHTUNG).(fmt.Stringer).String():                  KOMMUNIKATIONSEINRICHTUNG,
			interface{}(TECHNISCHE_STEUEREINRICHTUNG).(fmt.Stringer).String():               TECHNISCHE_STEUEREINRICHTUNG,
			interface{}(PARAGRAF_19_STROM_NEV_UMLAGE).(fmt.Stringer).String():               PARAGRAF_19_STROM_NEV_UMLAGE,
			interface{}(BEFESTIGUNGSEINRICHTUNG).(fmt.Stringer).String():                    BEFESTIGUNGSEINRICHTUNG,
			interface{}(OFFSHORE_HAFTUNGSUMLAGE).(fmt.Stringer).String():                    OFFSHORE_HAFTUNGSUMLAGE,
			interface{}(FIXE_ARBEITSENTGELTKOMPONENTE).(fmt.Stringer).String():              FIXE_ARBEITSENTGELTKOMPONENTE,
			interface{}(FIXE_LEISTUNGSENTGELTKOMPONENTE).(fmt.Stringer).String():            FIXE_LEISTUNGSENTGELTKOMPONENTE,
			interface{}(UMLAGE_ABSCHALTBARE_LASTEN).(fmt.Stringer).String():                 UMLAGE_ABSCHALTBARE_LASTEN,
			interface{}(MEHRMENGE).(fmt.Stringer).String():                                  MEHRMENGE,
			interface{}(MINDERMENGE).(fmt.Stringer).String():                                MINDERMENGE,
			interface{}(ENERGIESTEUER).(fmt.Stringer).String():                              ENERGIESTEUER,
			interface{}(SMARTMETER_GATEWAY).(fmt.Stringer).String():                         SMARTMETER_GATEWAY,
			interface{}(STEUERBOX).(fmt.Stringer).String():                                  STEUERBOX,
			interface{}(MSB_INKL_MESSUNG).(fmt.Stringer).String():                           MSB_INKL_MESSUNG,
			interface{}(AUSGLEICHSENERGIE_UNTERDECKUNG).(fmt.Stringer).String():             AUSGLEICHSENERGIE_UNTERDECKUNG,
			interface{}(ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_1_MSBG).(fmt.Stringer).String(): ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_1_MSBG,
			interface{}(ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_2_MSBG).(fmt.Stringer).String(): ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_2_MSBG,
			interface{}(ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_3_MSBG).(fmt.Stringer).String(): ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_3_MSBG,
			interface{}(ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_4_MSBG).(fmt.Stringer).String(): ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_4_MSBG,
			interface{}(ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_5_MSBG).(fmt.Stringer).String(): ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_5_MSBG,
			interface{}(ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_3_MSBG).(fmt.Stringer).String():   ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_3_MSBG,
			interface{}(EINBAU_IMS).(fmt.Stringer).String():                                 EINBAU_IMS,
			interface{}(EINBAU_KME_RLM).(fmt.Stringer).String():                             EINBAU_KME_RLM,
			interface{}(EINBAU_WANDLER).(fmt.Stringer).String():                             EINBAU_WANDLER,
			interface{}(WEITERE_ENERGIEFLUSSRICHTUNG).(fmt.Stringer).String():               WEITERE_ENERGIEFLUSSRICHTUNG,
			interface{}(VERGLEICHSMESSUNG).(fmt.Stringer).String():                          VERGLEICHSMESSUNG,
			interface{}(ÄNDERUNG_MESSEBENE).(fmt.Stringer).String():                         ÄNDERUNG_MESSEBENE,
			interface{}(EINBAU_STEUERBOX).(fmt.Stringer).String():                           EINBAU_STEUERBOX,
			interface{}(ANSCHLUSS_TR_STEUERBOX_SR).(fmt.Stringer).String():                  ANSCHLUSS_TR_STEUERBOX_SR,
			interface{}(SCHWACHLAST_KA).(fmt.Stringer).String():                             SCHWACHLAST_KA,
		}
	}
}

// MarshalJSON is generated so BDEWArtikelnummer satisfies json.Marshaler.
func (r BDEWArtikelnummer) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _BDEWArtikelnummerValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid BDEWArtikelnummer: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so BDEWArtikelnummer satisfies json.Unmarshaler.
func (r *BDEWArtikelnummer) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BDEWArtikelnummer should be a string, got %s", data)
	}
	v, ok := _BDEWArtikelnummerNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid BDEWArtikelnummer %q", s)
	}
	*r = v
	return nil
}
