// Code generated by jsonenums --type BDEWArtikelnummer; DO NOT EDIT.

package bdewartikelnummer

import (
	"encoding/json"
	"fmt"
)

var (
	_BDEWArtikelnummerNameToValue = map[string]BDEWArtikelnummer{
		"LEISTUNG":                               LEISTUNG,
		"LEISTUNGPAUSCHAL":                       LEISTUNGPAUSCHAL,
		"GRUNDPREIS":                             GRUNDPREIS,
		"REGELENERGIEPREIS":                      REGELENERGIEPREIS,
		"REGELENERGIELEISTUNG":                   REGELENERGIELEISTUNG,
		"NOTSTROMLIEFERUNGARBEIT":                NOTSTROMLIEFERUNGARBEIT,
		"NOTSTROMLIEFERUNGLEISTUNG":              NOTSTROMLIEFERUNGLEISTUNG,
		"RESERVENETZKAPAZITAET":                  RESERVENETZKAPAZITAET,
		"RESERVELEISTUNG":                        RESERVELEISTUNG,
		"ZUSAETZLICHEABLESUNG":                   ZUSAETZLICHEABLESUNG,
		"PRUEFGEBUEHRENAUSSERPLANMAESSIG":        PRUEFGEBUEHRENAUSSERPLANMAESSIG,
		"WIRKARBEIT":                             WIRKARBEIT,
		"SINGULAERGENUTZTEBETRIEBSMITTEL":        SINGULAERGENUTZTEBETRIEBSMITTEL,
		"ABGABEKWKG":                             ABGABEKWKG,
		"ABSCHLAG":                               ABSCHLAG,
		"KONZESSIONSABGABE":                      KONZESSIONSABGABE,
		"ENTGELT_FERNAUSLESUNG":                  ENTGELT_FERNAUSLESUNG,
		"UNTERMESSUNG":                           UNTERMESSUNG,
		"BLINDMEHRARBEIT":                        BLINDMEHRARBEIT,
		"ENTGELT_ABRECHNUNG":                     ENTGELT_ABRECHNUNG,
		"SPERRKOSTEN":                            SPERRKOSTEN,
		"ENTSPERRKOSTEN":                         ENTSPERRKOSTEN,
		"MAHNKOSTEN":                             MAHNKOSTEN,
		"MEHRMMINDERMENGEN":                      MEHRMMINDERMENGEN,
		"INKASSOKOSTEN":                          INKASSOKOSTEN,
		"BLINDMEHRLEISTUNG":                      BLINDMEHRLEISTUNG,
		"ENTGELTMESSUNGABLESUNG":                 ENTGELTMESSUNGABLESUNG,
		"ENTGELTEINBAUBETRIEBWARTUNGMESSTECHNIK": ENTGELTEINBAUBETRIEBWARTUNGMESSTECHNIK,
		"AUSGLEICHSENERGIE":                      AUSGLEICHSENERGIE,
		"ZAEHLEINRICHTUNG":                       ZAEHLEINRICHTUNG,
		"WANDLERMENGENUMWERTER":                  WANDLERMENGENUMWERTER,
		"KOMMUNIKATIONSEINRICHTUNG":              KOMMUNIKATIONSEINRICHTUNG,
		"TECHNISCHESTEUEREINRICHTUNG":            TECHNISCHESTEUEREINRICHTUNG,
		"PARAGRAF19STROMNEVUMLAGE":               PARAGRAF19STROMNEVUMLAGE,
		"BEFESTIGUNGSEINRICHTUNG":                BEFESTIGUNGSEINRICHTUNG,
		"OFFSHOREHAFTUNGSUMLAGE":                 OFFSHOREHAFTUNGSUMLAGE,
		"FIXEARBEITSENTGELTKOMPONENTE":           FIXEARBEITSENTGELTKOMPONENTE,
		"FIXELEISTUNGSENTGELTKOMPONENTE":         FIXELEISTUNGSENTGELTKOMPONENTE,
		"UMLAGEABSCHALTBARELASTEN":               UMLAGEABSCHALTBARELASTEN,
		"MEHRMENGE":                              MEHRMENGE,
		"MINDERMENGE":                            MINDERMENGE,
		"ENERGIESTEUER":                          ENERGIESTEUER,
		"SMARTMETERGATEWAY":                      SMARTMETERGATEWAY,
		"STEUERBOX":                              STEUERBOX,
		"MSBINKLMESSUNG":                         MSBINKLMESSUNG,
	}

	_BDEWArtikelnummerValueToName = map[BDEWArtikelnummer]string{
		LEISTUNG:                               "LEISTUNG",
		LEISTUNGPAUSCHAL:                       "LEISTUNGPAUSCHAL",
		GRUNDPREIS:                             "GRUNDPREIS",
		REGELENERGIEPREIS:                      "REGELENERGIEPREIS",
		REGELENERGIELEISTUNG:                   "REGELENERGIELEISTUNG",
		NOTSTROMLIEFERUNGARBEIT:                "NOTSTROMLIEFERUNGARBEIT",
		NOTSTROMLIEFERUNGLEISTUNG:              "NOTSTROMLIEFERUNGLEISTUNG",
		RESERVENETZKAPAZITAET:                  "RESERVENETZKAPAZITAET",
		RESERVELEISTUNG:                        "RESERVELEISTUNG",
		ZUSAETZLICHEABLESUNG:                   "ZUSAETZLICHEABLESUNG",
		PRUEFGEBUEHRENAUSSERPLANMAESSIG:        "PRUEFGEBUEHRENAUSSERPLANMAESSIG",
		WIRKARBEIT:                             "WIRKARBEIT",
		SINGULAERGENUTZTEBETRIEBSMITTEL:        "SINGULAERGENUTZTEBETRIEBSMITTEL",
		ABGABEKWKG:                             "ABGABEKWKG",
		ABSCHLAG:                               "ABSCHLAG",
		KONZESSIONSABGABE:                      "KONZESSIONSABGABE",
		ENTGELT_FERNAUSLESUNG:                  "ENTGELT_FERNAUSLESUNG",
		UNTERMESSUNG:                           "UNTERMESSUNG",
		BLINDMEHRARBEIT:                        "BLINDMEHRARBEIT",
		ENTGELT_ABRECHNUNG:                     "ENTGELT_ABRECHNUNG",
		SPERRKOSTEN:                            "SPERRKOSTEN",
		ENTSPERRKOSTEN:                         "ENTSPERRKOSTEN",
		MAHNKOSTEN:                             "MAHNKOSTEN",
		MEHRMMINDERMENGEN:                      "MEHRMMINDERMENGEN",
		INKASSOKOSTEN:                          "INKASSOKOSTEN",
		BLINDMEHRLEISTUNG:                      "BLINDMEHRLEISTUNG",
		ENTGELTMESSUNGABLESUNG:                 "ENTGELTMESSUNGABLESUNG",
		ENTGELTEINBAUBETRIEBWARTUNGMESSTECHNIK: "ENTGELTEINBAUBETRIEBWARTUNGMESSTECHNIK",
		AUSGLEICHSENERGIE:                      "AUSGLEICHSENERGIE",
		ZAEHLEINRICHTUNG:                       "ZAEHLEINRICHTUNG",
		WANDLERMENGENUMWERTER:                  "WANDLERMENGENUMWERTER",
		KOMMUNIKATIONSEINRICHTUNG:              "KOMMUNIKATIONSEINRICHTUNG",
		TECHNISCHESTEUEREINRICHTUNG:            "TECHNISCHESTEUEREINRICHTUNG",
		PARAGRAF19STROMNEVUMLAGE:               "PARAGRAF19STROMNEVUMLAGE",
		BEFESTIGUNGSEINRICHTUNG:                "BEFESTIGUNGSEINRICHTUNG",
		OFFSHOREHAFTUNGSUMLAGE:                 "OFFSHOREHAFTUNGSUMLAGE",
		FIXEARBEITSENTGELTKOMPONENTE:           "FIXEARBEITSENTGELTKOMPONENTE",
		FIXELEISTUNGSENTGELTKOMPONENTE:         "FIXELEISTUNGSENTGELTKOMPONENTE",
		UMLAGEABSCHALTBARELASTEN:               "UMLAGEABSCHALTBARELASTEN",
		MEHRMENGE:                              "MEHRMENGE",
		MINDERMENGE:                            "MINDERMENGE",
		ENERGIESTEUER:                          "ENERGIESTEUER",
		SMARTMETERGATEWAY:                      "SMARTMETERGATEWAY",
		STEUERBOX:                              "STEUERBOX",
		MSBINKLMESSUNG:                         "MSBINKLMESSUNG",
	}
)

func init() {
	var v BDEWArtikelnummer
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_BDEWArtikelnummerNameToValue = map[string]BDEWArtikelnummer{
			interface{}(LEISTUNG).(fmt.Stringer).String():                               LEISTUNG,
			interface{}(LEISTUNGPAUSCHAL).(fmt.Stringer).String():                       LEISTUNGPAUSCHAL,
			interface{}(GRUNDPREIS).(fmt.Stringer).String():                             GRUNDPREIS,
			interface{}(REGELENERGIEPREIS).(fmt.Stringer).String():                      REGELENERGIEPREIS,
			interface{}(REGELENERGIELEISTUNG).(fmt.Stringer).String():                   REGELENERGIELEISTUNG,
			interface{}(NOTSTROMLIEFERUNGARBEIT).(fmt.Stringer).String():                NOTSTROMLIEFERUNGARBEIT,
			interface{}(NOTSTROMLIEFERUNGLEISTUNG).(fmt.Stringer).String():              NOTSTROMLIEFERUNGLEISTUNG,
			interface{}(RESERVENETZKAPAZITAET).(fmt.Stringer).String():                  RESERVENETZKAPAZITAET,
			interface{}(RESERVELEISTUNG).(fmt.Stringer).String():                        RESERVELEISTUNG,
			interface{}(ZUSAETZLICHEABLESUNG).(fmt.Stringer).String():                   ZUSAETZLICHEABLESUNG,
			interface{}(PRUEFGEBUEHRENAUSSERPLANMAESSIG).(fmt.Stringer).String():        PRUEFGEBUEHRENAUSSERPLANMAESSIG,
			interface{}(WIRKARBEIT).(fmt.Stringer).String():                             WIRKARBEIT,
			interface{}(SINGULAERGENUTZTEBETRIEBSMITTEL).(fmt.Stringer).String():        SINGULAERGENUTZTEBETRIEBSMITTEL,
			interface{}(ABGABEKWKG).(fmt.Stringer).String():                             ABGABEKWKG,
			interface{}(ABSCHLAG).(fmt.Stringer).String():                               ABSCHLAG,
			interface{}(KONZESSIONSABGABE).(fmt.Stringer).String():                      KONZESSIONSABGABE,
			interface{}(ENTGELT_FERNAUSLESUNG).(fmt.Stringer).String():                  ENTGELT_FERNAUSLESUNG,
			interface{}(UNTERMESSUNG).(fmt.Stringer).String():                           UNTERMESSUNG,
			interface{}(BLINDMEHRARBEIT).(fmt.Stringer).String():                        BLINDMEHRARBEIT,
			interface{}(ENTGELT_ABRECHNUNG).(fmt.Stringer).String():                     ENTGELT_ABRECHNUNG,
			interface{}(SPERRKOSTEN).(fmt.Stringer).String():                            SPERRKOSTEN,
			interface{}(ENTSPERRKOSTEN).(fmt.Stringer).String():                         ENTSPERRKOSTEN,
			interface{}(MAHNKOSTEN).(fmt.Stringer).String():                             MAHNKOSTEN,
			interface{}(MEHRMMINDERMENGEN).(fmt.Stringer).String():                      MEHRMMINDERMENGEN,
			interface{}(INKASSOKOSTEN).(fmt.Stringer).String():                          INKASSOKOSTEN,
			interface{}(BLINDMEHRLEISTUNG).(fmt.Stringer).String():                      BLINDMEHRLEISTUNG,
			interface{}(ENTGELTMESSUNGABLESUNG).(fmt.Stringer).String():                 ENTGELTMESSUNGABLESUNG,
			interface{}(ENTGELTEINBAUBETRIEBWARTUNGMESSTECHNIK).(fmt.Stringer).String(): ENTGELTEINBAUBETRIEBWARTUNGMESSTECHNIK,
			interface{}(AUSGLEICHSENERGIE).(fmt.Stringer).String():                      AUSGLEICHSENERGIE,
			interface{}(ZAEHLEINRICHTUNG).(fmt.Stringer).String():                       ZAEHLEINRICHTUNG,
			interface{}(WANDLERMENGENUMWERTER).(fmt.Stringer).String():                  WANDLERMENGENUMWERTER,
			interface{}(KOMMUNIKATIONSEINRICHTUNG).(fmt.Stringer).String():              KOMMUNIKATIONSEINRICHTUNG,
			interface{}(TECHNISCHESTEUEREINRICHTUNG).(fmt.Stringer).String():            TECHNISCHESTEUEREINRICHTUNG,
			interface{}(PARAGRAF19STROMNEVUMLAGE).(fmt.Stringer).String():               PARAGRAF19STROMNEVUMLAGE,
			interface{}(BEFESTIGUNGSEINRICHTUNG).(fmt.Stringer).String():                BEFESTIGUNGSEINRICHTUNG,
			interface{}(OFFSHOREHAFTUNGSUMLAGE).(fmt.Stringer).String():                 OFFSHOREHAFTUNGSUMLAGE,
			interface{}(FIXEARBEITSENTGELTKOMPONENTE).(fmt.Stringer).String():           FIXEARBEITSENTGELTKOMPONENTE,
			interface{}(FIXELEISTUNGSENTGELTKOMPONENTE).(fmt.Stringer).String():         FIXELEISTUNGSENTGELTKOMPONENTE,
			interface{}(UMLAGEABSCHALTBARELASTEN).(fmt.Stringer).String():               UMLAGEABSCHALTBARELASTEN,
			interface{}(MEHRMENGE).(fmt.Stringer).String():                              MEHRMENGE,
			interface{}(MINDERMENGE).(fmt.Stringer).String():                            MINDERMENGE,
			interface{}(ENERGIESTEUER).(fmt.Stringer).String():                          ENERGIESTEUER,
			interface{}(SMARTMETERGATEWAY).(fmt.Stringer).String():                      SMARTMETERGATEWAY,
			interface{}(STEUERBOX).(fmt.Stringer).String():                              STEUERBOX,
			interface{}(MSBINKLMESSUNG).(fmt.Stringer).String():                         MSBINKLMESSUNG,
		}
	}
}

// MarshalJSON is generated so BDEWArtikelnummer satisfies json.Marshaler.
func (r BDEWArtikelnummer) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _BDEWArtikelnummerValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid BDEWArtikelnummer: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so BDEWArtikelnummer satisfies json.Unmarshaler.
func (r *BDEWArtikelnummer) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BDEWArtikelnummer should be a string, got %s", data)
	}
	v, ok := _BDEWArtikelnummerNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid BDEWArtikelnummer %q", s)
	}
	*r = v
	return nil
}
