// Code generated by "stringer --type BDEWArtikelnummer"; DO NOT EDIT.

package bdewartikelnummer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Leistung-1]
	_ = x[Leistungpauschal-2]
	_ = x[Grundpreis-3]
	_ = x[Regelenergiearbeit-4]
	_ = x[Regelenergieleistung-5]
	_ = x[Notstromlieferungarbeit-6]
	_ = x[Notstromlieferungleistung-7]
	_ = x[Reservenetzkapazitaet-8]
	_ = x[Reserveleistung-9]
	_ = x[Zusaetzlicheablesung-10]
	_ = x[Pruefgebuehrenausserplanmaessig-11]
	_ = x[Wirkarbeit-12]
	_ = x[Singulaergenutztebetriebsmittel-13]
	_ = x[Abgabekwkg-14]
	_ = x[Abschlag-15]
	_ = x[Konzessionsabgabe-16]
	_ = x[Entgelt_fernauslesung-17]
	_ = x[Untermessung-18]
	_ = x[Blindmehrarbeit-19]
	_ = x[Entgelt_abrechnung-20]
	_ = x[Sperrkosten-21]
	_ = x[Entsperrkosten-22]
	_ = x[Mahnkosten-23]
	_ = x[MehrMmindermengen-24]
	_ = x[Inkassokosten-25]
	_ = x[Blindmehrleistung-26]
	_ = x[EntgeltmessungAblesung-27]
	_ = x[EntgelteinbauBetriebWartungMesstechnik-28]
	_ = x[Ausgleichsenergie-29]
	_ = x[Zaehleinrichtung-30]
	_ = x[WandlerMengenumwerter-31]
	_ = x[Kommunikationseinrichtung-32]
	_ = x[TechnischeSteuereinrichtung-33]
	_ = x[Paragraf19StromNevUmlage-34]
	_ = x[Befestigungseinrichtung-35]
	_ = x[OffshoreHaftungsumlage-36]
	_ = x[FixeArbeitsentgeltkomponente-37]
	_ = x[FixeLeistungsentgeltkomponente-38]
	_ = x[UmlageAbschaltbareLasten-39]
	_ = x[Mehrmenge-40]
	_ = x[Mindermenge-41]
	_ = x[Energiesteuer-42]
	_ = x[SmartmeterGateway-43]
	_ = x[Steuerbox-44]
	_ = x[MsbInklMessung-45]
}

const _BDEWArtikelnummer_name = "LeistungLeistungpauschalGrundpreisRegelenergiearbeitRegelenergieleistungNotstromlieferungarbeitNotstromlieferungleistungReservenetzkapazitaetReserveleistungZusaetzlicheablesungPruefgebuehrenausserplanmaessigWirkarbeitSingulaergenutztebetriebsmittelAbgabekwkgAbschlagKonzessionsabgabeEntgelt_fernauslesungUntermessungBlindmehrarbeitEntgelt_abrechnungSperrkostenEntsperrkostenMahnkostenMehrMmindermengenInkassokostenBlindmehrleistungEntgeltmessungAblesungEntgelteinbauBetriebWartungMesstechnikAusgleichsenergieZaehleinrichtungWandlerMengenumwerterKommunikationseinrichtungTechnischeSteuereinrichtungParagraf19StromNevUmlageBefestigungseinrichtungOffshoreHaftungsumlageFixeArbeitsentgeltkomponenteFixeLeistungsentgeltkomponenteUmlageAbschaltbareLastenMehrmengeMindermengeEnergiesteuerSmartmeterGatewaySteuerboxMsbInklMessung"

var _BDEWArtikelnummer_index = [...]uint16{0, 8, 24, 34, 52, 72, 95, 120, 141, 156, 176, 207, 217, 248, 258, 266, 283, 304, 316, 331, 349, 360, 374, 384, 401, 414, 431, 453, 491, 508, 524, 545, 570, 597, 621, 644, 666, 694, 724, 748, 757, 768, 781, 798, 807, 821}

func (i BDEWArtikelnummer) String() string {
	i -= 1
	if i < 0 || i >= BDEWArtikelnummer(len(_BDEWArtikelnummer_index)-1) {
		return "BDEWArtikelnummer(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BDEWArtikelnummer_name[_BDEWArtikelnummer_index[i]:_BDEWArtikelnummer_index[i+1]]
}
