// Code generated by jsonenums --type LokationsbuendelstrukturVorhanden; DO NOT EDIT.

package lokationsbuendelstrukturvorhanden

import (
	"encoding/json"
	"fmt"
)

var (
	_LokationsbuendelstrukturVorhandenNameToValue = map[string]LokationsbuendelstrukturVorhanden{
		"VORHANDEN":       VORHANDEN,
		"NICHT_VORHANDEN": NICHT_VORHANDEN,
		"Z31":             VORHANDEN,
		"Z39":             NICHT_VORHANDEN,
	}

	_LokationsbuendelstrukturVorhandenValueToName = map[LokationsbuendelstrukturVorhanden]string{
		VORHANDEN:       "VORHANDEN",
		NICHT_VORHANDEN: "NICHT_VORHANDEN",
	}
)

func init() {
	var v LokationsbuendelstrukturVorhanden
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_LokationsbuendelstrukturVorhandenNameToValue = map[string]LokationsbuendelstrukturVorhanden{
			interface{}(VORHANDEN).(fmt.Stringer).String():       VORHANDEN,
			interface{}(NICHT_VORHANDEN).(fmt.Stringer).String(): NICHT_VORHANDEN,
			"Z31": VORHANDEN,
			"Z39": NICHT_VORHANDEN,
		}
	}
}

// MarshalJSON is generated so LokationsbuendelstrukturVorhanden satisfies json.Marshaler.
func (r LokationsbuendelstrukturVorhanden) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _LokationsbuendelstrukturVorhandenValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid LokationsbuendelstrukturVorhanden: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so LokationsbuendelstrukturVorhanden satisfies json.Unmarshaler.
func (r *LokationsbuendelstrukturVorhanden) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LokationsbuendelstrukturVorhanden should be a string, got %s", data)
	}
	v, ok := _LokationsbuendelstrukturVorhandenNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid LokationsbuendelstrukturVorhanden %q", s)
	}
	*r = v
	return nil
}
