// Code generated by "stringer --type LokationsbuendelstrukturVorhanden"; DO NOT EDIT.

package lokationsbuendelstrukturvorhanden

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VORHANDEN-1]
	_ = x[NICHT_VORHANDEN-2]
}

const _LokationsbuendelstrukturVorhanden_name = "VORHANDENNICHT_VORHANDEN"

var _LokationsbuendelstrukturVorhanden_index = [...]uint8{0, 9, 24}

func (i LokationsbuendelstrukturVorhanden) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_LokationsbuendelstrukturVorhanden_index)-1 {
		return "LokationsbuendelstrukturVorhanden(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LokationsbuendelstrukturVorhanden_name[_LokationsbuendelstrukturVorhanden_index[idx]:_LokationsbuendelstrukturVorhanden_index[idx+1]]
}
