// Code generated by "stringer --type HaeufigkeitZaehlzeit"; DO NOT EDIT.

package haeufigkeitzaehlzeit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EINMALIG-1]
	_ = x[JAEHRLICH-2]
}

const _HaeufigkeitZaehlzeit_name = "EINMALIGJAEHRLICH"

var _HaeufigkeitZaehlzeit_index = [...]uint8{0, 8, 17}

func (i HaeufigkeitZaehlzeit) String() string {
	i -= 1
	if i < 0 || i >= HaeufigkeitZaehlzeit(len(_HaeufigkeitZaehlzeit_index)-1) {
		return "HaeufigkeitZaehlzeit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _HaeufigkeitZaehlzeit_name[_HaeufigkeitZaehlzeit_index[i]:_HaeufigkeitZaehlzeit_index[i+1]]
}
