// Code generated by jsonenums --type BezeichnungSummenzeitreihe; DO NOT EDIT.

package bezeichnungsummenzeitreihe

import (
	"encoding/json"
	"fmt"
)

var (
	_BezeichnungSummenzeitreiheNameToValue = map[string]BezeichnungSummenzeitreihe{
		"BG_SZR_B":    BG_SZR_B,
		"BG_SZR_C":    BG_SZR_C,
		"BK_SZR_A":    BK_SZR_A,
		"BK_SZR_B_RZ": BK_SZR_B_RZ,
		"BK_SZR_B_BG": BK_SZR_B_BG,
		"BK_SZR_C":    BK_SZR_C,
		"LF_SZR_A":    LF_SZR_A,
		"LF_SZR_B_RZ": LF_SZR_B_RZ,
		"LF_SZR_B_BG": LF_SZR_B_BG,
		"DZUE":        DZUE,
		"NZR":         NZR,
		"ASZR":        ASZR,
		"NGZ":         NGZ,
	}

	_BezeichnungSummenzeitreiheValueToName = map[BezeichnungSummenzeitreihe]string{
		BG_SZR_B:    "BG_SZR_B",
		BG_SZR_C:    "BG_SZR_C",
		BK_SZR_A:    "BK_SZR_A",
		BK_SZR_B_RZ: "BK_SZR_B_RZ",
		BK_SZR_B_BG: "BK_SZR_B_BG",
		BK_SZR_C:    "BK_SZR_C",
		LF_SZR_A:    "LF_SZR_A",
		LF_SZR_B_RZ: "LF_SZR_B_RZ",
		LF_SZR_B_BG: "LF_SZR_B_BG",
		DZUE:        "DZUE",
		NZR:         "NZR",
		ASZR:        "ASZR",
		NGZ:         "NGZ",
	}
)

func init() {
	var v BezeichnungSummenzeitreihe
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_BezeichnungSummenzeitreiheNameToValue = map[string]BezeichnungSummenzeitreihe{
			interface{}(BG_SZR_B).(fmt.Stringer).String():    BG_SZR_B,
			interface{}(BG_SZR_C).(fmt.Stringer).String():    BG_SZR_C,
			interface{}(BK_SZR_A).(fmt.Stringer).String():    BK_SZR_A,
			interface{}(BK_SZR_B_RZ).(fmt.Stringer).String(): BK_SZR_B_RZ,
			interface{}(BK_SZR_B_BG).(fmt.Stringer).String(): BK_SZR_B_BG,
			interface{}(BK_SZR_C).(fmt.Stringer).String():    BK_SZR_C,
			interface{}(LF_SZR_A).(fmt.Stringer).String():    LF_SZR_A,
			interface{}(LF_SZR_B_RZ).(fmt.Stringer).String(): LF_SZR_B_RZ,
			interface{}(LF_SZR_B_BG).(fmt.Stringer).String(): LF_SZR_B_BG,
			interface{}(DZUE).(fmt.Stringer).String():        DZUE,
			interface{}(NZR).(fmt.Stringer).String():         NZR,
			interface{}(ASZR).(fmt.Stringer).String():        ASZR,
			interface{}(NGZ).(fmt.Stringer).String():         NGZ,
		}
	}
}

// MarshalJSON is generated so BezeichnungSummenzeitreihe satisfies json.Marshaler.
func (r BezeichnungSummenzeitreihe) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _BezeichnungSummenzeitreiheValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid BezeichnungSummenzeitreihe: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so BezeichnungSummenzeitreihe satisfies json.Unmarshaler.
func (r *BezeichnungSummenzeitreihe) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BezeichnungSummenzeitreihe should be a string, got %s", data)
	}
	v, ok := _BezeichnungSummenzeitreiheNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid BezeichnungSummenzeitreihe %q", s)
	}
	*r = v
	return nil
}
