// Code generated by "stringer --type BezeichnungSummenzeitreihe"; DO NOT EDIT.

package bezeichnungsummenzeitreihe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BG_SZR_B-1]
	_ = x[BG_SZR_C-2]
	_ = x[BK_SZR_A-3]
	_ = x[BK_SZR_B_RZ-4]
	_ = x[BK_SZR_B_BG-5]
	_ = x[BK_SZR_C-6]
	_ = x[LF_SZR_A-7]
	_ = x[LF_SZR_B_RZ-8]
	_ = x[LF_SZR_B_BG-9]
	_ = x[DZUE-10]
	_ = x[NZR-11]
	_ = x[ASZR-12]
	_ = x[NGZ-13]
}

const _BezeichnungSummenzeitreihe_name = "BG_SZR_BBG_SZR_CBK_SZR_ABK_SZR_B_RZBK_SZR_B_BGBK_SZR_CLF_SZR_ALF_SZR_B_RZLF_SZR_B_BGDZUENZRASZRNGZ"

var _BezeichnungSummenzeitreihe_index = [...]uint8{0, 8, 16, 24, 35, 46, 54, 62, 73, 84, 88, 91, 95, 98}

func (i BezeichnungSummenzeitreihe) String() string {
	i -= 1
	if i < 0 || i >= BezeichnungSummenzeitreihe(len(_BezeichnungSummenzeitreihe_index)-1) {
		return "BezeichnungSummenzeitreihe(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BezeichnungSummenzeitreihe_name[_BezeichnungSummenzeitreihe_index[i]:_BezeichnungSummenzeitreihe_index[i+1]]
}
