// Code generated by "stringer --type LeistungsbeschreibungDesSteuerkanals"; DO NOT EDIT.

package leistungsbeschreibungdessteuerkanals

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AN_AUS-1]
	_ = x[GESTUFT-2]
}

const _LeistungsbeschreibungDesSteuerkanals_name = "AN_AUSGESTUFT"

var _LeistungsbeschreibungDesSteuerkanals_index = [...]uint8{0, 6, 13}

func (i LeistungsbeschreibungDesSteuerkanals) String() string {
	i -= 1
	if i < 0 || i >= LeistungsbeschreibungDesSteuerkanals(len(_LeistungsbeschreibungDesSteuerkanals_index)-1) {
		return "LeistungsbeschreibungDesSteuerkanals(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LeistungsbeschreibungDesSteuerkanals_name[_LeistungsbeschreibungDesSteuerkanals_index[i]:_LeistungsbeschreibungDesSteuerkanals_index[i+1]]
}
