// Code generated by "stringer --type NNRechnungsart"; DO NOT EDIT.

package nnrechnungsart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HANDELSRECHNUNG-1]
	_ = x[SELBSTAUSGESTELLT-2]
}

const _NNRechnungsart_name = "HANDELSRECHNUNGSELBSTAUSGESTELLT"

var _NNRechnungsart_index = [...]uint8{0, 15, 32}

func (i NNRechnungsart) String() string {
	i -= 1
	if i < 0 || i >= NNRechnungsart(len(_NNRechnungsart_index)-1) {
		return "NNRechnungsart(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _NNRechnungsart_name[_NNRechnungsart_index[i]:_NNRechnungsart_index[i+1]]
}
