// Code generated by "stringer --type InbetriebsetzungTechnischeRessource"; DO NOT EDIT.

package inbetriebsetzungtechnischeressource

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NACH_2023-1]
	_ = x[VOR_2024-2]
}

const _InbetriebsetzungTechnischeRessource_name = "NACH_2023VOR_2024"

var _InbetriebsetzungTechnischeRessource_index = [...]uint8{0, 9, 17}

func (i InbetriebsetzungTechnischeRessource) String() string {
	i -= 1
	if i < 0 || i >= InbetriebsetzungTechnischeRessource(len(_InbetriebsetzungTechnischeRessource_index)-1) {
		return "InbetriebsetzungTechnischeRessource(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _InbetriebsetzungTechnischeRessource_name[_InbetriebsetzungTechnischeRessource_index[i]:_InbetriebsetzungTechnischeRessource_index[i+1]]
}
