// Code generated by jsonenums --type InbetriebsetzungTechnischeRessource; DO NOT EDIT.

package inbetriebsetzungtechnischeressource

import (
	"encoding/json"
	"fmt"
)

var (
	_InbetriebsetzungTechnischeRessourceNameToValue = map[string]InbetriebsetzungTechnischeRessource{
		"NACH_2023": NACH_2023,
		"VOR_2024":  VOR_2024,
	}

	_InbetriebsetzungTechnischeRessourceValueToName = map[InbetriebsetzungTechnischeRessource]string{
		NACH_2023: "NACH_2023",
		VOR_2024:  "VOR_2024",
	}
)

func init() {
	var v InbetriebsetzungTechnischeRessource
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_InbetriebsetzungTechnischeRessourceNameToValue = map[string]InbetriebsetzungTechnischeRessource{
			interface{}(NACH_2023).(fmt.Stringer).String(): NACH_2023,
			interface{}(VOR_2024).(fmt.Stringer).String():  VOR_2024,
		}
	}
}

// MarshalJSON is generated so InbetriebsetzungTechnischeRessource satisfies json.Marshaler.
func (r InbetriebsetzungTechnischeRessource) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _InbetriebsetzungTechnischeRessourceValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid InbetriebsetzungTechnischeRessource: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so InbetriebsetzungTechnischeRessource satisfies json.Unmarshaler.
func (r *InbetriebsetzungTechnischeRessource) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("InbetriebsetzungTechnischeRessource should be a string, got %s", data)
	}
	v, ok := _InbetriebsetzungTechnischeRessourceNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid InbetriebsetzungTechnischeRessource %q", s)
	}
	*r = v
	return nil
}
