// Code generated by "stringer --type Messwerterfassung"; DO NOT EDIT.

package messwerterfassung

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FERN_AUSLESBAR-1]
	_ = x[MANUELL_AUSGELESEN-2]
}

const _Messwerterfassung_name = "FERN_AUSLESBARMANUELL_AUSGELESEN"

var _Messwerterfassung_index = [...]uint8{0, 14, 32}

func (i Messwerterfassung) String() string {
	i -= 1
	if i < 0 || i >= Messwerterfassung(len(_Messwerterfassung_index)-1) {
		return "Messwerterfassung(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Messwerterfassung_name[_Messwerterfassung_index[i]:_Messwerterfassung_index[i+1]]
}
