// Code generated by "stringer --type Messwertstatus"; DO NOT EDIT.

package messwertstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ABGELESEN-0]
	_ = x[ERSATZWERT-1]
	_ = x[VORSCHLAGSWERT-2]
	_ = x[PROGNOSEWERT-3]
	_ = x[VORLAUFIGERWERT-4]
	_ = x[ENERGIEMENGESUMMIERT-5]
	_ = x[FEHLT-6]
}

const _Messwertstatus_name = "ABGELESENERSATZWERTVORSCHLAGSWERTPROGNOSEWERTVORLAUFIGERWERTENERGIEMENGESUMMIERTFEHLT"

var _Messwertstatus_index = [...]uint8{0, 9, 19, 33, 45, 60, 80, 85}

func (i Messwertstatus) String() string {
	if i < 0 || i >= Messwertstatus(len(_Messwertstatus_index)-1) {
		return "Messwertstatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Messwertstatus_name[_Messwertstatus_index[i]:_Messwertstatus_index[i+1]]
}
