// Code generated by jsonenums --type AufAbschlagsziel; DO NOT EDIT.

package aufabschlagsziel

import (
	"encoding/json"
	"fmt"
)

var (
	_AufAbschlagszielNameToValue = map[string]AufAbschlagsziel{
		"ARBEITSPREIS_HT":    ARBEITSPREIS_HT,
		"ARBEITSPREIS_NT":    ARBEITSPREIS_NT,
		"ARBEITSPREIS_HT_NT": ARBEITSPREIS_HT_NT,
		"GRUNDPREIS":         GRUNDPREIS,
		"GESAMTPREIS":        GESAMTPREIS,
	}

	_AufAbschlagszielValueToName = map[AufAbschlagsziel]string{
		ARBEITSPREIS_HT:    "ARBEITSPREIS_HT",
		ARBEITSPREIS_NT:    "ARBEITSPREIS_NT",
		ARBEITSPREIS_HT_NT: "ARBEITSPREIS_HT_NT",
		GRUNDPREIS:         "GRUNDPREIS",
		GESAMTPREIS:        "GESAMTPREIS",
	}
)

func init() {
	var v AufAbschlagsziel
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_AufAbschlagszielNameToValue = map[string]AufAbschlagsziel{
			interface{}(ARBEITSPREIS_HT).(fmt.Stringer).String():    ARBEITSPREIS_HT,
			interface{}(ARBEITSPREIS_NT).(fmt.Stringer).String():    ARBEITSPREIS_NT,
			interface{}(ARBEITSPREIS_HT_NT).(fmt.Stringer).String(): ARBEITSPREIS_HT_NT,
			interface{}(GRUNDPREIS).(fmt.Stringer).String():         GRUNDPREIS,
			interface{}(GESAMTPREIS).(fmt.Stringer).String():        GESAMTPREIS,
		}
	}
}

// MarshalJSON is generated so AufAbschlagsziel satisfies json.Marshaler.
func (r AufAbschlagsziel) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _AufAbschlagszielValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid AufAbschlagsziel: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so AufAbschlagsziel satisfies json.Unmarshaler.
func (r *AufAbschlagsziel) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AufAbschlagsziel should be a string, got %s", data)
	}
	v, ok := _AufAbschlagszielNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid AufAbschlagsziel %q", s)
	}
	*r = v
	return nil
}
