// Code generated by "stringer --type BerichtStatus"; DO NOT EDIT.

package berichtstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERFOLGREICH-1]
	_ = x[FEHLER-2]
}

const _BerichtStatus_name = "ERFOLGREICHFEHLER"

var _BerichtStatus_index = [...]uint8{0, 11, 17}

func (i BerichtStatus) String() string {
	i -= 1
	if i < 0 || i >= BerichtStatus(len(_BerichtStatus_index)-1) {
		return "BerichtStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BerichtStatus_name[_BerichtStatus_index[i]:_BerichtStatus_index[i+1]]
}
