// Code generated by "stringer --type Mengeneinheit"; DO NOT EDIT.

package mengeneinheit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[W-1]
	_ = x[WH-2]
	_ = x[KW-3]
	_ = x[KWH-4]
	_ = x[KVARH-5]
	_ = x[MW-6]
	_ = x[MWH-7]
	_ = x[STUECK-8]
	_ = x[ANZAHL-9]
	_ = x[KUBIKMETER-10]
	_ = x[STUNDE-11]
	_ = x[TAG-12]
	_ = x[MONAT-13]
	_ = x[JAHR-14]
	_ = x[PROZENT-15]
}

const _Mengeneinheit_name = "WWHKWKWHKVARHMWMWHSTUECKANZAHLKUBIKMETERSTUNDETAGMONATJAHRPROZENT"

var _Mengeneinheit_index = [...]uint8{0, 1, 3, 5, 8, 13, 15, 18, 24, 30, 40, 46, 49, 54, 58, 65}

func (i Mengeneinheit) String() string {
	i -= 1
	if i < 0 || i >= Mengeneinheit(len(_Mengeneinheit_index)-1) {
		return "Mengeneinheit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Mengeneinheit_name[_Mengeneinheit_index[i]:_Mengeneinheit_index[i+1]]
}
