// Code generated by "stringer --type Mengeneinheit"; DO NOT EDIT.

package mengeneinheit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[W-0]
	_ = x[WH-1]
	_ = x[KW-2]
	_ = x[KWH-3]
	_ = x[KVARH-4]
	_ = x[MW-5]
	_ = x[MWH-6]
	_ = x[Stueck-7]
	_ = x[KUBIKMETER-8]
	_ = x[Stunde-9]
	_ = x[Tag-10]
	_ = x[Monat-11]
	_ = x[Jahr-12]
	_ = x[Prozent-13]
}

const _Mengeneinheit_name = "WWHKWKWHKVARHMWMWHStueckKUBIKMETERStundeTagMonatJahrProzent"

var _Mengeneinheit_index = [...]uint8{0, 1, 3, 5, 8, 13, 15, 18, 24, 34, 40, 43, 48, 52, 59}

func (i Mengeneinheit) String() string {
	if i < 0 || i >= Mengeneinheit(len(_Mengeneinheit_index)-1) {
		return "Mengeneinheit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mengeneinheit_name[_Mengeneinheit_index[i]:_Mengeneinheit_index[i+1]]
}
