// Code generated by jsonenums --type Ausschreibungstyp; DO NOT EDIT.

package ausschreibungstyp

import (
	"encoding/json"
	"fmt"
)

var (
	_AusschreibungstypNameToValue = map[string]Ausschreibungstyp{
		"OEFFENTLICHRECHTLICH": OEFFENTLICHRECHTLICH,
		"EUROPAWEIT":           EUROPAWEIT,
	}

	_AusschreibungstypValueToName = map[Ausschreibungstyp]string{
		OEFFENTLICHRECHTLICH: "OEFFENTLICHRECHTLICH",
		EUROPAWEIT:           "EUROPAWEIT",
	}
)

func init() {
	var v Ausschreibungstyp
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_AusschreibungstypNameToValue = map[string]Ausschreibungstyp{
			interface{}(OEFFENTLICHRECHTLICH).(fmt.Stringer).String(): OEFFENTLICHRECHTLICH,
			interface{}(EUROPAWEIT).(fmt.Stringer).String():           EUROPAWEIT,
		}
	}
}

// MarshalJSON is generated so Ausschreibungstyp satisfies json.Marshaler.
func (r Ausschreibungstyp) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _AusschreibungstypValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Ausschreibungstyp: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Ausschreibungstyp satisfies json.Unmarshaler.
func (r *Ausschreibungstyp) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Ausschreibungstyp should be a string, got %s", data)
	}
	v, ok := _AusschreibungstypNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Ausschreibungstyp %q", s)
	}
	*r = v
	return nil
}
