// Code generated by "stringer --type Oekozertifikat"; DO NOT EDIT.

package oekozertifikat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CMS_EE02-1]
	_ = x[EECS-2]
	_ = x[FRAUNHOFER-3]
	_ = x[BET-4]
	_ = x[KLIMA_INVEST-5]
	_ = x[LGA-6]
	_ = x[FREIBERG-7]
	_ = x[RECS-8]
	_ = x[REGS_EGL-9]
	_ = x[TUEV-10]
	_ = x[TUEV_HESSEN-11]
	_ = x[TUEV_NORD-12]
	_ = x[TUEV_RHEINLAND-13]
	_ = x[TUEV_SUED-14]
	_ = x[TUEV_SUED_EE01-15]
	_ = x[TUEV_SUED_EE02-16]
}

const _Oekozertifikat_name = "CMS_EE02EECSFRAUNHOFERBETKLIMA_INVESTLGAFREIBERGRECSREGS_EGLTUEVTUEV_HESSENTUEV_NORDTUEV_RHEINLANDTUEV_SUEDTUEV_SUED_EE01TUEV_SUED_EE02"

var _Oekozertifikat_index = [...]uint8{0, 8, 12, 22, 25, 37, 40, 48, 52, 60, 64, 75, 84, 98, 107, 121, 135}

func (i Oekozertifikat) String() string {
	i -= 1
	if i < 0 || i >= Oekozertifikat(len(_Oekozertifikat_index)-1) {
		return "Oekozertifikat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Oekozertifikat_name[_Oekozertifikat_index[i]:_Oekozertifikat_index[i+1]]
}
