package korrekturgrund

// Korrekturgrund gives hints on why something needs to be corrected
//go:generate stringer --type Korrekturgrund
//go:generate jsonenums --type Korrekturgrund
type Korrekturgrund int

const (
	// Z74_KEINZUGANG is "kein Zugang"
	Z74_KEINZUGANG Korrekturgrund = iota + 1

	// Z75_KOMMUNIKATIONSSTOERUNG is "Kommunikationsstörung"
	Z75_KOMMUNIKATIONSSTOERUNG

	// Z76_NETZAUSFALL is "Netzausfall"
	Z76_NETZAUSFALL

	//Z77_SPANNUNGSAUSFALL is "Spannungsausfall"
	Z77_SPANNUNGSAUSFALL

	// Z78_GERAETEWECHSEL is "Gerätewechsel"
	Z78_GERAETEWECHSEL

	//Z79_KALIBRIERUNG is "Kalibrierung"
	Z79_KALIBRIERUNG

	//Z80_GERAETARBEITETAUSSERHALBDERBETRIEBSBEDINGUNG is "Gerät arbeitet außerhalb der Betriebsbedingungen"
	Z80_GERAETARBEITETAUSSERHALBDERBETRIEBSBEDINGUNG

	// Z81_MESSEINRICHTUNGGESTOERTDEFEKT is "Messeinrichtung gestört/defekt"
	Z81_MESSEINRICHTUNGGESTOERTDEFEKT

	// Z82_UNSICHERHEITMESSUNG is "Unsicherheit Messung"
	Z82_UNSICHERHEITMESSUNG

	// Z98_BERUECKSICHTIGUNGSTOERMENGENZAEHLWERK is "Berücksichtigung Störmengenzählwerk"
	Z98_BERUECKSICHTIGUNGSTOERMENGENZAEHLWERK

	// Z99_MENGENUMWERTUNGUNVOLLSTAENDIG is "Mengenumwertung unvollständig"
	Z99_MENGENUMWERTUNGUNVOLLSTAENDIG

	//ZA0_UHRZEITGESTELLTSYNCHRONISATION is "Uhrzeit gestellt / Synchronisation"
	ZA0_UHRZEITGESTELLTSYNCHRONISATION

	// ZA1_MESSWERTUNPLAUSIBEL is "Messwert unplausibel"
	ZA1_MESSWERTUNPLAUSIBEL

	// ZA3_FALSCHERWANDLERFAKTOR is "Falscher Wandlerfaktor"
	ZA3_FALSCHERWANDLERFAKTOR

	// ZA4_FEHLERHAFTEABLESUNG is "Fehlerhafte Ablesung"
	ZA4_FEHLERHAFTEABLESUNG

	// ZA5_AENDERUNGDERBERECHNUNG is "Änderung der Berechnung"
	ZA5_AENDERUNGDERBERECHNUNG

	// ZA6_UMBAUDERMESSLOKATION is "Umbau der Messlokation"
	ZA6_UMBAUDERMESSLOKATION

	// ZA7_DATENBEARBEITUNGSFEHLER is "Datenbearbeitungsfehler"
	ZA7_DATENBEARBEITUNGSFEHLER

	//ZA8_BRENNWERTKORREKTUR is "Brennwertkorrektur"
	ZA8_BRENNWERTKORREKTUR

	// ZA9_ZZAHLKORREKTUR is "Z-Zahl-Korrektur"
	ZA9_ZZAHLKORREKTUR

	// ZB0_STOERUNGDEFEKTMESSEINRICHTUNG is "Störung / Defekt Messeinrichtung"
	ZB0_STOERUNGDEFEKTMESSEINRICHTUNG

	// ZB9_AENDERUNGTARIFSCHALTZEITEN is "Änderung Tarifschaltzeiten"
	ZB9_AENDERUNGTARIFSCHALTZEITEN

	// ZC2_TARIFSCHALTGERAETDEFEKT is "Tarifschaltgerät defekt"
	ZC2_TARIFSCHALTGERAETDEFEKT

	// ZC4_IMPULSWERTIGKEITNICHTAUSREICHEND is "Impulswertigkeit nicht ausreichend"
	ZC4_IMPULSWERTIGKEITNICHTAUSREICHEND

	//ZJ8_ENERGIEMENGEINUNGEMESSENEMZEITINTERVALL is "Energiemenge in ungemessenem Zeitintervall"
	ZJ8_ENERGIEMENGEINUNGEMESSENEMZEITINTERVALL

	// ZJ9_ENERGIEAUSDEMUNGEPAIRTENZEITINTERVALL is "Energie aus dem ungepairten Zeitintervall"
	ZJ9_ENERGIEAUSDEMUNGEPAIRTENZEITINTERVALL

	// ZR1_WARTUNGSARBEITENANGEEICHTEMMESSGERAET is "Wartungsarbeiten an geeichtem Messgerät"
	ZR1_WARTUNGSARBEITENANGEEICHTEMMESSGERAET

	// ZR2_GESTOERTEWERTE is "Gestörte Werte"
	ZR2_GESTOERTEWERTE

	// ZR3_WARTUNGSARBEITENANEICHRECHTSKONFORMENMESSGERAETEN is "Wartungsarbeiten an eichrechtskonformen Messgeräten"
	ZR3_WARTUNGSARBEITENANEICHRECHTSKONFORMENMESSGERAETEN

	// ZR4_KONSISTENZUNDSYNCHRONPRUEFUNG is "Konsistenz- und Synchronprüfung"
	ZR4_KONSISTENZUNDSYNCHRONPRUEFUNG
)
