// Code generated by jsonenums --type Leistungsbezeichung; DO NOT EDIT.

package leistungsbezeichung

import (
	"encoding/json"
	"fmt"
)

var (
	_LeistungsbezeichungNameToValue = map[string]Leistungsbezeichung{
		"POG_VERBRAUCH_IMS_UEBER_100K":    POG_VERBRAUCH_IMS_UEBER_100K,
		"POG_VERBRAUCH_IMS_50K_BIS_100K":  POG_VERBRAUCH_IMS_50K_BIS_100K,
		"POG_VERBRAUCH_IMS_20K_BIS_50K":   POG_VERBRAUCH_IMS_20K_BIS_50K,
		"POG_VERBRAUCH_IMS_10K_BIS_20K":   POG_VERBRAUCH_IMS_10K_BIS_20K,
		"POG_VERBRAUCH_IMS_UNTERBRECHBAR": POG_VERBRAUCH_IMS_UNTERBRECHBAR,
		"POG_VERBRAUCH_IMS_6K_BIS_10K":    POG_VERBRAUCH_IMS_6K_BIS_10K,
		"POG_ERZEUGUNG_IMS_7_BIS_15":      POG_ERZEUGUNG_IMS_7_BIS_15,
		"POG_ERZEUGUNG_IMS_15_BIS_30":     POG_ERZEUGUNG_IMS_15_BIS_30,
		"POG_ERZEUGUNG_IMS_30_BIS_100":    POG_ERZEUGUNG_IMS_30_BIS_100,
		"POG_ERZEUGUNG_IMS_UEBER_100":     POG_ERZEUGUNG_IMS_UEBER_100,
		"POG_MME":                         POG_MME,
		"POG_VERBRAUCH_IMS_4K_BIS_6K":     POG_VERBRAUCH_IMS_4K_BIS_6K,
		"POG_VERBRAUCH_IMS_3K_BIS_4K":     POG_VERBRAUCH_IMS_3K_BIS_4K,
		"POG_VERBRAUCH_IMS_2K_BIS_3K":     POG_VERBRAUCH_IMS_2K_BIS_3K,
		"POG_VERBRAUCH_IMS_0_BIS_2K":      POG_VERBRAUCH_IMS_0_BIS_2K,
		"POG_ERZEUGUNG_IMS_OPTIONAL":      POG_ERZEUGUNG_IMS_OPTIONAL,
		"ZUSATZLEISTUNG":                  ZUSATZLEISTUNG,
	}

	_LeistungsbezeichungValueToName = map[Leistungsbezeichung]string{
		POG_VERBRAUCH_IMS_UEBER_100K:    "POG_VERBRAUCH_IMS_UEBER_100K",
		POG_VERBRAUCH_IMS_50K_BIS_100K:  "POG_VERBRAUCH_IMS_50K_BIS_100K",
		POG_VERBRAUCH_IMS_20K_BIS_50K:   "POG_VERBRAUCH_IMS_20K_BIS_50K",
		POG_VERBRAUCH_IMS_10K_BIS_20K:   "POG_VERBRAUCH_IMS_10K_BIS_20K",
		POG_VERBRAUCH_IMS_UNTERBRECHBAR: "POG_VERBRAUCH_IMS_UNTERBRECHBAR",
		POG_VERBRAUCH_IMS_6K_BIS_10K:    "POG_VERBRAUCH_IMS_6K_BIS_10K",
		POG_ERZEUGUNG_IMS_7_BIS_15:      "POG_ERZEUGUNG_IMS_7_BIS_15",
		POG_ERZEUGUNG_IMS_15_BIS_30:     "POG_ERZEUGUNG_IMS_15_BIS_30",
		POG_ERZEUGUNG_IMS_30_BIS_100:    "POG_ERZEUGUNG_IMS_30_BIS_100",
		POG_ERZEUGUNG_IMS_UEBER_100:     "POG_ERZEUGUNG_IMS_UEBER_100",
		POG_MME:                         "POG_MME",
		POG_VERBRAUCH_IMS_4K_BIS_6K:     "POG_VERBRAUCH_IMS_4K_BIS_6K",
		POG_VERBRAUCH_IMS_3K_BIS_4K:     "POG_VERBRAUCH_IMS_3K_BIS_4K",
		POG_VERBRAUCH_IMS_2K_BIS_3K:     "POG_VERBRAUCH_IMS_2K_BIS_3K",
		POG_VERBRAUCH_IMS_0_BIS_2K:      "POG_VERBRAUCH_IMS_0_BIS_2K",
		POG_ERZEUGUNG_IMS_OPTIONAL:      "POG_ERZEUGUNG_IMS_OPTIONAL",
		ZUSATZLEISTUNG:                  "ZUSATZLEISTUNG",
	}
)

func init() {
	var v Leistungsbezeichung
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_LeistungsbezeichungNameToValue = map[string]Leistungsbezeichung{
			interface{}(POG_VERBRAUCH_IMS_UEBER_100K).(fmt.Stringer).String():    POG_VERBRAUCH_IMS_UEBER_100K,
			interface{}(POG_VERBRAUCH_IMS_50K_BIS_100K).(fmt.Stringer).String():  POG_VERBRAUCH_IMS_50K_BIS_100K,
			interface{}(POG_VERBRAUCH_IMS_20K_BIS_50K).(fmt.Stringer).String():   POG_VERBRAUCH_IMS_20K_BIS_50K,
			interface{}(POG_VERBRAUCH_IMS_10K_BIS_20K).(fmt.Stringer).String():   POG_VERBRAUCH_IMS_10K_BIS_20K,
			interface{}(POG_VERBRAUCH_IMS_UNTERBRECHBAR).(fmt.Stringer).String(): POG_VERBRAUCH_IMS_UNTERBRECHBAR,
			interface{}(POG_VERBRAUCH_IMS_6K_BIS_10K).(fmt.Stringer).String():    POG_VERBRAUCH_IMS_6K_BIS_10K,
			interface{}(POG_ERZEUGUNG_IMS_7_BIS_15).(fmt.Stringer).String():      POG_ERZEUGUNG_IMS_7_BIS_15,
			interface{}(POG_ERZEUGUNG_IMS_15_BIS_30).(fmt.Stringer).String():     POG_ERZEUGUNG_IMS_15_BIS_30,
			interface{}(POG_ERZEUGUNG_IMS_30_BIS_100).(fmt.Stringer).String():    POG_ERZEUGUNG_IMS_30_BIS_100,
			interface{}(POG_ERZEUGUNG_IMS_UEBER_100).(fmt.Stringer).String():     POG_ERZEUGUNG_IMS_UEBER_100,
			interface{}(POG_MME).(fmt.Stringer).String():                         POG_MME,
			interface{}(POG_VERBRAUCH_IMS_4K_BIS_6K).(fmt.Stringer).String():     POG_VERBRAUCH_IMS_4K_BIS_6K,
			interface{}(POG_VERBRAUCH_IMS_3K_BIS_4K).(fmt.Stringer).String():     POG_VERBRAUCH_IMS_3K_BIS_4K,
			interface{}(POG_VERBRAUCH_IMS_2K_BIS_3K).(fmt.Stringer).String():     POG_VERBRAUCH_IMS_2K_BIS_3K,
			interface{}(POG_VERBRAUCH_IMS_0_BIS_2K).(fmt.Stringer).String():      POG_VERBRAUCH_IMS_0_BIS_2K,
			interface{}(POG_ERZEUGUNG_IMS_OPTIONAL).(fmt.Stringer).String():      POG_ERZEUGUNG_IMS_OPTIONAL,
			interface{}(ZUSATZLEISTUNG).(fmt.Stringer).String():                  ZUSATZLEISTUNG,
		}
	}
}

// MarshalJSON is generated so Leistungsbezeichung satisfies json.Marshaler.
func (r Leistungsbezeichung) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _LeistungsbezeichungValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Leistungsbezeichung: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Leistungsbezeichung satisfies json.Unmarshaler.
func (r *Leistungsbezeichung) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Leistungsbezeichung should be a string, got %s", data)
	}
	v, ok := _LeistungsbezeichungNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Leistungsbezeichung %q", s)
	}
	*r = v
	return nil
}
