package leistungsbezeichung

//go:generate stringer --type Leistungsbezeichung
//go:generate jsonenums --type Leistungsbezeichung
type Leistungsbezeichung int

const (
	POG_VERBRAUCH_IMS_UEBER_100K Leistungsbezeichung = iota + 1
	POG_VERBRAUCH_IMS_50K_BIS_100K
	POG_VERBRAUCH_IMS_20K_BIS_50K
	POG_VERBRAUCH_IMS_10K_BIS_20K
	POG_VERBRAUCH_IMS_UNTERBRECHBAR
	POG_VERBRAUCH_IMS_6K_BIS_10K
	POG_ERZEUGUNG_IMS_7_BIS_15
	POG_ERZEUGUNG_IMS_15_BIS_30
	POG_ERZEUGUNG_IMS_30_BIS_100
	POG_ERZEUGUNG_IMS_UEBER_100
	POG_MME
	POG_VERBRAUCH_IMS_4K_BIS_6K
	POG_VERBRAUCH_IMS_3K_BIS_4K
	POG_VERBRAUCH_IMS_2K_BIS_3K
	POG_VERBRAUCH_IMS_0_BIS_2K
	POG_ERZEUGUNG_IMS_OPTIONAL
	ZUSATZLEISTUNG
)
