// Code generated by "stringer --type WahlrechtPrognosegrundlage"; DO NOT EDIT.

package wahlrechtprognosegrundlage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DURCH_LF-1]
	_ = x[DURCH_LF_NICHT_GEGEBEN-2]
	_ = x[NICHT_WEGEN_GROSSEN_VERBRAUCHS-3]
	_ = x[NICHT_WEGEN_EIGENVERBRAUCH-4]
	_ = x[NICHT_WEGEN_TAGES_VERBRAUCH-5]
	_ = x[NICHT_WEGEN_ENWG-6]
}

const _WahlrechtPrognosegrundlage_name = "DURCH_LFDURCH_LF_NICHT_GEGEBENNICHT_WEGEN_GROSSEN_VERBRAUCHSNICHT_WEGEN_EIGENVERBRAUCHNICHT_WEGEN_TAGES_VERBRAUCHNICHT_WEGEN_ENWG"

var _WahlrechtPrognosegrundlage_index = [...]uint8{0, 8, 30, 60, 86, 113, 129}

func (i WahlrechtPrognosegrundlage) String() string {
	i -= 1
	if i < 0 || i >= WahlrechtPrognosegrundlage(len(_WahlrechtPrognosegrundlage_index)-1) {
		return "WahlrechtPrognosegrundlage(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _WahlrechtPrognosegrundlage_name[_WahlrechtPrognosegrundlage_index[i]:_WahlrechtPrognosegrundlage_index[i+1]]
}
