// This maps the EDIFACT Values to the AbweichungsGrund and vice versa
// nolint:dupl // linter thinks the mapping is a duplicate to jsonenums
package abweichungsgrund

import (
	"fmt"
)

// EdiValue outputs the EDIFACT representation of the enum (AJT 4465)
func (r AbweichungsGrund) EdiValue() (string, error) {
	s, ok := _AbweichungsGrundValueToEdi[r]
	if ok {
		return s, nil
	}
	return "", fmt.Errorf("could not map %s", r)
}

// FromEdi maps the EDIFACT code to the enum
func (r *AbweichungsGrund) FromEdi(value string) error {
	if v, ok := _AbweichungsGrundEdiToValue[value]; ok {
		*r = v
		return nil
	}
	return fmt.Errorf("could not read %s", value)
}

var (
	_AbweichungsGrundEdiToValue = map[string]AbweichungsGrund{
		"5":   PREIS_RECHENREGEL_FALSCH,
		"9":   FALSCHER_ABRECHNUNGSZEITRAUM,
		"14":  UNBEKANNTE_MARKTLOKATION_MESSLOKATION,
		"28":  SONSTIGER_ABWEICHUNGSGRUND,
		"53":  DOPPELTE_RECHNUNG,
		"Z01": ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN,
		"Z02": ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE,
		"Z03": BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH,
		"Z04": VORAUSBEZAHLTER_BETRAG_FALSCH,
		"Z06": ARTIKEL_NICHT_VEREINBART,
		"Z07": NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN,
		"Z08": RECHNUNGSNUMMER_BEREITS_ERHALTEN,
		"Z10": NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH,
		"Z33": ZEITLICHE_MENGENANGABE_FEHLERHAFT,
		"Z35": FALSCHER_BILANZIERUNGSBEGINN,
		"Z36": FALSCHES_NETZNUTZUNGSENDE,
		"Z37": BILANZIERTE_MENGE_FEHLT,
		"Z38": BILANZIERTE_MENGE_FALSCH,
		"Z39": NETZNUTZUNGSABRECHNUNG_FEHLT,
		"Z40": REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT,
		"Z41": ALLOKATIONSLISTE_FEHLT,
		"Z42": MEHR_MINDERMENGE_FALSCH,
		"Z43": UNGUELTIGES_RECHNUNGSDATUM,
		"Z44": ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT,
		"Z45": RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS,
		"Z52": ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN,
		"Z53": RECHNUNGSABWICKLUNG_NICHT_VEREINBART,
		"Z63": COMDIS_WIRD_ABGELEHNT,
	}

	_AbweichungsGrundValueToEdi = map[AbweichungsGrund]string{
		PREIS_RECHENREGEL_FALSCH:                          "5",
		FALSCHER_ABRECHNUNGSZEITRAUM:                      "9",
		UNBEKANNTE_MARKTLOKATION_MESSLOKATION:             "14",
		SONSTIGER_ABWEICHUNGSGRUND:                        "28",
		DOPPELTE_RECHNUNG:                                 "53",
		ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN:         "Z01",
		ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE:             "Z02",
		BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH:               "Z03",
		VORAUSBEZAHLTER_BETRAG_FALSCH:                     "Z04",
		ARTIKEL_NICHT_VEREINBART:                          "Z06",
		NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN:        "Z07",
		RECHNUNGSNUMMER_BEREITS_ERHALTEN:                  "Z08",
		NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH:        "Z10",
		ZEITLICHE_MENGENANGABE_FEHLERHAFT:                 "Z33",
		FALSCHER_BILANZIERUNGSBEGINN:                      "Z35",
		FALSCHES_NETZNUTZUNGSENDE:                         "Z36",
		BILANZIERTE_MENGE_FEHLT:                           "Z37",
		BILANZIERTE_MENGE_FALSCH:                          "Z38",
		NETZNUTZUNGSABRECHNUNG_FEHLT:                      "Z39",
		REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT:    "Z40",
		ALLOKATIONSLISTE_FEHLT:                            "Z41",
		MEHR_MINDERMENGE_FALSCH:                           "Z42",
		UNGUELTIGES_RECHNUNGSDATUM:                        "Z43",
		ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT: "Z44",
		RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS: "Z45",
		ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN:                                         "Z52",
		RECHNUNGSABWICKLUNG_NICHT_VEREINBART:                                                       "Z53",
		COMDIS_WIRD_ABGELEHNT:                                                                      "Z63",
	}
)
