// Code generated by jsonenums --type ZaehlertypSpezifikation; DO NOT EDIT.

package zaehlertypspezifikation

import (
	"encoding/json"
	"fmt"
)

var (
	_ZaehlertypSpezifikationNameToValue = map[string]ZaehlertypSpezifikation{
		"EDL40":         EDL40,
		"EDL21":         EDL21,
		"SONSTIGER_EHZ": SONSTIGER_EHZ,
		"MME_STANDARD":  MME_STANDARD,
		"MME_MEDA":      MME_MEDA,
	}

	_ZaehlertypSpezifikationValueToName = map[ZaehlertypSpezifikation]string{
		EDL40:         "EDL40",
		EDL21:         "EDL21",
		SONSTIGER_EHZ: "SONSTIGER_EHZ",
		MME_STANDARD:  "MME_STANDARD",
		MME_MEDA:      "MME_MEDA",
	}
)

func init() {
	var v ZaehlertypSpezifikation
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_ZaehlertypSpezifikationNameToValue = map[string]ZaehlertypSpezifikation{
			interface{}(EDL40).(fmt.Stringer).String():         EDL40,
			interface{}(EDL21).(fmt.Stringer).String():         EDL21,
			interface{}(SONSTIGER_EHZ).(fmt.Stringer).String(): SONSTIGER_EHZ,
			interface{}(MME_STANDARD).(fmt.Stringer).String():  MME_STANDARD,
			interface{}(MME_MEDA).(fmt.Stringer).String():      MME_MEDA,
		}
	}
}

// MarshalJSON is generated so ZaehlertypSpezifikation satisfies json.Marshaler.
func (r ZaehlertypSpezifikation) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _ZaehlertypSpezifikationValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid ZaehlertypSpezifikation: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so ZaehlertypSpezifikation satisfies json.Unmarshaler.
func (r *ZaehlertypSpezifikation) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ZaehlertypSpezifikation should be a string, got %s", data)
	}
	v, ok := _ZaehlertypSpezifikationNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid ZaehlertypSpezifikation %q", s)
	}
	*r = v
	return nil
}
