// Code generated by "stringer --type ZaehlertypSpezifikation"; DO NOT EDIT.

package zaehlertypspezifikation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EDL40-1]
	_ = x[EDL21-2]
	_ = x[SONSTIGER_EHZ-3]
	_ = x[MME_STANDARD-4]
	_ = x[MME_MEDA-5]
}

const _ZaehlertypSpezifikation_name = "EDL40EDL21SONSTIGER_EHZMME_STANDARDMME_MEDA"

var _ZaehlertypSpezifikation_index = [...]uint8{0, 5, 10, 23, 35, 43}

func (i ZaehlertypSpezifikation) String() string {
	i -= 1
	if i < 0 || i >= ZaehlertypSpezifikation(len(_ZaehlertypSpezifikation_index)-1) {
		return "ZaehlertypSpezifikation(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ZaehlertypSpezifikation_name[_ZaehlertypSpezifikation_index[i]:_ZaehlertypSpezifikation_index[i+1]]
}
