// Code generated by jsonenums --type Preismodell; DO NOT EDIT.

package preismodell

import (
	"encoding/json"
	"fmt"
)

var (
	_PreismodellNameToValue = map[string]Preismodell{
		"TRANCHE": TRANCHE,
	}

	_PreismodellValueToName = map[Preismodell]string{
		TRANCHE: "TRANCHE",
	}
)

func init() {
	var v Preismodell
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_PreismodellNameToValue = map[string]Preismodell{
			interface{}(TRANCHE).(fmt.Stringer).String(): TRANCHE,
		}
	}
}

// MarshalJSON is generated so Preismodell satisfies json.Marshaler.
func (r Preismodell) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _PreismodellValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Preismodell: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Preismodell satisfies json.Unmarshaler.
func (r *Preismodell) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Preismodell should be a string, got %s", data)
	}
	v, ok := _PreismodellNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Preismodell %q", s)
	}
	*r = v
	return nil
}
