// Code generated by "stringer --type Preismodell"; DO NOT EDIT.

package preismodell

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TRANCHE-1]
}

const _Preismodell_name = "TRANCHE"

var _Preismodell_index = [...]uint8{0, 7}

func (i Preismodell) String() string {
	i -= 1
	if i < 0 || i >= Preismodell(len(_Preismodell_index)-1) {
		return "Preismodell(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Preismodell_name[_Preismodell_index[i]:_Preismodell_index[i+1]]
}
