// Code generated by "stringer --type Netznutzungsvertrag"; DO NOT EDIT.

package netznutzungsvertrag

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KUNDEN_NB-1]
	_ = x[LIEFERANTEN_NB-2]
}

const _Netznutzungsvertrag_name = "KUNDEN_NBLIEFERANTEN_NB"

var _Netznutzungsvertrag_index = [...]uint8{0, 9, 23}

func (i Netznutzungsvertrag) String() string {
	i -= 1
	if i < 0 || i >= Netznutzungsvertrag(len(_Netznutzungsvertrag_index)-1) {
		return "Netznutzungsvertrag(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Netznutzungsvertrag_name[_Netznutzungsvertrag_index[i]:_Netznutzungsvertrag_index[i+1]]
}
