// Code generated by jsonenums --type Netznutzungsvertrag; DO NOT EDIT.

package netznutzungsvertrag

import (
	"encoding/json"
	"fmt"
)

var (
	_NetznutzungsvertragNameToValue = map[string]Netznutzungsvertrag{
		"KUNDEN_NB":      KUNDEN_NB,
		"LIEFERANTEN_NB": LIEFERANTEN_NB,
	}

	_NetznutzungsvertragValueToName = map[Netznutzungsvertrag]string{
		KUNDEN_NB:      "KUNDEN_NB",
		LIEFERANTEN_NB: "LIEFERANTEN_NB",
	}
)

func init() {
	var v Netznutzungsvertrag
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_NetznutzungsvertragNameToValue = map[string]Netznutzungsvertrag{
			interface{}(KUNDEN_NB).(fmt.Stringer).String():      KUNDEN_NB,
			interface{}(LIEFERANTEN_NB).(fmt.Stringer).String(): LIEFERANTEN_NB,
		}
	}
}

// MarshalJSON is generated so Netznutzungsvertrag satisfies json.Marshaler.
func (r Netznutzungsvertrag) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _NetznutzungsvertragValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Netznutzungsvertrag: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Netznutzungsvertrag satisfies json.Unmarshaler.
func (r *Netznutzungsvertrag) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Netznutzungsvertrag should be a string, got %s", data)
	}
	v, ok := _NetznutzungsvertragNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Netznutzungsvertrag %q", s)
	}
	*r = v
	return nil
}
