// Code generated by "stringer --type FernsteuerbarkeitStatus"; DO NOT EDIT.

package fernsteuerbarkeitstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NICHT_FERNSTEUERBAR-1]
	_ = x[TECHNISCH_FERNSTEUERBAR-2]
	_ = x[LIEFERANT_FERNSTEUERBAR-3]
}

const _FernsteuerbarkeitStatus_name = "NICHT_FERNSTEUERBARTECHNISCH_FERNSTEUERBARLIEFERANT_FERNSTEUERBAR"

var _FernsteuerbarkeitStatus_index = [...]uint8{0, 19, 42, 65}

func (i FernsteuerbarkeitStatus) String() string {
	i -= 1
	if i < 0 || i >= FernsteuerbarkeitStatus(len(_FernsteuerbarkeitStatus_index)-1) {
		return "FernsteuerbarkeitStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FernsteuerbarkeitStatus_name[_FernsteuerbarkeitStatus_index[i]:_FernsteuerbarkeitStatus_index[i+1]]
}
