// Code generated by jsonenums --type Vertragsform; DO NOT EDIT.

package vertragsform

import (
	"encoding/json"
	"fmt"
)

var (
	_VertragsformNameToValue = map[string]Vertragsform{
		"ONLINE": ONLINE,
		"DIREKT": DIREKT,
		"FAX":    FAX,
	}

	_VertragsformValueToName = map[Vertragsform]string{
		ONLINE: "ONLINE",
		DIREKT: "DIREKT",
		FAX:    "FAX",
	}
)

func init() {
	var v Vertragsform
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_VertragsformNameToValue = map[string]Vertragsform{
			interface{}(ONLINE).(fmt.Stringer).String(): ONLINE,
			interface{}(DIREKT).(fmt.Stringer).String(): DIREKT,
			interface{}(FAX).(fmt.Stringer).String():    FAX,
		}
	}
}

// MarshalJSON is generated so Vertragsform satisfies json.Marshaler.
func (r Vertragsform) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _VertragsformValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Vertragsform: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Vertragsform satisfies json.Unmarshaler.
func (r *Vertragsform) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Vertragsform should be a string, got %s", data)
	}
	v, ok := _VertragsformNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Vertragsform %q", s)
	}
	*r = v
	return nil
}
