// Code generated by "stringer --type Vertragsform"; DO NOT EDIT.

package vertragsform

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ONLINE-1]
	_ = x[DIREKT-2]
	_ = x[FAX-3]
}

const _Vertragsform_name = "ONLINEDIREKTFAX"

var _Vertragsform_index = [...]uint8{0, 6, 12, 15}

func (i Vertragsform) String() string {
	i -= 1
	if i < 0 || i >= Vertragsform(len(_Vertragsform_index)-1) {
		return "Vertragsform(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Vertragsform_name[_Vertragsform_index[i]:_Vertragsform_index[i+1]]
}
