// Code generated by "stringer --type RechnungspositionsStatus"; DO NOT EDIT.

package rechnungspositionsstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ROH-1]
	_ = x[ROH_AUSGENOMMEN-2]
	_ = x[ABRECHENBAR-3]
	_ = x[ABRECHENBAR_AUSGENOMMEN-4]
	_ = x[ABGERECHNET-5]
}

const _RechnungspositionsStatus_name = "ROHROH_AUSGENOMMENABRECHENBARABRECHENBAR_AUSGENOMMENABGERECHNET"

var _RechnungspositionsStatus_index = [...]uint8{0, 3, 18, 29, 52, 63}

func (i RechnungspositionsStatus) String() string {
	i -= 1
	if i < 0 || i >= RechnungspositionsStatus(len(_RechnungspositionsStatus_index)-1) {
		return "RechnungspositionsStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RechnungspositionsStatus_name[_RechnungspositionsStatus_index[i]:_RechnungspositionsStatus_index[i+1]]
}
