// Code generated by "stringer --type Handelsunstimmigkeitsgrund"; DO NOT EDIT.

package handelsunstimmigkeitsgrund

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ANMELDUNG_BESTAETIGT-1]
	_ = x[ABRECHNUNGSBEGINN_GLEICH_BESTAETIGTEM_VERTRAGSBEGINN-2]
	_ = x[ABRECHNUNGSENDE_GLEICH_BESTAETIGTEM_VERTRAGSENDE-3]
	_ = x[NN_MSCONS_UEBERSENDET-4]
	_ = x[RICHTIGE_MESSWERTE_ENERGIEMENGEN_UEBERSENDET-5]
	_ = x[SONSTIGES_SIEHE_BEGRUENDUNG-6]
}

const _Handelsunstimmigkeitsgrund_name = "ANMELDUNG_BESTAETIGTABRECHNUNGSBEGINN_GLEICH_BESTAETIGTEM_VERTRAGSBEGINNABRECHNUNGSENDE_GLEICH_BESTAETIGTEM_VERTRAGSENDENN_MSCONS_UEBERSENDETRICHTIGE_MESSWERTE_ENERGIEMENGEN_UEBERSENDETSONSTIGES_SIEHE_BEGRUENDUNG"

var _Handelsunstimmigkeitsgrund_index = [...]uint8{0, 20, 72, 120, 141, 185, 212}

func (i Handelsunstimmigkeitsgrund) String() string {
	i -= 1
	if i < 0 || i >= Handelsunstimmigkeitsgrund(len(_Handelsunstimmigkeitsgrund_index)-1) {
		return "Handelsunstimmigkeitsgrund(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Handelsunstimmigkeitsgrund_name[_Handelsunstimmigkeitsgrund_index[i]:_Handelsunstimmigkeitsgrund_index[i+1]]
}
