package handelsunstimmigkeitsgrund

// Handelsunstimmigkeitsgrund are the possible types of reasons for the correctness of "Rechnung" or "Lieferschein"
// (COMDIS SG3 AJT 4465)
//
//go:generate stringer --type Handelsunstimmigkeitsgrund
//go:generate jsonenums --type Handelsunstimmigkeitsgrund
type Handelsunstimmigkeitsgrund int

const (
	// ANMELDUNG_BESTAETIGT represents COMDIS SG3 AJT 4465 code "Z58"
	ANMELDUNG_BESTAETIGT Handelsunstimmigkeitsgrund = iota + 1

	// ABRECHNUNGSBEGINN_GLEICH_BESTAETIGTEM_VERTRAGSBEGINN represents COMDIS SG3 AJT 4465 code "Z59"
	ABRECHNUNGSBEGINN_GLEICH_BESTAETIGTEM_VERTRAGSBEGINN

	// ABRECHNUNGSENDE_GLEICH_BESTAETIGTEM_VERTRAGSENDE represents COMDIS SG3 AJT 4465 code "Z60"
	ABRECHNUNGSENDE_GLEICH_BESTAETIGTEM_VERTRAGSENDE

	// NN_MSCONS_UEBERSENDET represents COMDIS SG3 AJT 4465 code "Z61"
	NN_MSCONS_UEBERSENDET

	// RICHTIGE_MESSWERTE_ENERGIEMENGEN_UEBERSENDET represents COMDIS SG3 AJT 4465 code "Z62"
	RICHTIGE_MESSWERTE_ENERGIEMENGEN_UEBERSENDET

	// SONSTIGES_SIEHE_BEGRUENDUNG represents COMDIS SG3 AJT 4465 code "28"
	SONSTIGES_SIEHE_BEGRUENDUNG

	// GUELTIGER_SPERRAUFTRAG_VORHANDEN represents a valid lock order exists
	GUELTIGER_SPERRAUFTRAG_VORHANDEN

	// GUELTIGES_PREISBLATT_BLINDARBEIT_VERSENDET represents valid reactive power price sheet sent
	GUELTIGES_PREISBLATT_BLINDARBEIT_VERSENDET

	// GUELTIGES_PREISBLATT_FRISTGERECHT_VERSENDET represents valid price sheet sent on time
	GUELTIGES_PREISBLATT_FRISTGERECHT_VERSENDET

	// GUELTIGES_PREISBLATT_VERSENDET represents valid price sheet sent
	GUELTIGES_PREISBLATT_VERSENDET

	// GUELTIGE_RECHNUNG_VORHANDEN represents valid invoice exists
	GUELTIGE_RECHNUNG_VORHANDEN

	// KORREKTER_PREIS_IN_RECHNUNG_ABGERECHNET represents correct price billed in invoice
	KORREKTER_PREIS_IN_RECHNUNG_ABGERECHNET

	// KORREKTER_PREIS_ZU_GUELTIGEM_PREISBLATT_IN_RECHNUNG represents correct price per valid price sheet in invoice
	KORREKTER_PREIS_ZU_GUELTIGEM_PREISBLATT_IN_RECHNUNG

	// KORREKTE_ARTIKEL_ID_FUER_ABRECHNUNG_STORNIERTER_SPERRAUFTRAG_ANGEGEBEN represents correct article ID for cancelled lock order billing
	KORREKTE_ARTIKEL_ID_FUER_ABRECHNUNG_STORNIERTER_SPERRAUFTRAG_ANGEGEBEN

	// KORREKTE_ARTIKEL_ID_IN_RECHNUNG represents correct article ID in invoice
	KORREKTE_ARTIKEL_ID_IN_RECHNUNG
)
