// Code generated by "stringer --type Unternehmensart"; DO NOT EDIT.

package unternehmensart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LIEFERANT-1]
	_ = x[NETZBETREIBER-2]
	_ = x[MESSSTELLENBETREIBER-3]
	_ = x[UEBERTRAGUNGSNETZBETREIBER-4]
	_ = x[BILANZKOORDINATOR-5]
	_ = x[BILANZKREISVERANTWORTLICHER-6]
	_ = x[ENERGIESERVICEANBIETER-7]
}

const _Unternehmensart_name = "LIEFERANTNETZBETREIBERMESSSTELLENBETREIBERUEBERTRAGUNGSNETZBETREIBERBILANZKOORDINATORBILANZKREISVERANTWORTLICHERENERGIESERVICEANBIETER"

var _Unternehmensart_index = [...]uint8{0, 9, 22, 42, 68, 85, 112, 134}

func (i Unternehmensart) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Unternehmensart_index)-1 {
		return "Unternehmensart(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Unternehmensart_name[_Unternehmensart_index[idx]:_Unternehmensart_index[idx+1]]
}
