// Code generated by jsonenums --type Unternehmensart; DO NOT EDIT.

package unternehmensart

import (
	"encoding/json"
	"fmt"
)

var (
	_UnternehmensartNameToValue = map[string]Unternehmensart{
		"LIEFERANT":                   LIEFERANT,
		"NETZBETREIBER":               NETZBETREIBER,
		"MESSSTELLENBETREIBER":        MESSSTELLENBETREIBER,
		"UEBERTRAGUNGSNETZBETREIBER":  UEBERTRAGUNGSNETZBETREIBER,
		"BILANZKOORDINATOR":           BILANZKOORDINATOR,
		"BILANZKREISVERANTWORTLICHER": BILANZKREISVERANTWORTLICHER,
		"ENERGIESERVICEANBIETER":      ENERGIESERVICEANBIETER,
	}

	_UnternehmensartValueToName = map[Unternehmensart]string{
		LIEFERANT:                   "LIEFERANT",
		NETZBETREIBER:               "NETZBETREIBER",
		MESSSTELLENBETREIBER:        "MESSSTELLENBETREIBER",
		UEBERTRAGUNGSNETZBETREIBER:  "UEBERTRAGUNGSNETZBETREIBER",
		BILANZKOORDINATOR:           "BILANZKOORDINATOR",
		BILANZKREISVERANTWORTLICHER: "BILANZKREISVERANTWORTLICHER",
		ENERGIESERVICEANBIETER:      "ENERGIESERVICEANBIETER",
	}
)

func init() {
	var v Unternehmensart
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_UnternehmensartNameToValue = map[string]Unternehmensart{
			interface{}(LIEFERANT).(fmt.Stringer).String():                   LIEFERANT,
			interface{}(NETZBETREIBER).(fmt.Stringer).String():               NETZBETREIBER,
			interface{}(MESSSTELLENBETREIBER).(fmt.Stringer).String():        MESSSTELLENBETREIBER,
			interface{}(UEBERTRAGUNGSNETZBETREIBER).(fmt.Stringer).String():  UEBERTRAGUNGSNETZBETREIBER,
			interface{}(BILANZKOORDINATOR).(fmt.Stringer).String():           BILANZKOORDINATOR,
			interface{}(BILANZKREISVERANTWORTLICHER).(fmt.Stringer).String(): BILANZKREISVERANTWORTLICHER,
			interface{}(ENERGIESERVICEANBIETER).(fmt.Stringer).String():      ENERGIESERVICEANBIETER,
		}
	}
}

// MarshalJSON is generated so Unternehmensart satisfies json.Marshaler.
func (r Unternehmensart) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _UnternehmensartValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Unternehmensart: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Unternehmensart satisfies json.Unmarshaler.
func (r *Unternehmensart) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Unternehmensart should be a string, got %s", data)
	}
	v, ok := _UnternehmensartNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Unternehmensart %q", s)
	}
	*r = v
	return nil
}
