// Code generated by "stringer --type Kontaktart"; DO NOT EDIT.

package kontaktart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Anschreiben-1]
	_ = x[Telefonat-2]
	_ = x[Fax-3]
	_ = x[Email-4]
	_ = x[SMS-5]
}

const _Kontaktart_name = "AnschreibenTelefonatFaxEmailSMS"

var _Kontaktart_index = [...]uint8{0, 11, 20, 23, 28, 31}

func (i Kontaktart) String() string {
	i -= 1
	if i < 0 || i >= Kontaktart(len(_Kontaktart_index)-1) {
		return "Kontaktart(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kontaktart_name[_Kontaktart_index[i]:_Kontaktart_index[i+1]]
}
