// Code generated by "stringer --type Sperrstatus"; DO NOT EDIT.

package sperrstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ENTSPERRT-1]
	_ = x[GESPERRT-2]
}

const _Sperrstatus_name = "ENTSPERRTGESPERRT"

var _Sperrstatus_index = [...]uint8{0, 9, 17}

func (i Sperrstatus) String() string {
	i -= 1
	if i < 0 || i >= Sperrstatus(len(_Sperrstatus_index)-1) {
		return "Sperrstatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Sperrstatus_name[_Sperrstatus_index[i]:_Sperrstatus_index[i+1]]
}
