// Code generated by "stringer --type Waehrungseinheit"; DO NOT EDIT.

package waehrungseinheit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EUR-1]
	_ = x[CT-2]
}

const _Waehrungseinheit_name = "EURCT"

var _Waehrungseinheit_index = [...]uint8{0, 3, 5}

func (i Waehrungseinheit) String() string {
	i -= 1
	if i < 0 || i >= Waehrungseinheit(len(_Waehrungseinheit_index)-1) {
		return "Waehrungseinheit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Waehrungseinheit_name[_Waehrungseinheit_index[i]:_Waehrungseinheit_index[i+1]]
}
