// Code generated by "stringer --type Prioritaet"; DO NOT EDIT.

package prioritaet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SEHR_NIEDRIG-1]
	_ = x[NIEDRIG-2]
	_ = x[NORMAL-3]
	_ = x[HOCH-4]
	_ = x[SEHR_HOCH-5]
}

const _Prioritaet_name = "SEHR_NIEDRIGNIEDRIGNORMALHOCHSEHR_HOCH"

var _Prioritaet_index = [...]uint8{0, 12, 19, 25, 29, 38}

func (i Prioritaet) String() string {
	i -= 1
	if i < 0 || i >= Prioritaet(len(_Prioritaet_index)-1) {
		return "Prioritaet(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Prioritaet_name[_Prioritaet_index[i]:_Prioritaet_index[i+1]]
}
