// Code generated by jsonenums --type Prioritaet; DO NOT EDIT.

package prioritaet

import (
	"encoding/json"
	"fmt"
)

var (
	_PrioritaetNameToValue = map[string]Prioritaet{
		"SEHR_NIEDRIG": SEHR_NIEDRIG,
		"NIEDRIG":      NIEDRIG,
		"NORMAL":       NORMAL,
		"HOCH":         HOCH,
		"SEHR_HOCH":    SEHR_HOCH,
	}

	_PrioritaetValueToName = map[Prioritaet]string{
		SEHR_NIEDRIG: "SEHR_NIEDRIG",
		NIEDRIG:      "NIEDRIG",
		NORMAL:       "NORMAL",
		HOCH:         "HOCH",
		SEHR_HOCH:    "SEHR_HOCH",
	}
)

func init() {
	var v Prioritaet
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_PrioritaetNameToValue = map[string]Prioritaet{
			interface{}(SEHR_NIEDRIG).(fmt.Stringer).String(): SEHR_NIEDRIG,
			interface{}(NIEDRIG).(fmt.Stringer).String():      NIEDRIG,
			interface{}(NORMAL).(fmt.Stringer).String():       NORMAL,
			interface{}(HOCH).(fmt.Stringer).String():         HOCH,
			interface{}(SEHR_HOCH).(fmt.Stringer).String():    SEHR_HOCH,
		}
	}
}

// MarshalJSON is generated so Prioritaet satisfies json.Marshaler.
func (r Prioritaet) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _PrioritaetValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Prioritaet: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Prioritaet satisfies json.Unmarshaler.
func (r *Prioritaet) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Prioritaet should be a string, got %s", data)
	}
	v, ok := _PrioritaetNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Prioritaet %q", s)
	}
	*r = v
	return nil
}
