// Code generated by "stringer --type Netznutzungsabrechnungsgrundlage"; DO NOT EDIT.

package netznutzungsabrechnungsgrundlage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LIEFERSCHEIN-1]
	_ = x[ABWEICHENDE_GRUNDLAGE-2]
}

const _Netznutzungsabrechnungsgrundlage_name = "LIEFERSCHEINABWEICHENDE_GRUNDLAGE"

var _Netznutzungsabrechnungsgrundlage_index = [...]uint8{0, 12, 33}

func (i Netznutzungsabrechnungsgrundlage) String() string {
	i -= 1
	if i < 0 || i >= Netznutzungsabrechnungsgrundlage(len(_Netznutzungsabrechnungsgrundlage_index)-1) {
		return "Netznutzungsabrechnungsgrundlage(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Netznutzungsabrechnungsgrundlage_name[_Netznutzungsabrechnungsgrundlage_index[i]:_Netznutzungsabrechnungsgrundlage_index[i+1]]
}
