// Code generated by jsonenums --type Tarifregionskriterium; DO NOT EDIT.

package tarifregionskriterium

import (
	"encoding/json"
	"fmt"
)

var (
	_TarifregionskriteriumNameToValue = map[string]Tarifregionskriterium{
		"NETZ_NUMMER":           NETZ_NUMMER,
		"POSTLEITZAHL":          POSTLEITZAHL,
		"ORT":                   ORT,
		"GRUNDVERSORGER_NUMMER": GRUNDVERSORGER_NUMMER,
	}

	_TarifregionskriteriumValueToName = map[Tarifregionskriterium]string{
		NETZ_NUMMER:           "NETZ_NUMMER",
		POSTLEITZAHL:          "POSTLEITZAHL",
		ORT:                   "ORT",
		GRUNDVERSORGER_NUMMER: "GRUNDVERSORGER_NUMMER",
	}
)

func init() {
	var v Tarifregionskriterium
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_TarifregionskriteriumNameToValue = map[string]Tarifregionskriterium{
			interface{}(NETZ_NUMMER).(fmt.Stringer).String():           NETZ_NUMMER,
			interface{}(POSTLEITZAHL).(fmt.Stringer).String():          POSTLEITZAHL,
			interface{}(ORT).(fmt.Stringer).String():                   ORT,
			interface{}(GRUNDVERSORGER_NUMMER).(fmt.Stringer).String(): GRUNDVERSORGER_NUMMER,
		}
	}
}

// MarshalJSON is generated so Tarifregionskriterium satisfies json.Marshaler.
func (r Tarifregionskriterium) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _TarifregionskriteriumValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Tarifregionskriterium: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Tarifregionskriterium satisfies json.Unmarshaler.
func (r *Tarifregionskriterium) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Tarifregionskriterium should be a string, got %s", data)
	}
	v, ok := _TarifregionskriteriumNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Tarifregionskriterium %q", s)
	}
	*r = v
	return nil
}
