// Code generated by "stringer --type Bemessungsgroesse"; DO NOT EDIT.

package bemessungsgroesse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WIRKARBEIT_EL-1]
	_ = x[LEISTUNG_EL-2]
	_ = x[BLINDARBEIT_KAP-3]
	_ = x[BLINDARBEIT_IND-4]
	_ = x[BLINDLEISTUNG_KAP-5]
	_ = x[BLINDLEISTUNG_IND-6]
	_ = x[WIRKARBEIT_TH-7]
	_ = x[LEISTUNG_TH-8]
	_ = x[VOLUMEN-9]
	_ = x[VOLUMENSTROM-10]
	_ = x[BENUTZUNGSDAUER-11]
	_ = x[ANZAHL-12]
}

const _Bemessungsgroesse_name = "WIRKARBEIT_ELLEISTUNG_ELBLINDARBEIT_KAPBLINDARBEIT_INDBLINDLEISTUNG_KAPBLINDLEISTUNG_INDWIRKARBEIT_THLEISTUNG_THVOLUMENVOLUMENSTROMBENUTZUNGSDAUERANZAHL"

var _Bemessungsgroesse_index = [...]uint8{0, 13, 24, 39, 54, 71, 88, 101, 112, 119, 131, 146, 152}

func (i Bemessungsgroesse) String() string {
	i -= 1
	if i < 0 || i >= Bemessungsgroesse(len(_Bemessungsgroesse_index)-1) {
		return "Bemessungsgroesse(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Bemessungsgroesse_name[_Bemessungsgroesse_index[i]:_Bemessungsgroesse_index[i+1]]
}
