// Code generated by "stringer --type Schwachlastfaehigkeit"; DO NOT EDIT.

package schwachlastfaehigkeit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SCHWACHLASTFAEHIG-1]
	_ = x[NICHT_SCHWACHLASTFAEHIG-2]
}

const _Schwachlastfaehigkeit_name = "SCHWACHLASTFAEHIGNICHT_SCHWACHLASTFAEHIG"

var _Schwachlastfaehigkeit_index = [...]uint8{0, 17, 40}

func (i Schwachlastfaehigkeit) String() string {
	i -= 1
	if i < 0 || i >= Schwachlastfaehigkeit(len(_Schwachlastfaehigkeit_index)-1) {
		return "Schwachlastfaehigkeit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Schwachlastfaehigkeit_name[_Schwachlastfaehigkeit_index[i]:_Schwachlastfaehigkeit_index[i+1]]
}
