// Code generated by "stringer --type Zaehlerauspraegung"; DO NOT EDIT.

package zaehlerauspraegung

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EINRICHTUNGSZAEHLER-1]
	_ = x[ZWEIRICHTUNGSZAEHLER-2]
}

const _Zaehlerauspraegung_name = "EINRICHTUNGSZAEHLERZWEIRICHTUNGSZAEHLER"

var _Zaehlerauspraegung_index = [...]uint8{0, 19, 39}

func (i Zaehlerauspraegung) String() string {
	i -= 1
	if i < 0 || i >= Zaehlerauspraegung(len(_Zaehlerauspraegung_index)-1) {
		return "Zaehlerauspraegung(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Zaehlerauspraegung_name[_Zaehlerauspraegung_index[i]:_Zaehlerauspraegung_index[i+1]]
}
