// Code generated by "stringer --type GrundlageZurVerringerungDerUmlagenNachEnfg"; DO NOT EDIT.

package grundlagezurverringerungderumlagennachenfg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KUNDE_ERFUELLT_VORAUSSETZUNG-1]
	_ = x[KUNDE_ERFUELLT_VORAUSSETZUNG_NICHT-2]
	_ = x[KEINE_ANGABE-3]
}

const _GrundlageZurVerringerungDerUmlagenNachEnfg_name = "KUNDE_ERFUELLT_VORAUSSETZUNGKUNDE_ERFUELLT_VORAUSSETZUNG_NICHTKEINE_ANGABE"

var _GrundlageZurVerringerungDerUmlagenNachEnfg_index = [...]uint8{0, 28, 62, 74}

func (i GrundlageZurVerringerungDerUmlagenNachEnfg) String() string {
	i -= 1
	if i < 0 || i >= GrundlageZurVerringerungDerUmlagenNachEnfg(len(_GrundlageZurVerringerungDerUmlagenNachEnfg_index)-1) {
		return "GrundlageZurVerringerungDerUmlagenNachEnfg(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _GrundlageZurVerringerungDerUmlagenNachEnfg_name[_GrundlageZurVerringerungDerUmlagenNachEnfg_index[i]:_GrundlageZurVerringerungDerUmlagenNachEnfg_index[i+1]]
}
