// Code generated by "stringer --type FehlerTyp"; DO NOT EDIT.

package fehlertyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SYNTAX-1]
	_ = x[VERARBEITUNG-2]
}

const _FehlerTyp_name = "SYNTAXVERARBEITUNG"

var _FehlerTyp_index = [...]uint8{0, 6, 18}

func (i FehlerTyp) String() string {
	i -= 1
	if i < 0 || i >= FehlerTyp(len(_FehlerTyp_index)-1) {
		return "FehlerTyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FehlerTyp_name[_FehlerTyp_index[i]:_FehlerTyp_index[i+1]]
}
