// Code generated by jsonenums --type Sperrauftragsart; DO NOT EDIT.

package sperrauftragsart

import (
	"encoding/json"
	"fmt"
)

var (
	_SperrauftragsartNameToValue = map[string]Sperrauftragsart{
		"SPERREN":    SPERREN,
		"ENTSPERREN": ENTSPERREN,
	}

	_SperrauftragsartValueToName = map[Sperrauftragsart]string{
		SPERREN:    "SPERREN",
		ENTSPERREN: "ENTSPERREN",
	}
)

func init() {
	var v Sperrauftragsart
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_SperrauftragsartNameToValue = map[string]Sperrauftragsart{
			interface{}(SPERREN).(fmt.Stringer).String():    SPERREN,
			interface{}(ENTSPERREN).(fmt.Stringer).String(): ENTSPERREN,
		}
	}
}

// MarshalJSON is generated so Sperrauftragsart satisfies json.Marshaler.
func (r Sperrauftragsart) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _SperrauftragsartValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Sperrauftragsart: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Sperrauftragsart satisfies json.Unmarshaler.
func (r *Sperrauftragsart) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Sperrauftragsart should be a string, got %s", data)
	}
	v, ok := _SperrauftragsartNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Sperrauftragsart %q", s)
	}
	*r = v
	return nil
}
