// Code generated by "stringer --type Sperrauftragsart"; DO NOT EDIT.

package sperrauftragsart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SPERREN-1]
	_ = x[ENTSPERREN-2]
}

const _Sperrauftragsart_name = "SPERRENENTSPERREN"

var _Sperrauftragsart_index = [...]uint8{0, 7, 17}

func (i Sperrauftragsart) String() string {
	i -= 1
	if i < 0 || i >= Sperrauftragsart(len(_Sperrauftragsart_index)-1) {
		return "Sperrauftragsart(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Sperrauftragsart_name[_Sperrauftragsart_index[i]:_Sperrauftragsart_index[i+1]]
}
