// Code generated by jsonenums --type Rechnungslegung; DO NOT EDIT.

package rechnungslegung

import (
	"encoding/json"
	"fmt"
)

var (
	_RechnungslegungNameToValue = map[string]Rechnungslegung{
		"MONATSRECHN":             MONATSRECHN,
		"ABSCHL_MONATSRECHN":      ABSCHL_MONATSRECHN,
		"ABSCHL_JAHRESRECHN":      ABSCHL_JAHRESRECHN,
		"MONATSRECHN_JAHRESRECHN": MONATSRECHN_JAHRESRECHN,
		"VORKASSE":                VORKASSE,
	}

	_RechnungslegungValueToName = map[Rechnungslegung]string{
		MONATSRECHN:             "MONATSRECHN",
		ABSCHL_MONATSRECHN:      "ABSCHL_MONATSRECHN",
		ABSCHL_JAHRESRECHN:      "ABSCHL_JAHRESRECHN",
		MONATSRECHN_JAHRESRECHN: "MONATSRECHN_JAHRESRECHN",
		VORKASSE:                "VORKASSE",
	}
)

func init() {
	var v Rechnungslegung
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_RechnungslegungNameToValue = map[string]Rechnungslegung{
			interface{}(MONATSRECHN).(fmt.Stringer).String():             MONATSRECHN,
			interface{}(ABSCHL_MONATSRECHN).(fmt.Stringer).String():      ABSCHL_MONATSRECHN,
			interface{}(ABSCHL_JAHRESRECHN).(fmt.Stringer).String():      ABSCHL_JAHRESRECHN,
			interface{}(MONATSRECHN_JAHRESRECHN).(fmt.Stringer).String(): MONATSRECHN_JAHRESRECHN,
			interface{}(VORKASSE).(fmt.Stringer).String():                VORKASSE,
		}
	}
}

// MarshalJSON is generated so Rechnungslegung satisfies json.Marshaler.
func (r Rechnungslegung) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _RechnungslegungValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Rechnungslegung: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Rechnungslegung satisfies json.Unmarshaler.
func (r *Rechnungslegung) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Rechnungslegung should be a string, got %s", data)
	}
	v, ok := _RechnungslegungNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Rechnungslegung %q", s)
	}
	*r = v
	return nil
}
