// Code generated by "stringer --type Rechnungsstatus"; DO NOT EDIT.

package rechnungsstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNGEPRUEFT-1]
	_ = x[GEPRUEFT_OK-2]
	_ = x[GEPRUEFT_FEHLERHAFT-3]
	_ = x[GEBUCHT-4]
	_ = x[BEZAHLT-5]
}

const _Rechnungsstatus_name = "UNGEPRUEFTGEPRUEFT_OKGEPRUEFT_FEHLERHAFTGEBUCHTBEZAHLT"

var _Rechnungsstatus_index = [...]uint8{0, 10, 21, 40, 47, 54}

func (i Rechnungsstatus) String() string {
	i -= 1
	if i < 0 || i >= Rechnungsstatus(len(_Rechnungsstatus_index)-1) {
		return "Rechnungsstatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Rechnungsstatus_name[_Rechnungsstatus_index[i]:_Rechnungsstatus_index[i+1]]
}
