// Code generated by "stringer --type Verwendungszweck"; DO NOT EDIT.

package verwendungszweck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NETZNUTZUNGSABRECHNUNG-1]
	_ = x[BILANZKREISABRECHNUNG-2]
	_ = x[MEHRMINDERMENGENABRECHNUNG-3]
	_ = x[ENDKUNDENABRECHNUNG-4]
	_ = x[UEBERMITTLUNG_AN_DAS_HKNR-5]
	_ = x[ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS-6]
	_ = x[BLINDARBEITABRECHNUNG_BETRIEBSFUEHRUNG-7]
	_ = x[SELBSTVERBRAUCH-8]
	_ = x[ES_LIEGT_KEIN_VERWENDUNGSZWECK_VOR-9]
	_ = x[KEINE_DATENLIEFERUNG_AN_MARKTROLLE-10]
}

const _Verwendungszweck_name = "NETZNUTZUNGSABRECHNUNGBILANZKREISABRECHNUNGMEHRMINDERMENGENABRECHNUNGENDKUNDENABRECHNUNGUEBERMITTLUNG_AN_DAS_HKNRERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREISBLINDARBEITABRECHNUNG_BETRIEBSFUEHRUNGSELBSTVERBRAUCHES_LIEGT_KEIN_VERWENDUNGSZWECK_VORKEINE_DATENLIEFERUNG_AN_MARKTROLLE"

var _Verwendungszweck_index = [...]uint16{0, 22, 43, 69, 88, 113, 152, 190, 205, 239, 273}

func (i Verwendungszweck) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Verwendungszweck_index)-1 {
		return "Verwendungszweck(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Verwendungszweck_name[_Verwendungszweck_index[idx]:_Verwendungszweck_index[idx+1]]
}
