// Code generated by "stringer --type Kundengruppe"; DO NOT EDIT.

package kundengruppe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RLM-1]
	_ = x[SLP_S_G0-2]
	_ = x[SLP_S_G1-3]
	_ = x[SLP_S_G2-4]
	_ = x[SLP_S_G3-5]
	_ = x[SLP_S_G4-6]
	_ = x[SLP_S_G5-7]
	_ = x[SLP_S_G6-8]
	_ = x[SLP_S_G7-9]
	_ = x[SLP_S_L0-10]
	_ = x[SLP_S_L1-11]
	_ = x[SLP_S_L2-12]
	_ = x[SLP_S_H0-13]
	_ = x[SLP_S_SB-14]
	_ = x[SLP_S_HZ-15]
	_ = x[SLP_S_WP-16]
	_ = x[SLP_G_GKO-17]
	_ = x[SLP_G_GHA-18]
	_ = x[SLP_G_GMK-19]
	_ = x[SLP_G_GBD-20]
	_ = x[SLP_G_GGA-21]
	_ = x[SLP_G_GBH-22]
	_ = x[SLP_G_GBA-23]
	_ = x[SLP_G_GWA-24]
	_ = x[SLP_G_GGB-25]
	_ = x[SLP_G_GPD-26]
	_ = x[SLP_G_GMF-27]
	_ = x[SLP_G_HEF-28]
	_ = x[SLP_G_HMF-29]
	_ = x[SLP_G_HKO-30]
}

const _Kundengruppe_name = "RLMSLP_S_G0SLP_S_G1SLP_S_G2SLP_S_G3SLP_S_G4SLP_S_G5SLP_S_G6SLP_S_G7SLP_S_L0SLP_S_L1SLP_S_L2SLP_S_H0SLP_S_SBSLP_S_HZSLP_S_WPSLP_G_GKOSLP_G_GHASLP_G_GMKSLP_G_GBDSLP_G_GGASLP_G_GBHSLP_G_GBASLP_G_GWASLP_G_GGBSLP_G_GPDSLP_G_GMFSLP_G_HEFSLP_G_HMFSLP_G_HKO"

var _Kundengruppe_index = [...]uint8{0, 3, 11, 19, 27, 35, 43, 51, 59, 67, 75, 83, 91, 99, 107, 115, 123, 132, 141, 150, 159, 168, 177, 186, 195, 204, 213, 222, 231, 240, 249}

func (i Kundengruppe) String() string {
	i -= 1
	if i < 0 || i >= Kundengruppe(len(_Kundengruppe_index)-1) {
		return "Kundengruppe(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kundengruppe_name[_Kundengruppe_index[i]:_Kundengruppe_index[i+1]]
}
