// Code generated by jsonenums --type Profilklasse; DO NOT EDIT.

package profilklasse

import (
	"encoding/json"
	"fmt"
)

var (
	_ProfilklasseNameToValue = map[string]Profilklasse{
		"GEWERBE":                           GEWERBE,
		"GEWERBE_WERKTAG_9_BIS_18":          GEWERBE_WERKTAG_9_BIS_18,
		"GEWERBE_ABEND":                     GEWERBE_ABEND,
		"GEWERBE_DURCHLAUFEND":              GEWERBE_DURCHLAUFEND,
		"GEWERBE_LADEN_FRISEUR":             GEWERBE_LADEN_FRISEUR,
		"GEWERBE_BAECKEREI":                 GEWERBE_BAECKEREI,
		"GEWERBE_WOCHENENDE":                GEWERBE_WOCHENENDE,
		"LANDWIRTSCHAFT":                    LANDWIRTSCHAFT,
		"LANDWIRTSCHAFT_MIT_MILCH":          LANDWIRTSCHAFT_MIT_MILCH,
		"LANDWIRTSCHAFT_OHNE_MILCH":         LANDWIRTSCHAFT_OHNE_MILCH,
		"HAUSHALT":                          HAUSHALT,
		"BANDLAST":                          BANDLAST,
		"HEIZWAERMESPEICHER":                HEIZWAERMESPEICHER,
		"STRASSENBELEUCHTUNG":               STRASSENBELEUCHTUNG,
		"PHOTOVOLTAIK":                      PHOTOVOLTAIK,
		"BLOCKHEIZKRAFTWERK":                BLOCKHEIZKRAFTWERK,
		"SONSTIGE_ERZEUGENDE_MARKTLOKATION": SONSTIGE_ERZEUGENDE_MARKTLOKATION,
		"EMOB_OEFFENTLICH":                  EMOB_OEFFENTLICH,
		"EMOB_HAUSHALT":                     EMOB_HAUSHALT,
		"EMOB_GEWERBE":                      EMOB_GEWERBE,
	}

	_ProfilklasseValueToName = map[Profilklasse]string{
		GEWERBE:                           "GEWERBE",
		GEWERBE_WERKTAG_9_BIS_18:          "GEWERBE_WERKTAG_9_BIS_18",
		GEWERBE_ABEND:                     "GEWERBE_ABEND",
		GEWERBE_DURCHLAUFEND:              "GEWERBE_DURCHLAUFEND",
		GEWERBE_LADEN_FRISEUR:             "GEWERBE_LADEN_FRISEUR",
		GEWERBE_BAECKEREI:                 "GEWERBE_BAECKEREI",
		GEWERBE_WOCHENENDE:                "GEWERBE_WOCHENENDE",
		LANDWIRTSCHAFT:                    "LANDWIRTSCHAFT",
		LANDWIRTSCHAFT_MIT_MILCH:          "LANDWIRTSCHAFT_MIT_MILCH",
		LANDWIRTSCHAFT_OHNE_MILCH:         "LANDWIRTSCHAFT_OHNE_MILCH",
		HAUSHALT:                          "HAUSHALT",
		BANDLAST:                          "BANDLAST",
		HEIZWAERMESPEICHER:                "HEIZWAERMESPEICHER",
		STRASSENBELEUCHTUNG:               "STRASSENBELEUCHTUNG",
		PHOTOVOLTAIK:                      "PHOTOVOLTAIK",
		BLOCKHEIZKRAFTWERK:                "BLOCKHEIZKRAFTWERK",
		SONSTIGE_ERZEUGENDE_MARKTLOKATION: "SONSTIGE_ERZEUGENDE_MARKTLOKATION",
		EMOB_OEFFENTLICH:                  "EMOB_OEFFENTLICH",
		EMOB_HAUSHALT:                     "EMOB_HAUSHALT",
		EMOB_GEWERBE:                      "EMOB_GEWERBE",
	}
)

func init() {
	var v Profilklasse
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_ProfilklasseNameToValue = map[string]Profilklasse{
			interface{}(GEWERBE).(fmt.Stringer).String():                           GEWERBE,
			interface{}(GEWERBE_WERKTAG_9_BIS_18).(fmt.Stringer).String():          GEWERBE_WERKTAG_9_BIS_18,
			interface{}(GEWERBE_ABEND).(fmt.Stringer).String():                     GEWERBE_ABEND,
			interface{}(GEWERBE_DURCHLAUFEND).(fmt.Stringer).String():              GEWERBE_DURCHLAUFEND,
			interface{}(GEWERBE_LADEN_FRISEUR).(fmt.Stringer).String():             GEWERBE_LADEN_FRISEUR,
			interface{}(GEWERBE_BAECKEREI).(fmt.Stringer).String():                 GEWERBE_BAECKEREI,
			interface{}(GEWERBE_WOCHENENDE).(fmt.Stringer).String():                GEWERBE_WOCHENENDE,
			interface{}(LANDWIRTSCHAFT).(fmt.Stringer).String():                    LANDWIRTSCHAFT,
			interface{}(LANDWIRTSCHAFT_MIT_MILCH).(fmt.Stringer).String():          LANDWIRTSCHAFT_MIT_MILCH,
			interface{}(LANDWIRTSCHAFT_OHNE_MILCH).(fmt.Stringer).String():         LANDWIRTSCHAFT_OHNE_MILCH,
			interface{}(HAUSHALT).(fmt.Stringer).String():                          HAUSHALT,
			interface{}(BANDLAST).(fmt.Stringer).String():                          BANDLAST,
			interface{}(HEIZWAERMESPEICHER).(fmt.Stringer).String():                HEIZWAERMESPEICHER,
			interface{}(STRASSENBELEUCHTUNG).(fmt.Stringer).String():               STRASSENBELEUCHTUNG,
			interface{}(PHOTOVOLTAIK).(fmt.Stringer).String():                      PHOTOVOLTAIK,
			interface{}(BLOCKHEIZKRAFTWERK).(fmt.Stringer).String():                BLOCKHEIZKRAFTWERK,
			interface{}(SONSTIGE_ERZEUGENDE_MARKTLOKATION).(fmt.Stringer).String(): SONSTIGE_ERZEUGENDE_MARKTLOKATION,
			interface{}(EMOB_OEFFENTLICH).(fmt.Stringer).String():                  EMOB_OEFFENTLICH,
			interface{}(EMOB_HAUSHALT).(fmt.Stringer).String():                     EMOB_HAUSHALT,
			interface{}(EMOB_GEWERBE).(fmt.Stringer).String():                      EMOB_GEWERBE,
		}
	}
}

// MarshalJSON is generated so Profilklasse satisfies json.Marshaler.
func (r Profilklasse) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _ProfilklasseValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Profilklasse: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Profilklasse satisfies json.Unmarshaler.
func (r *Profilklasse) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Profilklasse should be a string, got %s", data)
	}
	v, ok := _ProfilklasseNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Profilklasse %q", s)
	}
	*r = v
	return nil
}
