package profilklasse

//go:generate stringer --type Profilklasse
//go:generate jsonenums --type Profilklasse
type Profilklasse int

const (
	GEWERBE Profilklasse = iota + 1
	GEWERBE_WERKTAG_9_BIS_18
	GEWERBE_ABEND
	GEWERBE_DURCHLAUFEND
	GEWERBE_LADEN_FRISEUR
	GEWERBE_BAECKEREI
	GEWERBE_WOCHENENDE
	LANDWIRTSCHAFT
	LANDWIRTSCHAFT_MIT_MILCH
	LANDWIRTSCHAFT_OHNE_MILCH
	HAUSHALT
	BANDLAST
	HEIZWAERMESPEICHER
	STRASSENBELEUCHTUNG
	PHOTOVOLTAIK
	BLOCKHEIZKRAFTWERK
	SONSTIGE_ERZEUGENDE_MARKTLOKATION
	EMOB_OEFFENTLICH
	EMOB_HAUSHALT
	EMOB_GEWERBE
	UNTERBRECHBARE_VERBRAUCHSEINRICHTUNG
	SONSTIGE_VERBRAUCHENDE_MARKTLOKATION
)
