// Code generated by "stringer --type Ersatzwertbildungsverfahren"; DO NOT EDIT.

package ersatzwertbildungsverfahren

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Z88_VERGLEICHSMESSUNGGEEICHT-1]
	_ = x[Z89_VERGLEICHSMESSUNGNICHTGEEICHT-2]
	_ = x[Z90_MESSWERTNACHBILDUNGAUSGEEICHTENWERTEN-3]
	_ = x[Z91_MESSWERTNACHBILDUNGAUSNICHTGEEICHTENWERTEN-4]
	_ = x[Z92_INTERPOLATION-5]
	_ = x[Z93_HALTEWERT-6]
	_ = x[Z94_BILANZIERUNGNETZABSCHNITT-7]
	_ = x[Z95_HISTORISCHEMESSWERTE-8]
	_ = x[ZQ8_AUFTEILUNG-9]
	_ = x[ZQ9_VERWENDUNGVONWERTENDESSTOERMENGENZAEHLWERKS-10]
	_ = x[ZR0_UMGANGSUNDKORREKTURMENGEN-11]
	_ = x[ZJ2_STATISCHEMETHODE-12]
}

const _Ersatzwertbildungsverfahren_name = "Z88_VERGLEICHSMESSUNGGEEICHTZ89_VERGLEICHSMESSUNGNICHTGEEICHTZ90_MESSWERTNACHBILDUNGAUSGEEICHTENWERTENZ91_MESSWERTNACHBILDUNGAUSNICHTGEEICHTENWERTENZ92_INTERPOLATIONZ93_HALTEWERTZ94_BILANZIERUNGNETZABSCHNITTZ95_HISTORISCHEMESSWERTEZQ8_AUFTEILUNGZQ9_VERWENDUNGVONWERTENDESSTOERMENGENZAEHLWERKSZR0_UMGANGSUNDKORREKTURMENGENZJ2_STATISCHEMETHODE"

var _Ersatzwertbildungsverfahren_index = [...]uint16{0, 28, 61, 102, 148, 165, 178, 207, 231, 245, 292, 321, 341}

func (i Ersatzwertbildungsverfahren) String() string {
	i -= 1
	if i < 0 || i >= Ersatzwertbildungsverfahren(len(_Ersatzwertbildungsverfahren_index)-1) {
		return "Ersatzwertbildungsverfahren(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Ersatzwertbildungsverfahren_name[_Ersatzwertbildungsverfahren_index[i]:_Ersatzwertbildungsverfahren_index[i+1]]
}
