// Code generated by "stringer --type ErmittlungLeistungsmaximum"; DO NOT EDIT.

package ermittlungleistungsmaximum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VERWENDUNG_HOCHLASTFENSTER-1]
	_ = x[KEINE_VERWENDUNG_HOCHLASTFENSTER-2]
}

const _ErmittlungLeistungsmaximum_name = "VERWENDUNG_HOCHLASTFENSTERKEINE_VERWENDUNG_HOCHLASTFENSTER"

var _ErmittlungLeistungsmaximum_index = [...]uint8{0, 26, 58}

func (i ErmittlungLeistungsmaximum) String() string {
	i -= 1
	if i < 0 || i >= ErmittlungLeistungsmaximum(len(_ErmittlungLeistungsmaximum_index)-1) {
		return "ErmittlungLeistungsmaximum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErmittlungLeistungsmaximum_name[_ErmittlungLeistungsmaximum_index[i]:_ErmittlungLeistungsmaximum_index[i+1]]
}
