// Code generated by "stringer --type KundengruppeKA"; DO NOT EDIT.

package kundengruppeKA

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[S_TARIF_25000-1]
	_ = x[S_TARIF_100000-2]
	_ = x[S_TARIF_500000-3]
	_ = x[S_TARIF_G_500000-4]
	_ = x[S_SONDERKUNDE-5]
	_ = x[G_KOWA_25000-6]
	_ = x[G_KOWA_100000-7]
	_ = x[G_KOWA_500000-8]
	_ = x[G_KOWA_G_500000-9]
	_ = x[G_TARIF_25000-10]
	_ = x[G_TARIF_100000-11]
	_ = x[G_TARIF_500000-12]
	_ = x[G_TARIF_G_500000-13]
	_ = x[G_SONDERKUNDE-14]
	_ = x[SONDER_KAS-15]
	_ = x[SONDER_SAS-16]
	_ = x[SONDER_TAS-17]
	_ = x[SONDER_TKS-18]
	_ = x[SONDER_TSS-19]
}

const _KundengruppeKA_name = "S_TARIF_25000S_TARIF_100000S_TARIF_500000S_TARIF_G_500000S_SONDERKUNDEG_KOWA_25000G_KOWA_100000G_KOWA_500000G_KOWA_G_500000G_TARIF_25000G_TARIF_100000G_TARIF_500000G_TARIF_G_500000G_SONDERKUNDESONDER_KASSONDER_SASSONDER_TASSONDER_TKSSONDER_TSS"

var _KundengruppeKA_index = [...]uint8{0, 13, 27, 41, 57, 70, 82, 95, 108, 123, 136, 150, 164, 180, 193, 203, 213, 223, 233, 243}

func (i KundengruppeKA) String() string {
	i -= 1
	if i < 0 || i >= KundengruppeKA(len(_KundengruppeKA_index)-1) {
		return "KundengruppeKA(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _KundengruppeKA_name[_KundengruppeKA_index[i]:_KundengruppeKA_index[i+1]]
}
