// Code generated by jsonenums --type Sperrauftragsverhinderungsgrund; DO NOT EDIT.

package sperrauftragsverhinderungsgrund

import (
	"encoding/json"
	"fmt"
)

var (
	_SperrauftragsverhinderungsgrundNameToValue = map[string]Sperrauftragsverhinderungsgrund{
		"RECHTLICHER_GRUND_FEHLT":                 RECHTLICHER_GRUND_FEHLT,
		"AKTIVE_ZUTRITTSVERWEIGERUNG":             AKTIVE_ZUTRITTSVERWEIGERUNG,
		"PASSIVE_ZUTRITTSVERWEIGERUNG":            PASSIVE_ZUTRITTSVERWEIGERUNG,
		"ANDERER_VERHINDERUNGSGRUND":              ANDERER_VERHINDERUNGSGRUND,
		"TATSAECHLICHER_VERHINDERUNGSGRUND":       TATSAECHLICHER_VERHINDERUNGSGRUND,
		"TECHNISCHER_VERHINDERUNGSGRUND":          TECHNISCHER_VERHINDERUNGSGRUND,
		"ANSCHLUSSNUTZER_WURDE_NICHT_ANGETROFFEN": ANSCHLUSSNUTZER_WURDE_NICHT_ANGETROFFEN,
	}

	_SperrauftragsverhinderungsgrundValueToName = map[Sperrauftragsverhinderungsgrund]string{
		RECHTLICHER_GRUND_FEHLT:                 "RECHTLICHER_GRUND_FEHLT",
		AKTIVE_ZUTRITTSVERWEIGERUNG:             "AKTIVE_ZUTRITTSVERWEIGERUNG",
		PASSIVE_ZUTRITTSVERWEIGERUNG:            "PASSIVE_ZUTRITTSVERWEIGERUNG",
		ANDERER_VERHINDERUNGSGRUND:              "ANDERER_VERHINDERUNGSGRUND",
		TATSAECHLICHER_VERHINDERUNGSGRUND:       "TATSAECHLICHER_VERHINDERUNGSGRUND",
		TECHNISCHER_VERHINDERUNGSGRUND:          "TECHNISCHER_VERHINDERUNGSGRUND",
		ANSCHLUSSNUTZER_WURDE_NICHT_ANGETROFFEN: "ANSCHLUSSNUTZER_WURDE_NICHT_ANGETROFFEN",
	}
)

func init() {
	var v Sperrauftragsverhinderungsgrund
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_SperrauftragsverhinderungsgrundNameToValue = map[string]Sperrauftragsverhinderungsgrund{
			interface{}(RECHTLICHER_GRUND_FEHLT).(fmt.Stringer).String():                 RECHTLICHER_GRUND_FEHLT,
			interface{}(AKTIVE_ZUTRITTSVERWEIGERUNG).(fmt.Stringer).String():             AKTIVE_ZUTRITTSVERWEIGERUNG,
			interface{}(PASSIVE_ZUTRITTSVERWEIGERUNG).(fmt.Stringer).String():            PASSIVE_ZUTRITTSVERWEIGERUNG,
			interface{}(ANDERER_VERHINDERUNGSGRUND).(fmt.Stringer).String():              ANDERER_VERHINDERUNGSGRUND,
			interface{}(TATSAECHLICHER_VERHINDERUNGSGRUND).(fmt.Stringer).String():       TATSAECHLICHER_VERHINDERUNGSGRUND,
			interface{}(TECHNISCHER_VERHINDERUNGSGRUND).(fmt.Stringer).String():          TECHNISCHER_VERHINDERUNGSGRUND,
			interface{}(ANSCHLUSSNUTZER_WURDE_NICHT_ANGETROFFEN).(fmt.Stringer).String(): ANSCHLUSSNUTZER_WURDE_NICHT_ANGETROFFEN,
		}
	}
}

// MarshalJSON is generated so Sperrauftragsverhinderungsgrund satisfies json.Marshaler.
func (r Sperrauftragsverhinderungsgrund) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _SperrauftragsverhinderungsgrundValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Sperrauftragsverhinderungsgrund: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Sperrauftragsverhinderungsgrund satisfies json.Unmarshaler.
func (r *Sperrauftragsverhinderungsgrund) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Sperrauftragsverhinderungsgrund should be a string, got %s", data)
	}
	v, ok := _SperrauftragsverhinderungsgrundNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Sperrauftragsverhinderungsgrund %q", s)
	}
	*r = v
	return nil
}
