// Code generated by "stringer --type Sperrauftragsverhinderungsgrund"; DO NOT EDIT.

package sperrauftragsverhinderungsgrund

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RECHTLICHER_GRUND_FEHLT-1]
	_ = x[AKTIVE_ZUTRITTSVERWEIGERUNG-2]
	_ = x[PASSIVE_ZUTRITTSVERWEIGERUNG-3]
	_ = x[ANDERER_VERHINDERUNGSGRUND-4]
	_ = x[TATSAECHLICHER_VERHINDERUNGSGRUND-5]
	_ = x[TECHNISCHER_VERHINDERUNGSGRUND-6]
}

const _Sperrauftragsverhinderungsgrund_name = "RECHTLICHER_GRUND_FEHLTAKTIVE_ZUTRITTSVERWEIGERUNGPASSIVE_ZUTRITTSVERWEIGERUNGANDERER_VERHINDERUNGSGRUNDTATSAECHLICHER_VERHINDERUNGSGRUNDTECHNISCHER_VERHINDERUNGSGRUND"

var _Sperrauftragsverhinderungsgrund_index = [...]uint8{0, 23, 50, 78, 104, 137, 167}

func (i Sperrauftragsverhinderungsgrund) String() string {
	i -= 1
	if i < 0 || i >= Sperrauftragsverhinderungsgrund(len(_Sperrauftragsverhinderungsgrund_index)-1) {
		return "Sperrauftragsverhinderungsgrund(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Sperrauftragsverhinderungsgrund_name[_Sperrauftragsverhinderungsgrund_index[i]:_Sperrauftragsverhinderungsgrund_index[i+1]]
}
