// Code generated by "stringer --type BOTyp"; DO NOT EDIT.

package botyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Angebot-0]
	_ = x[Ansprechpartner-1]
	_ = x[Ausschreibung-2]
	_ = x[Energiemenge-3]
	_ = x[Geschaeftspartner-4]
	_ = x[Kosten-5]
	_ = x[Marktlokation-6]
	_ = x[Messlokation-7]
	_ = x[Marktteilnehmer-8]
	_ = x[Netznutzungsrechnung-9]
	_ = x[Preisblatt-10]
	_ = x[PreisblattDienstleistung-11]
	_ = x[PreisblattKonzessionsabgabe-12]
	_ = x[PreisblattMessung-13]
	_ = x[PreisblattUmlagen-14]
	_ = x[Rechnung-15]
	_ = x[Tarifinfo-16]
	_ = x[TarifPreisblatt-17]
	_ = x[Vertrag-18]
	_ = x[Zaehler-19]
	_ = x[Zeitreihe-20]
}

const _BOTyp_name = "AngebotAnsprechpartnerAusschreibungEnergiemengeGeschaeftspartnerKostenMarktlokationMesslokationMarktteilnehmerNetznutzungsrechnungPreisblattPreisblattDienstleistungPreisblattKonzessionsabgabePreisblattMessungPreisblattUmlagenRechnungTarifinfoTarifPreisblattVertragZaehlerZeitreihe"

var _BOTyp_index = [...]uint16{0, 7, 22, 35, 47, 64, 70, 83, 95, 110, 130, 140, 164, 191, 208, 225, 233, 242, 257, 264, 271, 280}

func (i BOTyp) String() string {
	if i < 0 || i >= BOTyp(len(_BOTyp_index)-1) {
		return "BOTyp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BOTyp_name[_BOTyp_index[i]:_BOTyp_index[i+1]]
}
