// Code generated by "stringer --type Verbrauchsmengetyp"; DO NOT EDIT.

package verbrauchsmengetyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ARBEITLEISTUNGTAGESPARAMETERABHMALO-1]
	_ = x[VERANSCHLAGTEJAHRESMENGE-2]
	_ = x[TUMKUNDENWERT-3]
}

const _Verbrauchsmengetyp_name = "ARBEITLEISTUNGTAGESPARAMETERABHMALOVERANSCHLAGTEJAHRESMENGETUMKUNDENWERT"

var _Verbrauchsmengetyp_index = [...]uint8{0, 35, 59, 72}

func (i Verbrauchsmengetyp) String() string {
	i -= 1
	if i < 0 || i >= Verbrauchsmengetyp(len(_Verbrauchsmengetyp_index)-1) {
		return "Verbrauchsmengetyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Verbrauchsmengetyp_name[_Verbrauchsmengetyp_index[i]:_Verbrauchsmengetyp_index[i+1]]
}
