// Code generated by jsonenums --type Verbrauchsmengetyp; DO NOT EDIT.

package verbrauchsmengetyp

import (
	"encoding/json"
	"fmt"
)

var (
	_VerbrauchsmengetypNameToValue = map[string]Verbrauchsmengetyp{
		"ARBEITLEISTUNGTAGESPARAMETERABHMALO": ARBEITLEISTUNGTAGESPARAMETERABHMALO,
		"VERANSCHLAGTEJAHRESMENGE":            VERANSCHLAGTEJAHRESMENGE,
		"TUMKUNDENWERT":                       TUMKUNDENWERT,
	}

	_VerbrauchsmengetypValueToName = map[Verbrauchsmengetyp]string{
		ARBEITLEISTUNGTAGESPARAMETERABHMALO: "ARBEITLEISTUNGTAGESPARAMETERABHMALO",
		VERANSCHLAGTEJAHRESMENGE:            "VERANSCHLAGTEJAHRESMENGE",
		TUMKUNDENWERT:                       "TUMKUNDENWERT",
	}
)

func init() {
	var v Verbrauchsmengetyp
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_VerbrauchsmengetypNameToValue = map[string]Verbrauchsmengetyp{
			interface{}(ARBEITLEISTUNGTAGESPARAMETERABHMALO).(fmt.Stringer).String(): ARBEITLEISTUNGTAGESPARAMETERABHMALO,
			interface{}(VERANSCHLAGTEJAHRESMENGE).(fmt.Stringer).String():            VERANSCHLAGTEJAHRESMENGE,
			interface{}(TUMKUNDENWERT).(fmt.Stringer).String():                       TUMKUNDENWERT,
		}
	}
}

// MarshalJSON is generated so Verbrauchsmengetyp satisfies json.Marshaler.
func (r Verbrauchsmengetyp) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _VerbrauchsmengetypValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Verbrauchsmengetyp: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Verbrauchsmengetyp satisfies json.Unmarshaler.
func (r *Verbrauchsmengetyp) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Verbrauchsmengetyp should be a string, got %s", data)
	}
	v, ok := _VerbrauchsmengetypNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Verbrauchsmengetyp %q", s)
	}
	*r = v
	return nil
}
