// Code generated by "stringer --type Preisstatus"; DO NOT EDIT.

package preisstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Vorlaufig-1]
	_ = x[Endgueltig-2]
}

const _Preisstatus_name = "VorlaufigEndgueltig"

var _Preisstatus_index = [...]uint8{0, 9, 19}

func (i Preisstatus) String() string {
	i -= 1
	if i < 0 || i >= Preisstatus(len(_Preisstatus_index)-1) {
		return "Preisstatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Preisstatus_name[_Preisstatus_index[i]:_Preisstatus_index[i+1]]
}
