// Code generated by "stringer --type Schwachlastfaehig"; DO NOT EDIT.

package schwachlastfaehig

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NICHT_SCHWACHLASTFAEHIG-1]
	_ = x[SCHWACHLASTFAEHIG-2]
}

const _Schwachlastfaehig_name = "NICHT_SCHWACHLASTFAEHIGSCHWACHLASTFAEHIG"

var _Schwachlastfaehig_index = [...]uint8{0, 23, 40}

func (i Schwachlastfaehig) String() string {
	i -= 1
	if i < 0 || i >= Schwachlastfaehig(len(_Schwachlastfaehig_index)-1) {
		return "Schwachlastfaehig(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Schwachlastfaehig_name[_Schwachlastfaehig_index[i]:_Schwachlastfaehig_index[i+1]]
}
