// Code generated by jsonenums --type Schwachlastfaehig; DO NOT EDIT.

package schwachlastfaehig

import (
	"encoding/json"
	"fmt"
)

var (
	_SchwachlastfaehigNameToValue = map[string]Schwachlastfaehig{
		"NICHT_SCHWACHLASTFAEHIG": NICHT_SCHWACHLASTFAEHIG,
		"SCHWACHLASTFAEHIG":       SCHWACHLASTFAEHIG,
	}

	_SchwachlastfaehigValueToName = map[Schwachlastfaehig]string{
		NICHT_SCHWACHLASTFAEHIG: "NICHT_SCHWACHLASTFAEHIG",
		SCHWACHLASTFAEHIG:       "SCHWACHLASTFAEHIG",
	}
)

func init() {
	var v Schwachlastfaehig
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_SchwachlastfaehigNameToValue = map[string]Schwachlastfaehig{
			interface{}(NICHT_SCHWACHLASTFAEHIG).(fmt.Stringer).String(): NICHT_SCHWACHLASTFAEHIG,
			interface{}(SCHWACHLASTFAEHIG).(fmt.Stringer).String():       SCHWACHLASTFAEHIG,
		}
	}
}

// MarshalJSON is generated so Schwachlastfaehig satisfies json.Marshaler.
func (r Schwachlastfaehig) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _SchwachlastfaehigValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Schwachlastfaehig: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Schwachlastfaehig satisfies json.Unmarshaler.
func (r *Schwachlastfaehig) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Schwachlastfaehig should be a string, got %s", data)
	}
	v, ok := _SchwachlastfaehigNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Schwachlastfaehig %q", s)
	}
	*r = v
	return nil
}
