// Code generated by "stringer --type UebermittelbarkeitZaehlzeit"; DO NOT EDIT.

package uebermittelbarkeitzaehlzeit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ELEKTRONISCH-1]
	_ = x[NICHT_ELEKTRONISCH-2]
}

const _UebermittelbarkeitZaehlzeit_name = "ELEKTRONISCHNICHT_ELEKTRONISCH"

var _UebermittelbarkeitZaehlzeit_index = [...]uint8{0, 12, 30}

func (i UebermittelbarkeitZaehlzeit) String() string {
	i -= 1
	if i < 0 || i >= UebermittelbarkeitZaehlzeit(len(_UebermittelbarkeitZaehlzeit_index)-1) {
		return "UebermittelbarkeitZaehlzeit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UebermittelbarkeitZaehlzeit_name[_UebermittelbarkeitZaehlzeit_index[i]:_UebermittelbarkeitZaehlzeit_index[i+1]]
}
