// Code generated by "stringer --type ArtVolumenerfassung"; DO NOT EDIT.

package artvolumenerfassung

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KENNLINIENKORREKTUR-1]
	_ = x[SCHLEICHMENGENUNTERDRÜCKUNG-2]
}

const _ArtVolumenerfassung_name = "KENNLINIENKORREKTURSCHLEICHMENGENUNTERDRÜCKUNG"

var _ArtVolumenerfassung_index = [...]uint8{0, 19, 47}

func (i ArtVolumenerfassung) String() string {
	i -= 1
	if i < 0 || i >= ArtVolumenerfassung(len(_ArtVolumenerfassung_index)-1) {
		return "ArtVolumenerfassung(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ArtVolumenerfassung_name[_ArtVolumenerfassung_index[i]:_ArtVolumenerfassung_index[i+1]]
}
