// Code generated by jsonenums --type Anfragekategorie; DO NOT EDIT.

package anfragekategorie

import (
	"encoding/json"
	"fmt"
)

var (
	_AnfragekategorieNameToValue = map[string]Anfragekategorie{
		"PROZESSDATENBERICHT":                              PROZESSDATENBERICHT,
		"GERAETEUEBERNAHME":                                GERAETEUEBERNAHME,
		"WEITERVERPFLICHTUNG_BETRIEB_MELO":                 WEITERVERPFLICHTUNG_BETRIEB_MELO,
		"AENDERUNG_MELO":                                   AENDERUNG_MELO,
		"STAMMDATEN_MALO_ODER_MELO":                        STAMMDATEN_MALO_ODER_MELO,
		"BILANZIERTE_MENGE_MEHR_MINDER_MENGEN":             BILANZIERTE_MENGE_MEHR_MINDER_MENGEN,
		"ALLOKATIONSLISTE_MEHR_MINDER_MENGEN":              ALLOKATIONSLISTE_MEHR_MINDER_MENGEN,
		"ENERGIEMENGE_UND_LEISTUNGSMAXIMUM":                ENERGIEMENGE_UND_LEISTUNGSMAXIMUM,
		"ABRECHNUNG_MESSSTELLENBETRIEB_MSB_AN_LF":          ABRECHNUNG_MESSSTELLENBETRIEB_MSB_AN_LF,
		"AENDERUNG_PROGNOSEGRUNDLAGE_GERAETEKONFIGURATION": AENDERUNG_PROGNOSEGRUNDLAGE_GERAETEKONFIGURATION,
		"AENDERUNG_GERAETEKONFIGURATION":                   AENDERUNG_GERAETEKONFIGURATION,
		"REKLAMATION_VON_WERTEN":                           REKLAMATION_VON_WERTEN,
		"LASTGANG_MALO_TRANCHE":                            LASTGANG_MALO_TRANCHE,
		"SPERRUNG":                                         SPERRUNG,
		"ENTSPERRUNG":                                      ENTSPERRUNG,
	}

	_AnfragekategorieValueToName = map[Anfragekategorie]string{
		PROZESSDATENBERICHT:                              "PROZESSDATENBERICHT",
		GERAETEUEBERNAHME:                                "GERAETEUEBERNAHME",
		WEITERVERPFLICHTUNG_BETRIEB_MELO:                 "WEITERVERPFLICHTUNG_BETRIEB_MELO",
		AENDERUNG_MELO:                                   "AENDERUNG_MELO",
		STAMMDATEN_MALO_ODER_MELO:                        "STAMMDATEN_MALO_ODER_MELO",
		BILANZIERTE_MENGE_MEHR_MINDER_MENGEN:             "BILANZIERTE_MENGE_MEHR_MINDER_MENGEN",
		ALLOKATIONSLISTE_MEHR_MINDER_MENGEN:              "ALLOKATIONSLISTE_MEHR_MINDER_MENGEN",
		ENERGIEMENGE_UND_LEISTUNGSMAXIMUM:                "ENERGIEMENGE_UND_LEISTUNGSMAXIMUM",
		ABRECHNUNG_MESSSTELLENBETRIEB_MSB_AN_LF:          "ABRECHNUNG_MESSSTELLENBETRIEB_MSB_AN_LF",
		AENDERUNG_PROGNOSEGRUNDLAGE_GERAETEKONFIGURATION: "AENDERUNG_PROGNOSEGRUNDLAGE_GERAETEKONFIGURATION",
		AENDERUNG_GERAETEKONFIGURATION:                   "AENDERUNG_GERAETEKONFIGURATION",
		REKLAMATION_VON_WERTEN:                           "REKLAMATION_VON_WERTEN",
		LASTGANG_MALO_TRANCHE:                            "LASTGANG_MALO_TRANCHE",
		SPERRUNG:                                         "SPERRUNG",
		ENTSPERRUNG:                                      "ENTSPERRUNG",
	}
)

func init() {
	var v Anfragekategorie
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_AnfragekategorieNameToValue = map[string]Anfragekategorie{
			interface{}(PROZESSDATENBERICHT).(fmt.Stringer).String():                              PROZESSDATENBERICHT,
			interface{}(GERAETEUEBERNAHME).(fmt.Stringer).String():                                GERAETEUEBERNAHME,
			interface{}(WEITERVERPFLICHTUNG_BETRIEB_MELO).(fmt.Stringer).String():                 WEITERVERPFLICHTUNG_BETRIEB_MELO,
			interface{}(AENDERUNG_MELO).(fmt.Stringer).String():                                   AENDERUNG_MELO,
			interface{}(STAMMDATEN_MALO_ODER_MELO).(fmt.Stringer).String():                        STAMMDATEN_MALO_ODER_MELO,
			interface{}(BILANZIERTE_MENGE_MEHR_MINDER_MENGEN).(fmt.Stringer).String():             BILANZIERTE_MENGE_MEHR_MINDER_MENGEN,
			interface{}(ALLOKATIONSLISTE_MEHR_MINDER_MENGEN).(fmt.Stringer).String():              ALLOKATIONSLISTE_MEHR_MINDER_MENGEN,
			interface{}(ENERGIEMENGE_UND_LEISTUNGSMAXIMUM).(fmt.Stringer).String():                ENERGIEMENGE_UND_LEISTUNGSMAXIMUM,
			interface{}(ABRECHNUNG_MESSSTELLENBETRIEB_MSB_AN_LF).(fmt.Stringer).String():          ABRECHNUNG_MESSSTELLENBETRIEB_MSB_AN_LF,
			interface{}(AENDERUNG_PROGNOSEGRUNDLAGE_GERAETEKONFIGURATION).(fmt.Stringer).String(): AENDERUNG_PROGNOSEGRUNDLAGE_GERAETEKONFIGURATION,
			interface{}(AENDERUNG_GERAETEKONFIGURATION).(fmt.Stringer).String():                   AENDERUNG_GERAETEKONFIGURATION,
			interface{}(REKLAMATION_VON_WERTEN).(fmt.Stringer).String():                           REKLAMATION_VON_WERTEN,
			interface{}(LASTGANG_MALO_TRANCHE).(fmt.Stringer).String():                            LASTGANG_MALO_TRANCHE,
			interface{}(SPERRUNG).(fmt.Stringer).String():                                         SPERRUNG,
			interface{}(ENTSPERRUNG).(fmt.Stringer).String():                                      ENTSPERRUNG,
		}
	}
}

// MarshalJSON is generated so Anfragekategorie satisfies json.Marshaler.
func (r Anfragekategorie) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _AnfragekategorieValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Anfragekategorie: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Anfragekategorie satisfies json.Unmarshaler.
func (r *Anfragekategorie) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Anfragekategorie should be a string, got %s", data)
	}
	v, ok := _AnfragekategorieNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Anfragekategorie %q", s)
	}
	*r = v
	return nil
}
