// Code generated by "stringer --type Kalkulationsmethode"; DO NOT EDIT.

package kalkulationsmethode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KEINE-1]
	_ = x[STAFFELN-2]
	_ = x[ZONEN-3]
	_ = x[VORZONEN_GP-4]
	_ = x[SIGMOID-5]
	_ = x[BLINDARBEIT_GT_50_PROZENT-6]
	_ = x[BLINDARBEIT_GT_40_PROZENT-7]
	_ = x[BLINDARBEIT_MIT_FREIMENGE-8]
	_ = x[AP_GP_ZONEN-9]
	_ = x[LP_INSTALL_LEISTUNG-10]
	_ = x[AP_TRANSPORT_ODER_VERTEILNETZ-11]
	_ = x[AP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNETZ_SIGMOID-12]
	_ = x[LP_JAHRESVERBRAUCH-13]
	_ = x[LP_TRANSPORT_ODER_VERTEILNETZ-14]
	_ = x[LP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNETZ_SIGMOID-15]
	_ = x[FUNKTIONEN-16]
	_ = x[VERBRAUCH_UEBER_SLP_GRENZE_FUNKTIONSBEZOGEN_WEITERE_BERECHNUNG_ALS_LGK-17]
}

const _Kalkulationsmethode_name = "KEINESTAFFELNZONENVORZONEN_GPSIGMOIDBLINDARBEIT_GT_50_PROZENTBLINDARBEIT_GT_40_PROZENTBLINDARBEIT_MIT_FREIMENGEAP_GP_ZONENLP_INSTALL_LEISTUNGAP_TRANSPORT_ODER_VERTEILNETZAP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNETZ_SIGMOIDLP_JAHRESVERBRAUCHLP_TRANSPORT_ODER_VERTEILNETZLP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNETZ_SIGMOIDFUNKTIONENVERBRAUCH_UEBER_SLP_GRENZE_FUNKTIONSBEZOGEN_WEITERE_BERECHNUNG_ALS_LGK"

var _Kalkulationsmethode_index = [...]uint16{0, 5, 13, 18, 29, 36, 61, 86, 111, 122, 141, 170, 223, 241, 270, 323, 333, 403}

func (i Kalkulationsmethode) String() string {
	i -= 1
	if i < 0 || i >= Kalkulationsmethode(len(_Kalkulationsmethode_index)-1) {
		return "Kalkulationsmethode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kalkulationsmethode_name[_Kalkulationsmethode_index[i]:_Kalkulationsmethode_index[i+1]]
}
