// Code generated by "stringer --type Geraeteart"; DO NOT EDIT.

package geraeteart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WANDLER-1]
	_ = x[KOMMUNIKATIONSEINRICHTUNG-2]
	_ = x[TECHNISCHE_STEUEREINRICHTUNG-3]
	_ = x[MENGENUMWERTER-4]
	_ = x[SMARTMETER_GATEWAY-5]
	_ = x[STEUERBOX-6]
	_ = x[ZAEHLEINRICHTUNG-7]
}

const _Geraeteart_name = "WANDLERKOMMUNIKATIONSEINRICHTUNGTECHNISCHE_STEUEREINRICHTUNGMENGENUMWERTERSMARTMETER_GATEWAYSTEUERBOXZAEHLEINRICHTUNG"

var _Geraeteart_index = [...]uint8{0, 7, 32, 60, 74, 92, 101, 117}

func (i Geraeteart) String() string {
	i -= 1
	if i < 0 || i >= Geraeteart(len(_Geraeteart_index)-1) {
		return "Geraeteart(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Geraeteart_name[_Geraeteart_index[i]:_Geraeteart_index[i+1]]
}
