// Code generated by "stringer --type Aggregationsverantwortung"; DO NOT EDIT.

package aggregationsverantwortung

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UENB-1]
	_ = x[VNB-2]
}

const _Aggregationsverantwortung_name = "UENBVNB"

var _Aggregationsverantwortung_index = [...]uint8{0, 4, 7}

func (i Aggregationsverantwortung) String() string {
	i -= 1
	if i < 0 || i >= Aggregationsverantwortung(len(_Aggregationsverantwortung_index)-1) {
		return "Aggregationsverantwortung(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Aggregationsverantwortung_name[_Aggregationsverantwortung_index[i]:_Aggregationsverantwortung_index[i+1]]
}
