// Code generated by "stringer --type Schalthandlung"; DO NOT EDIT.

package schalthandlung

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEISTUNG_LOKATION_AN-1]
	_ = x[LEISTUNG_LOKATION_AUS-2]
}

const _Schalthandlung_name = "LEISTUNG_LOKATION_ANLEISTUNG_LOKATION_AUS"

var _Schalthandlung_index = [...]uint8{0, 20, 41}

func (i Schalthandlung) String() string {
	i -= 1
	if i < 0 || i >= Schalthandlung(len(_Schalthandlung_index)-1) {
		return "Schalthandlung(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Schalthandlung_name[_Schalthandlung_index[i]:_Schalthandlung_index[i+1]]
}
