// Code generated by jsonenums --type Schalthandlung; DO NOT EDIT.

package schalthandlung

import (
	"encoding/json"
	"fmt"
)

var (
	_SchalthandlungNameToValue = map[string]Schalthandlung{
		"LEISTUNG_LOKATION_AN":  LEISTUNG_LOKATION_AN,
		"LEISTUNG_LOKATION_AUS": LEISTUNG_LOKATION_AUS,
	}

	_SchalthandlungValueToName = map[Schalthandlung]string{
		LEISTUNG_LOKATION_AN:  "LEISTUNG_LOKATION_AN",
		LEISTUNG_LOKATION_AUS: "LEISTUNG_LOKATION_AUS",
	}
)

func init() {
	var v Schalthandlung
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_SchalthandlungNameToValue = map[string]Schalthandlung{
			interface{}(LEISTUNG_LOKATION_AN).(fmt.Stringer).String():  LEISTUNG_LOKATION_AN,
			interface{}(LEISTUNG_LOKATION_AUS).(fmt.Stringer).String(): LEISTUNG_LOKATION_AUS,
		}
	}
}

// MarshalJSON is generated so Schalthandlung satisfies json.Marshaler.
func (r Schalthandlung) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _SchalthandlungValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Schalthandlung: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Schalthandlung satisfies json.Unmarshaler.
func (r *Schalthandlung) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Schalthandlung should be a string, got %s", data)
	}
	v, ok := _SchalthandlungNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Schalthandlung %q", s)
	}
	*r = v
	return nil
}
