// Code generated by "stringer --type Steuerkennzeichen"; DO NOT EDIT.

package steuerkennzeichen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UST_0-1]
	_ = x[UST_16-2]
	_ = x[UST_19-3]
	_ = x[UST_7-4]
	_ = x[VST_0-5]
	_ = x[VST_19-6]
	_ = x[VST_7-7]
	_ = x[RCV-8]
	_ = x[UST_SONDER-9]
	_ = x[VST_16-10]
}

const _Steuerkennzeichen_name = "UST_0UST_16UST_19UST_7VST_0VST_19VST_7RCVUST_SONDERVST_16"

var _Steuerkennzeichen_index = [...]uint8{0, 5, 11, 17, 22, 27, 33, 38, 41, 51, 57}

func (i Steuerkennzeichen) String() string {
	i -= 1
	if i < 0 || i >= Steuerkennzeichen(len(_Steuerkennzeichen_index)-1) {
		return "Steuerkennzeichen(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Steuerkennzeichen_name[_Steuerkennzeichen_index[i]:_Steuerkennzeichen_index[i+1]]
}
