// Code generated by "stringer --type Steuerkennzeichen"; DO NOT EDIT.

package steuerkennzeichen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UST0-1]
	_ = x[UST19-2]
	_ = x[UST7-3]
	_ = x[VST0-4]
	_ = x[VST19-5]
	_ = x[VST7-6]
	_ = x[RCV-7]
}

const _Steuerkennzeichen_name = "UST0UST19UST7VST0VST19VST7RCV"

var _Steuerkennzeichen_index = [...]uint8{0, 4, 9, 13, 17, 22, 26, 29}

func (i Steuerkennzeichen) String() string {
	i -= 1
	if i < 0 || i >= Steuerkennzeichen(len(_Steuerkennzeichen_index)-1) {
		return "Steuerkennzeichen(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Steuerkennzeichen_name[_Steuerkennzeichen_index[i]:_Steuerkennzeichen_index[i+1]]
}
