// Code generated by "stringer --type Steuerkennzeichen"; DO NOT EDIT.

package steuerkennzeichen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UST_0-1]
	_ = x[UST_19-2]
	_ = x[US_T7-3]
	_ = x[VST_0-4]
	_ = x[VST_19-5]
	_ = x[VST_7-6]
	_ = x[RCV-7]
}

const _Steuerkennzeichen_name = "UST_0UST_19US_T7VST_0VST_19VST_7RCV"

var _Steuerkennzeichen_index = [...]uint8{0, 5, 11, 16, 21, 27, 32, 35}

func (i Steuerkennzeichen) String() string {
	i -= 1
	if i < 0 || i >= Steuerkennzeichen(len(_Steuerkennzeichen_index)-1) {
		return "Steuerkennzeichen(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Steuerkennzeichen_name[_Steuerkennzeichen_index[i]:_Steuerkennzeichen_index[i+1]]
}
