// Code generated by "stringer --type Marktteilnehmerrolle"; DO NOT EDIT.

package marktteilnehmerrolle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ANDERE_PARTEI-1]
	_ = x[EMPFAENGER-2]
}

const _Marktteilnehmerrolle_name = "ANDERE_PARTEIEMPFAENGER"

var _Marktteilnehmerrolle_index = [...]uint8{0, 13, 23}

func (i Marktteilnehmerrolle) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Marktteilnehmerrolle_index)-1 {
		return "Marktteilnehmerrolle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Marktteilnehmerrolle_name[_Marktteilnehmerrolle_index[idx]:_Marktteilnehmerrolle_index[idx+1]]
}
