// Code generated by jsonenums --type Normierungsfaktor; DO NOT EDIT.

package normierungsfaktor

import (
	"encoding/json"
	"fmt"
)

var (
	_NormierungsfaktorNameToValue = map[string]Normierungsfaktor{
		"NORMIERUNGSFAKTOR_1_000_000_KWH_A": NORMIERUNGSFAKTOR_1_000_000_KWH_A,
		"NORMIERUNGSFAKTOR_300_KWH_K":       NORMIERUNGSFAKTOR_300_KWH_K,
		"NORMIERUNGSFAKTOR_1_000_000_KW":    NORMIERUNGSFAKTOR_1_000_000_KW,
	}

	_NormierungsfaktorValueToName = map[Normierungsfaktor]string{
		NORMIERUNGSFAKTOR_1_000_000_KWH_A: "NORMIERUNGSFAKTOR_1_000_000_KWH_A",
		NORMIERUNGSFAKTOR_300_KWH_K:       "NORMIERUNGSFAKTOR_300_KWH_K",
		NORMIERUNGSFAKTOR_1_000_000_KW:    "NORMIERUNGSFAKTOR_1_000_000_KW",
	}
)

func init() {
	var v Normierungsfaktor
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_NormierungsfaktorNameToValue = map[string]Normierungsfaktor{
			interface{}(NORMIERUNGSFAKTOR_1_000_000_KWH_A).(fmt.Stringer).String(): NORMIERUNGSFAKTOR_1_000_000_KWH_A,
			interface{}(NORMIERUNGSFAKTOR_300_KWH_K).(fmt.Stringer).String():       NORMIERUNGSFAKTOR_300_KWH_K,
			interface{}(NORMIERUNGSFAKTOR_1_000_000_KW).(fmt.Stringer).String():    NORMIERUNGSFAKTOR_1_000_000_KW,
		}
	}
}

// MarshalJSON is generated so Normierungsfaktor satisfies json.Marshaler.
func (r Normierungsfaktor) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _NormierungsfaktorValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Normierungsfaktor: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Normierungsfaktor satisfies json.Unmarshaler.
func (r *Normierungsfaktor) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Normierungsfaktor should be a string, got %s", data)
	}
	v, ok := _NormierungsfaktorNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Normierungsfaktor %q", s)
	}
	*r = v
	return nil
}
