package themengebiet

// Themengebiet erlaubt eine thematische Zuordnung, beispielsweise eines bo.Ansprechpartner
//
//go:generate stringer --type Themengebiet
//go:generate jsonenums --type Themengebiet
type Themengebiet int

const (
	// ALLGEMEINER_INFORMATIONSAUSTAUSCH bedeutet "zuständig für Allgemeiner Informationsaustausch"
	ALLGEMEINER_INFORMATIONSAUSTAUSCH           Themengebiet = iota + 1
	AN_UND_ABMELDUNG                                         // AN_UND_ABMELDUNG bedeutet "zuständig für An- und Abmeldung"
	ANSPRECHPARTNER_ALLGEMEIN                                // ANSPRECHPARTNER_ALLGEMEIN bedeutet "zuständig für Ansprechpartner Allgemein"
	ANSPRECHPARTNER_BDEW_DVGW                                // ANSPRECHPARTNER_BDEW_DVGW bedeutet "zuständig für Ansprechpartner BDEW/DVGW"
	ANSPRECHPARTNER_IT_TECHNIK                               // ANSPRECHPARTNER_IT_TECHNIK bedeutet "zuständig für Ansprechpartner IT/Technik"
	BILANZIERUNG                                             // BILANZIERUNG bedeutet "zuständig für Bilanzierung"
	BILANZKREISKOORDINATOR                                   // BILANZKREISKOORDINATOR bedeutet "zuständig für Bilanzkreiskoordinator"
	BILANZKREISVERANTWORTLICHER                              // BILANZKREISVERANTWORTLICHER bedeutet "zuständig für Bilanzkreisverantwortlicher"
	DATENFORMATE_ZERTIFIKATE_VERSCHLUESSELUNGEN              // DATENFORMATE_ZERTIFIKATE_VERSCHLUESSELUNGEN bedeutet "zuständig für Datenformate, Zertifikate, Verschlüsselungen"
	DEBITORENMANAGEMENT                                      // DEBITORENMANAGEMENT bedeutet "zuständig für Debitorenmanagement"
	DEMAND_SIDE_MANAGEMENT                                   // DEMAND_SIDE_MANAGEMENT bedeutet "zuständig für Demand-Side-Management"
	EDI_VEREINBARUNG                                         // EDI_VEREINBARUNG bedeutet "zuständig für EDI-Vereinbarung"
	EDIFACT                                                  // EDIFACT bedeutet "zuständig für EDIFACT"
	ENERGIEDATENMANAGEMENT                                   // ENERGIEDATENMANAGEMENT bedeutet "zuständig für Energiedatenmanagement"
	FAHRPLANMANAGEMENT                                       // FAHRPLANMANAGEMENT bedeutet "zuständig für Fahrplanmanagement"
	ALOCAT                                                   // ALOCAT bedeutet "zuständig für Format:ALOCAT"
	APERAK                                                   // APERAK bedeutet "zuständig für Format:APERAK"
	CONTRL                                                   // CONTRL bedeutet "zuständig für Format:CONTRL"
	INVOIC                                                   // INVOIC bedeutet "zuständig für Format:INVOIC"
	MSCONS                                                   // MSCONS bedeutet "zuständig für Format:MSCONS"
	ORDERS                                                   // ORDERS bedeutet "zuständig für Format:ORDERS"
	ORDERSP                                                  // ORDERSP bedeutet "zuständig für Format:ORDERSP"
	REMADV                                                   // REMADV bedeutet "zuständig für Format:REMADV"
	UTILMD                                                   // UTILMD bedeutet "zuständig für Format:UTILMD"
	GABI                                                     // GABI bedeutet "zuständig für GaBi Gas"
	GELI                                                     // GELI bedeutet "zuständig für GeLi Gas"
	GERAETERUECKGABE                                         // GERAETERUECKGABE bedeutet "zuständig für Geräterückgabe"
	GERAETEWECHSEL                                           // GERAETEWECHSEL bedeutet "zuständig für Gerätewechsel"
	GPKE                                                     // GPKE bedeutet "zuständig für GPKE"
	INBETRIEBNAHME                                           // INBETRIEBNAHME bedeutet "zuständig für Inbetriebnahme"
	KAPAZITAETSMANAGEMENT                                    // KAPAZITAETSMANAGEMENT bedeutet "zuständig für Kapazitätsmanagement"
	KLAERFAELLE                                              // KLAERFAELLE bedeutet "zuständig für Klärfälle"
	LASTGAENGE_RLM                                           // LASTGAENGE_RLM bedeutet "zuständig für Lastgänge RLM"
	LIEFERANTENRAHMENVERTRAG                                 // LIEFERANTENRAHMENVERTRAG bedeutet "zuständig für Lieferantenrahmenvertrag"
	LIEFERANTENWECHSEL                                       // LIEFERANTENWECHSEL bedeutet "zuständig für Lieferantenwechsel"
	MABIS                                                    // MABIS bedeutet "zuständig für MaBiS"
	MAHNWESEN                                                // MAHNWESEN bedeutet "zuständig für Mahnwesen"
	MARKTGEBIETSVERANTWORTLICHER                             // MARKTGEBIETSVERANTWORTLICHER bedeutet "zuständig für Marktgebietsverantwortlicher"
	MARKTKOMMUNIKATION                                       // MARKTKOMMUNIKATION bedeutet "zuständig für Marktkommunikation"
	MEHR_MINDERMENGEN                                        // MEHR_MINDERMENGEN bedeutet "zuständig für Mehr- Mindermengen"
	MSB_MDL                                                  // MSB_MDL bedeutet "zuständig für MSB - MDL"
	NETZABRECHNUNG                                           // NETZABRECHNUNG bedeutet "zuständig für Netzabrechnung"
	NETZENTGELTE                                             // NETZENTGELTE bedeutet "zuständig für Netzentgelte"
	NETZMANAGEMENT                                           // NETZMANAGEMENT bedeutet "zuständig für Netzmanagement"
	RECHT                                                    // RECHT bedeutet "zuständig für Recht"
	REGULIERUNGSMANAGEMENT                                   // REGULIERUNGSMANAGEMENT bedeutet "zuständig für Regulierungsmanagement"
	REKLAMATIONEN                                            // REKLAMATIONEN bedeutet "zuständig für Reklamationen"
	SPERREN_ENTSPERREN_INKASSO                               // SPERREN_ENTSPERREN_INKASSO bedeutet "zuständig für Sperren/Entsperren/Inkasso"
	STAMMDATEN                                               // STAMMDATEN bedeutet "zuständig für Stammdaten"
	STOERUNGSFAELLE                                          // STOERUNGSFAELLE bedeutet "zuständig für Übermittlung_Störungsfälle"
	TECHNISCHE_FRAGEN                                        // TECHNISCHE_FRAGEN bedeutet "zuständig für Technische Fragen"
	UMSTELLUNG_INVOIC                                        // UMSTELLUNG_INVOIC bedeutet "zuständig für Umstellung INVOIC"
	VERSCHLUESSELUNG_SIGNATUR                                // VERSCHLUESSELUNG_SIGNATUR bedeutet "zuständig für Verschlüsselung/Signatur"
	VERTRAGSMANAGEMENT                                       // VERTRAGSMANAGEMENT bedeutet "zuständig für Vertragsmanagement"
	VERTRIEB                                                 // VERTRIEB bedeutet "zuständig für Vertrieb"
	WIM                                                      // WIM bedeutet "zuständig für WiM"
	ZAEHLERSTAENDE_SLP                                       // ZAEHLERSTAENDE_SLP bedeutet "zuständig für Zählerstände SLP"
	ZAHLUNGSVERKEHR                                          // ZAHLUNGSVERKEHR bedeutet "zuständig für Zahlungsverkehr"
	ZUORDNUNGSVEREINBARUNG                                   // ZUORDNUNGSVEREINBARUNG bedeutet "zuständig für Zuordnungsvereinbarung"
)
