// Code generated by jsonenums --type BerechnungsformelAblehngrund; DO NOT EDIT.

package berechnungsformelablehngrund

import (
	"encoding/json"
	"fmt"
)

var (
	_BerechnungsformelAblehngrundNameToValue = map[string]BerechnungsformelAblehngrund{
		"START_DATUM_UNPLAUSIBEL":                                   START_DATUM_UNPLAUSIBEL,
		"ZU_VIELE_MESSLOKATIONEN":                                   ZU_VIELE_MESSLOKATIONEN,
		"FEHLENDE_MESSLOKATIONEN":                                   FEHLENDE_MESSLOKATIONEN,
		"FALSCHE_MESSLOKATION":                                      FALSCHE_MESSLOKATION,
		"FALSCHE_LIEFERRICHTUNG_DER_MARKTLOKATION":                  FALSCHE_LIEFERRICHTUNG_DER_MARKTLOKATION,
		"FALSCHE_FLUSSRICHTUNG_DER_MESSLOKATION":                    FALSCHE_FLUSSRICHTUNG_DER_MESSLOKATION,
		"MARKTLOKATION_IST_NICHT_GENAU_DER_MESSLOKATION_ZUGEORDNET": MARKTLOKATION_IST_NICHT_GENAU_DER_MESSLOKATION_ZUGEORDNET,
	}

	_BerechnungsformelAblehngrundValueToName = map[BerechnungsformelAblehngrund]string{
		START_DATUM_UNPLAUSIBEL:                                   "START_DATUM_UNPLAUSIBEL",
		ZU_VIELE_MESSLOKATIONEN:                                   "ZU_VIELE_MESSLOKATIONEN",
		FEHLENDE_MESSLOKATIONEN:                                   "FEHLENDE_MESSLOKATIONEN",
		FALSCHE_MESSLOKATION:                                      "FALSCHE_MESSLOKATION",
		FALSCHE_LIEFERRICHTUNG_DER_MARKTLOKATION:                  "FALSCHE_LIEFERRICHTUNG_DER_MARKTLOKATION",
		FALSCHE_FLUSSRICHTUNG_DER_MESSLOKATION:                    "FALSCHE_FLUSSRICHTUNG_DER_MESSLOKATION",
		MARKTLOKATION_IST_NICHT_GENAU_DER_MESSLOKATION_ZUGEORDNET: "MARKTLOKATION_IST_NICHT_GENAU_DER_MESSLOKATION_ZUGEORDNET",
	}
)

func init() {
	var v BerechnungsformelAblehngrund
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_BerechnungsformelAblehngrundNameToValue = map[string]BerechnungsformelAblehngrund{
			interface{}(START_DATUM_UNPLAUSIBEL).(fmt.Stringer).String():                                   START_DATUM_UNPLAUSIBEL,
			interface{}(ZU_VIELE_MESSLOKATIONEN).(fmt.Stringer).String():                                   ZU_VIELE_MESSLOKATIONEN,
			interface{}(FEHLENDE_MESSLOKATIONEN).(fmt.Stringer).String():                                   FEHLENDE_MESSLOKATIONEN,
			interface{}(FALSCHE_MESSLOKATION).(fmt.Stringer).String():                                      FALSCHE_MESSLOKATION,
			interface{}(FALSCHE_LIEFERRICHTUNG_DER_MARKTLOKATION).(fmt.Stringer).String():                  FALSCHE_LIEFERRICHTUNG_DER_MARKTLOKATION,
			interface{}(FALSCHE_FLUSSRICHTUNG_DER_MESSLOKATION).(fmt.Stringer).String():                    FALSCHE_FLUSSRICHTUNG_DER_MESSLOKATION,
			interface{}(MARKTLOKATION_IST_NICHT_GENAU_DER_MESSLOKATION_ZUGEORDNET).(fmt.Stringer).String(): MARKTLOKATION_IST_NICHT_GENAU_DER_MESSLOKATION_ZUGEORDNET,
		}
	}
}

// MarshalJSON is generated so BerechnungsformelAblehngrund satisfies json.Marshaler.
func (r BerechnungsformelAblehngrund) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _BerechnungsformelAblehngrundValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid BerechnungsformelAblehngrund: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so BerechnungsformelAblehngrund satisfies json.Unmarshaler.
func (r *BerechnungsformelAblehngrund) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BerechnungsformelAblehngrund should be a string, got %s", data)
	}
	v, ok := _BerechnungsformelAblehngrundNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid BerechnungsformelAblehngrund %q", s)
	}
	*r = v
	return nil
}
