// Code generated by "stringer --type BerechnungsformelAblehngrund"; DO NOT EDIT.

package berechnungsformelablehngrund

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[START_DATUM_UNPLAUSIBEL-1]
	_ = x[ZU_VIELE_MESSLOKATIONEN-2]
	_ = x[FEHLENDE_MESSLOKATIONEN-3]
	_ = x[FALSCHE_MESSLOKATION-4]
	_ = x[FALSCHE_LIEFERRICHTUNG_DER_MARKTLOKATION-5]
	_ = x[FALSCHE_FLUSSRICHTUNG_DER_MESSLOKATION-6]
	_ = x[MARKTLOKATION_IST_NICHT_GENAU_DER_MESSLOKATION_ZUGEORDNET-7]
}

const _BerechnungsformelAblehngrund_name = "START_DATUM_UNPLAUSIBELZU_VIELE_MESSLOKATIONENFEHLENDE_MESSLOKATIONENFALSCHE_MESSLOKATIONFALSCHE_LIEFERRICHTUNG_DER_MARKTLOKATIONFALSCHE_FLUSSRICHTUNG_DER_MESSLOKATIONMARKTLOKATION_IST_NICHT_GENAU_DER_MESSLOKATION_ZUGEORDNET"

var _BerechnungsformelAblehngrund_index = [...]uint8{0, 23, 46, 69, 89, 129, 167, 224}

func (i BerechnungsformelAblehngrund) String() string {
	i -= 1
	if i < 0 || i >= BerechnungsformelAblehngrund(len(_BerechnungsformelAblehngrund_index)-1) {
		return "BerechnungsformelAblehngrund(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BerechnungsformelAblehngrund_name[_BerechnungsformelAblehngrund_index[i]:_BerechnungsformelAblehngrund_index[i+1]]
}
