// Code generated by "stringer --type Leistungsbezeichnung"; DO NOT EDIT.

package leistungsbezeichnung

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[POG_VERBRAUCH_IMS_UEBER_100K-1]
	_ = x[POG_VERBRAUCH_IMS_50K_BIS_100K-2]
	_ = x[POG_VERBRAUCH_IMS_20K_BIS_50K-3]
	_ = x[POG_VERBRAUCH_IMS_10K_BIS_20K-4]
	_ = x[POG_VERBRAUCH_IMS_UNTERBRECHBAR-5]
	_ = x[POG_VERBRAUCH_IMS_6K_BIS_10K-6]
	_ = x[POG_ERZEUGUNG_IMS_7_BIS_15-7]
	_ = x[POG_ERZEUGUNG_IMS_15_BIS_30-8]
	_ = x[POG_ERZEUGUNG_IMS_30_BIS_100-9]
	_ = x[POG_ERZEUGUNG_IMS_UEBER_100-10]
	_ = x[POG_MME-11]
	_ = x[POG_VERBRAUCH_IMS_4K_BIS_6K-12]
	_ = x[POG_VERBRAUCH_IMS_3K_BIS_4K-13]
	_ = x[POG_VERBRAUCH_IMS_2K_BIS_3K-14]
	_ = x[POG_VERBRAUCH_IMS_0_BIS_2K-15]
	_ = x[POG_ERZEUGUNG_IMS_OPTIONAL-16]
	_ = x[ZUSATZLEISTUNG-17]
}

const _Leistungsbezeichnung_name = "POG_VERBRAUCH_IMS_UEBER_100KPOG_VERBRAUCH_IMS_50K_BIS_100KPOG_VERBRAUCH_IMS_20K_BIS_50KPOG_VERBRAUCH_IMS_10K_BIS_20KPOG_VERBRAUCH_IMS_UNTERBRECHBARPOG_VERBRAUCH_IMS_6K_BIS_10KPOG_ERZEUGUNG_IMS_7_BIS_15POG_ERZEUGUNG_IMS_15_BIS_30POG_ERZEUGUNG_IMS_30_BIS_100POG_ERZEUGUNG_IMS_UEBER_100POG_MMEPOG_VERBRAUCH_IMS_4K_BIS_6KPOG_VERBRAUCH_IMS_3K_BIS_4KPOG_VERBRAUCH_IMS_2K_BIS_3KPOG_VERBRAUCH_IMS_0_BIS_2KPOG_ERZEUGUNG_IMS_OPTIONALZUSATZLEISTUNG"

var _Leistungsbezeichnung_index = [...]uint16{0, 28, 58, 87, 116, 147, 175, 201, 228, 256, 283, 290, 317, 344, 371, 397, 423, 437}

func (i Leistungsbezeichnung) String() string {
	i -= 1
	if i < 0 || i >= Leistungsbezeichnung(len(_Leistungsbezeichnung_index)-1) {
		return "Leistungsbezeichnung(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Leistungsbezeichnung_name[_Leistungsbezeichnung_index[i]:_Leistungsbezeichnung_index[i+1]]
}
