// Code generated by "stringer --type Auftragsstatus"; DO NOT EDIT.

package auftragsstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GESCHEITERT-1]
	_ = x[ERFOLGREICH-2]
	_ = x[GEPLANT-3]
	_ = x[ZUGESTIMMT-4]
	_ = x[WIDERSPROCHEN-5]
	_ = x[ABGELEHNT-6]
}

const _Auftragsstatus_name = "GESCHEITERTERFOLGREICHGEPLANTZUGESTIMMTWIDERSPROCHENABGELEHNT"

var _Auftragsstatus_index = [...]uint8{0, 11, 22, 29, 39, 52, 61}

func (i Auftragsstatus) String() string {
	i -= 1
	if i < 0 || i >= Auftragsstatus(len(_Auftragsstatus_index)-1) {
		return "Auftragsstatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Auftragsstatus_name[_Auftragsstatus_index[i]:_Auftragsstatus_index[i+1]]
}
