// Code generated by jsonenums --type Auftragsstatus; DO NOT EDIT.

package auftragsstatus

import (
	"encoding/json"
	"fmt"
)

var (
	_AuftragsstatusNameToValue = map[string]Auftragsstatus{
		"GESCHEITERT":   GESCHEITERT,
		"ERFOLGREICH":   ERFOLGREICH,
		"GEPLANT":       GEPLANT,
		"ZUGESTIMMT":    ZUGESTIMMT,
		"WIDERSPROCHEN": WIDERSPROCHEN,
		"ABGELEHNT":     ABGELEHNT,
	}

	_AuftragsstatusValueToName = map[Auftragsstatus]string{
		GESCHEITERT:   "GESCHEITERT",
		ERFOLGREICH:   "ERFOLGREICH",
		GEPLANT:       "GEPLANT",
		ZUGESTIMMT:    "ZUGESTIMMT",
		WIDERSPROCHEN: "WIDERSPROCHEN",
		ABGELEHNT:     "ABGELEHNT",
	}
)

func init() {
	var v Auftragsstatus
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_AuftragsstatusNameToValue = map[string]Auftragsstatus{
			interface{}(GESCHEITERT).(fmt.Stringer).String():   GESCHEITERT,
			interface{}(ERFOLGREICH).(fmt.Stringer).String():   ERFOLGREICH,
			interface{}(GEPLANT).(fmt.Stringer).String():       GEPLANT,
			interface{}(ZUGESTIMMT).(fmt.Stringer).String():    ZUGESTIMMT,
			interface{}(WIDERSPROCHEN).(fmt.Stringer).String(): WIDERSPROCHEN,
			interface{}(ABGELEHNT).(fmt.Stringer).String():     ABGELEHNT,
		}
	}
}

// MarshalJSON is generated so Auftragsstatus satisfies json.Marshaler.
func (r Auftragsstatus) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _AuftragsstatusValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Auftragsstatus: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Auftragsstatus satisfies json.Unmarshaler.
func (r *Auftragsstatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Auftragsstatus should be a string, got %s", data)
	}
	v, ok := _AuftragsstatusNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Auftragsstatus %q", s)
	}
	*r = v
	return nil
}
