// Code generated by jsonenums --type Tarifmerkmal; DO NOT EDIT.

package tarifmerkmal

import (
	"encoding/json"
	"fmt"
)

var (
	_TarifmerkmalNameToValue = map[string]Tarifmerkmal{
		"VORKASSE":  VORKASSE,
		"PAKET":     PAKET,
		"KOMBI":     KOMBI,
		"FESTPREIS": FESTPREIS,
		"BAUSTROM":  BAUSTROM,
		"HAUSLICHT": HAUSLICHT,
		"HEIZSTROM": HEIZSTROM,
	}

	_TarifmerkmalValueToName = map[Tarifmerkmal]string{
		VORKASSE:  "VORKASSE",
		PAKET:     "PAKET",
		KOMBI:     "KOMBI",
		FESTPREIS: "FESTPREIS",
		BAUSTROM:  "BAUSTROM",
		HAUSLICHT: "HAUSLICHT",
		HEIZSTROM: "HEIZSTROM",
	}
)

func init() {
	var v Tarifmerkmal
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_TarifmerkmalNameToValue = map[string]Tarifmerkmal{
			interface{}(VORKASSE).(fmt.Stringer).String():  VORKASSE,
			interface{}(PAKET).(fmt.Stringer).String():     PAKET,
			interface{}(KOMBI).(fmt.Stringer).String():     KOMBI,
			interface{}(FESTPREIS).(fmt.Stringer).String(): FESTPREIS,
			interface{}(BAUSTROM).(fmt.Stringer).String():  BAUSTROM,
			interface{}(HAUSLICHT).(fmt.Stringer).String(): HAUSLICHT,
			interface{}(HEIZSTROM).(fmt.Stringer).String(): HEIZSTROM,
		}
	}
}

// MarshalJSON is generated so Tarifmerkmal satisfies json.Marshaler.
func (r Tarifmerkmal) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _TarifmerkmalValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Tarifmerkmal: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Tarifmerkmal satisfies json.Unmarshaler.
func (r *Tarifmerkmal) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Tarifmerkmal should be a string, got %s", data)
	}
	v, ok := _TarifmerkmalNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Tarifmerkmal %q", s)
	}
	*r = v
	return nil
}
