// Code generated by jsonenums --type Sperrauftragsablehngrund; DO NOT EDIT.

package sperrauftragsablehngrund

import (
	"encoding/json"
	"fmt"
)

var (
	_SperrauftragsablehngrundNameToValue = map[string]Sperrauftragsablehngrund{
		"DUPLIKAT":                       DUPLIKAT,
		"FALSCHER_MSB":                   FALSCHER_MSB,
		"FALSCHE_SPANNUNGSEBENE":         FALSCHE_SPANNUNGSEBENE,
		"WEITERE_MALO_BETROFFEN":         WEITERE_MALO_BETROFFEN,
		"ANDERER_ABLEHNGRUND":            ANDERER_ABLEHNGRUND,
		"FRISTVERLETZUNG_TERMINGEBUNDEN": FRISTVERLETZUNG_TERMINGEBUNDEN,
		"ANDERER_FEHLER":                 ANDERER_FEHLER,
		"LIEGT_BEREITS_VOR":              LIEGT_BEREITS_VOR,
		"ANDERER_ZUKUENFTIGER_LIEFERANT": ANDERER_ZUKUENFTIGER_LIEFERANT,
		"BESTAETIGTER_LIEFERBEGINN":      BESTAETIGTER_LIEFERBEGINN,
	}

	_SperrauftragsablehngrundValueToName = map[Sperrauftragsablehngrund]string{
		DUPLIKAT:                       "DUPLIKAT",
		FALSCHER_MSB:                   "FALSCHER_MSB",
		FALSCHE_SPANNUNGSEBENE:         "FALSCHE_SPANNUNGSEBENE",
		WEITERE_MALO_BETROFFEN:         "WEITERE_MALO_BETROFFEN",
		ANDERER_ABLEHNGRUND:            "ANDERER_ABLEHNGRUND",
		FRISTVERLETZUNG_TERMINGEBUNDEN: "FRISTVERLETZUNG_TERMINGEBUNDEN",
		ANDERER_FEHLER:                 "ANDERER_FEHLER",
		LIEGT_BEREITS_VOR:              "LIEGT_BEREITS_VOR",
		ANDERER_ZUKUENFTIGER_LIEFERANT: "ANDERER_ZUKUENFTIGER_LIEFERANT",
		BESTAETIGTER_LIEFERBEGINN:      "BESTAETIGTER_LIEFERBEGINN",
	}
)

func init() {
	var v Sperrauftragsablehngrund
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_SperrauftragsablehngrundNameToValue = map[string]Sperrauftragsablehngrund{
			interface{}(DUPLIKAT).(fmt.Stringer).String():                       DUPLIKAT,
			interface{}(FALSCHER_MSB).(fmt.Stringer).String():                   FALSCHER_MSB,
			interface{}(FALSCHE_SPANNUNGSEBENE).(fmt.Stringer).String():         FALSCHE_SPANNUNGSEBENE,
			interface{}(WEITERE_MALO_BETROFFEN).(fmt.Stringer).String():         WEITERE_MALO_BETROFFEN,
			interface{}(ANDERER_ABLEHNGRUND).(fmt.Stringer).String():            ANDERER_ABLEHNGRUND,
			interface{}(FRISTVERLETZUNG_TERMINGEBUNDEN).(fmt.Stringer).String(): FRISTVERLETZUNG_TERMINGEBUNDEN,
			interface{}(ANDERER_FEHLER).(fmt.Stringer).String():                 ANDERER_FEHLER,
			interface{}(LIEGT_BEREITS_VOR).(fmt.Stringer).String():              LIEGT_BEREITS_VOR,
			interface{}(ANDERER_ZUKUENFTIGER_LIEFERANT).(fmt.Stringer).String(): ANDERER_ZUKUENFTIGER_LIEFERANT,
			interface{}(BESTAETIGTER_LIEFERBEGINN).(fmt.Stringer).String():      BESTAETIGTER_LIEFERBEGINN,
		}
	}
}

// MarshalJSON is generated so Sperrauftragsablehngrund satisfies json.Marshaler.
func (r Sperrauftragsablehngrund) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _SperrauftragsablehngrundValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Sperrauftragsablehngrund: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Sperrauftragsablehngrund satisfies json.Unmarshaler.
func (r *Sperrauftragsablehngrund) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Sperrauftragsablehngrund should be a string, got %s", data)
	}
	v, ok := _SperrauftragsablehngrundNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Sperrauftragsablehngrund %q", s)
	}
	*r = v
	return nil
}
