// Code generated by "stringer --type Anrede"; DO NOT EDIT.

package anrede

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HERR-1]
	_ = x[FRAU-2]
	_ = x[DIVERS-3]
	_ = x[EHELEUTE-4]
	_ = x[FIRMA-5]
	_ = x[WOHNGEMEINSCHAFT-6]
	_ = x[INDIVIDUELL-7]
	_ = x[FAMILIE-8]
	_ = x[ERBENGEMEINSCHAFT-9]
	_ = x[GRUNDSTUECKGEMEINSCHAFT-10]
	_ = x[DR-11]
}

const _Anrede_name = "HERRFRAUDIVERSEHELEUTEFIRMAWOHNGEMEINSCHAFTINDIVIDUELLFAMILIEERBENGEMEINSCHAFTGRUNDSTUECKGEMEINSCHAFTDR"

var _Anrede_index = [...]uint8{0, 4, 8, 14, 22, 27, 43, 54, 61, 78, 101, 103}

func (i Anrede) String() string {
	i -= 1
	if i < 0 || i >= Anrede(len(_Anrede_index)-1) {
		return "Anrede(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Anrede_name[_Anrede_index[i]:_Anrede_index[i+1]]
}
