// Code generated by "stringer --type ArtikelId"; DO NOT EDIT.

package artikelid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNTERBRECHUNG_REGULAER-1]
	_ = x[WIEDERHERSTELLUNG_REGULAER-2]
	_ = x[UNTERBRECHUNG_OHNE_ERFOLG-3]
	_ = x[STORNO_UNTERBRECHUNG_BIS_VORTAG-4]
	_ = x[STORNO_UNTERBRECHUNG_SPERRTAG-5]
	_ = x[WIEDERHERSTELLUNG_IRREGULAER-6]
	_ = x[VERZUGPAUSCHAL-7]
	_ = x[VERZUGVARIABEL-8]
}

const _ArtikelId_name = "UNTERBRECHUNG_REGULAERWIEDERHERSTELLUNG_REGULAERUNTERBRECHUNG_OHNE_ERFOLGSTORNO_UNTERBRECHUNG_BIS_VORTAGSTORNO_UNTERBRECHUNG_SPERRTAGWIEDERHERSTELLUNG_IRREGULAERVERZUGPAUSCHALVERZUGVARIABEL"

var _ArtikelId_index = [...]uint8{0, 22, 48, 73, 104, 133, 161, 175, 189}

func (i ArtikelId) String() string {
	i -= 1
	if i < 0 || i >= ArtikelId(len(_ArtikelId_index)-1) {
		return "ArtikelId(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ArtikelId_name[_ArtikelId_index[i]:_ArtikelId_index[i+1]]
}
