package anfragetyp

//go:generate stringer --type Anfragetyp
//go:generate jsonenums --type Anfragetyp
type Anfragetyp int

const (
	START_ABO Anfragetyp = iota + 1
	ENDE_ABO
	KAUF
	NUTZUNGSUEBERLASSUNG
	KANN_NICHT_ANGEBOTEN_WERDEN
	ABRECHNUNGSBRENNWERT_UND_ZUSTANDSZAHL
	LASTGANGDATEN
	ZAEHLERSTAENDE
	WERTEERMITTLUNG
	LIEFERRICHTUNG
	ANGEBOT_AUF_BASIS_PREISBLATT
	INDIVIDUELLES_ANGEBOT
	ENERGIEMENGE_EINZELWERT
)
