// Code generated by "stringer --type Anfragetyp"; DO NOT EDIT.

package anfragetyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[START_ABO-1]
	_ = x[ENDE_ABO-2]
	_ = x[KAUF-3]
	_ = x[NUTZUNGSUEBERLASSUNG-4]
	_ = x[KANN_NICHT_ANGEBOTEN_WERDEN-5]
	_ = x[ABRECHNUNGSBRENNWERT_UND_ZUSTANDSZAHL-6]
	_ = x[LASTGANGDATEN-7]
	_ = x[ZAEHLERSTAENDE-8]
	_ = x[WERTEERMITTLUNG-9]
	_ = x[LIEFERRICHTUNG-10]
	_ = x[ANGEBOT_AUF_BASIS_PREISBLATT-11]
	_ = x[INDIVIDUELLES_ANGEBOT-12]
	_ = x[ENERGIEMENGE_EINZELWERT-13]
}

const _Anfragetyp_name = "START_ABOENDE_ABOKAUFNUTZUNGSUEBERLASSUNGKANN_NICHT_ANGEBOTEN_WERDENABRECHNUNGSBRENNWERT_UND_ZUSTANDSZAHLLASTGANGDATENZAEHLERSTAENDEWERTEERMITTLUNGLIEFERRICHTUNGANGEBOT_AUF_BASIS_PREISBLATTINDIVIDUELLES_ANGEBOTENERGIEMENGE_EINZELWERT"

var _Anfragetyp_index = [...]uint8{0, 9, 17, 21, 41, 68, 105, 118, 132, 147, 161, 189, 210, 233}

func (i Anfragetyp) String() string {
	i -= 1
	if i < 0 || i >= Anfragetyp(len(_Anfragetyp_index)-1) {
		return "Anfragetyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Anfragetyp_name[_Anfragetyp_index[i]:_Anfragetyp_index[i+1]]
}
