// Code generated by jsonenums --type Kundentyp; DO NOT EDIT.

package kundentyp

import (
	"encoding/json"
	"fmt"
)

var (
	_KundentypNameToValue = map[string]Kundentyp{
		"PRIVAT":                  PRIVAT,
		"LANDWIRT":                LANDWIRT,
		"SONSTIGE":                SONSTIGE,
		"HAUSHALT":                HAUSHALT,
		"DIREKTHEIZUNG":           DIREKTHEIZUNG,
		"GEMEINSCHAFT_MFH":        GEMEINSCHAFT_MFH,
		"KIRCHE":                  KIRCHE,
		"KWK":                     KWK,
		"LADESAEULE":              LADESAEULE,
		"BELEUCHTUNG_OEFFENTLICH": BELEUCHTUNG_OEFFENTLICH,
		"BELEUCHTUNG_STRASSE":     BELEUCHTUNG_STRASSE,
		"SPEICHERHEIZUNG":         SPEICHERHEIZUNG,
		"UNTERBR_EINRICHTUNG":     UNTERBR_EINRICHTUNG,
		"WAERMEPUMPE":             WAERMEPUMPE,
	}

	_KundentypValueToName = map[Kundentyp]string{
		PRIVAT:                  "PRIVAT",
		LANDWIRT:                "LANDWIRT",
		SONSTIGE:                "SONSTIGE",
		HAUSHALT:                "HAUSHALT",
		DIREKTHEIZUNG:           "DIREKTHEIZUNG",
		GEMEINSCHAFT_MFH:        "GEMEINSCHAFT_MFH",
		KIRCHE:                  "KIRCHE",
		KWK:                     "KWK",
		LADESAEULE:              "LADESAEULE",
		BELEUCHTUNG_OEFFENTLICH: "BELEUCHTUNG_OEFFENTLICH",
		BELEUCHTUNG_STRASSE:     "BELEUCHTUNG_STRASSE",
		SPEICHERHEIZUNG:         "SPEICHERHEIZUNG",
		UNTERBR_EINRICHTUNG:     "UNTERBR_EINRICHTUNG",
		WAERMEPUMPE:             "WAERMEPUMPE",
	}
)

func init() {
	var v Kundentyp
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_KundentypNameToValue = map[string]Kundentyp{
			interface{}(PRIVAT).(fmt.Stringer).String():                  PRIVAT,
			interface{}(LANDWIRT).(fmt.Stringer).String():                LANDWIRT,
			interface{}(SONSTIGE).(fmt.Stringer).String():                SONSTIGE,
			interface{}(HAUSHALT).(fmt.Stringer).String():                HAUSHALT,
			interface{}(DIREKTHEIZUNG).(fmt.Stringer).String():           DIREKTHEIZUNG,
			interface{}(GEMEINSCHAFT_MFH).(fmt.Stringer).String():        GEMEINSCHAFT_MFH,
			interface{}(KIRCHE).(fmt.Stringer).String():                  KIRCHE,
			interface{}(KWK).(fmt.Stringer).String():                     KWK,
			interface{}(LADESAEULE).(fmt.Stringer).String():              LADESAEULE,
			interface{}(BELEUCHTUNG_OEFFENTLICH).(fmt.Stringer).String(): BELEUCHTUNG_OEFFENTLICH,
			interface{}(BELEUCHTUNG_STRASSE).(fmt.Stringer).String():     BELEUCHTUNG_STRASSE,
			interface{}(SPEICHERHEIZUNG).(fmt.Stringer).String():         SPEICHERHEIZUNG,
			interface{}(UNTERBR_EINRICHTUNG).(fmt.Stringer).String():     UNTERBR_EINRICHTUNG,
			interface{}(WAERMEPUMPE).(fmt.Stringer).String():             WAERMEPUMPE,
		}
	}
}

// MarshalJSON is generated so Kundentyp satisfies json.Marshaler.
func (r Kundentyp) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _KundentypValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Kundentyp: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Kundentyp satisfies json.Unmarshaler.
func (r *Kundentyp) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Kundentyp should be a string, got %s", data)
	}
	v, ok := _KundentypNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Kundentyp %q", s)
	}
	*r = v
	return nil
}
