// Code generated by "stringer --type Kundentyp"; DO NOT EDIT.

package kundentyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PRIVAT-1]
	_ = x[LANDWIRT-2]
	_ = x[SONSTIGE-3]
	_ = x[HAUSHALT-4]
	_ = x[DIREKTHEIZUNG-5]
	_ = x[GEMEINSCHAFT_MFH-6]
	_ = x[KIRCHE-7]
	_ = x[KWK-8]
	_ = x[LADESAEULE-9]
	_ = x[BELEUCHTUNG_OEFFENTLICH-10]
	_ = x[BELEUCHTUNG_STRASSE-11]
	_ = x[SPEICHERHEIZUNG-12]
	_ = x[UNTERBR_EINRICHTUNG-13]
	_ = x[WAERMEPUMPE-14]
}

const _Kundentyp_name = "PRIVATLANDWIRTSONSTIGEHAUSHALTDIREKTHEIZUNGGEMEINSCHAFT_MFHKIRCHEKWKLADESAEULEBELEUCHTUNG_OEFFENTLICHBELEUCHTUNG_STRASSESPEICHERHEIZUNGUNTERBR_EINRICHTUNGWAERMEPUMPE"

var _Kundentyp_index = [...]uint8{0, 6, 14, 22, 30, 43, 59, 65, 68, 78, 101, 120, 135, 154, 165}

func (i Kundentyp) String() string {
	i -= 1
	if i < 0 || i >= Kundentyp(len(_Kundentyp_index)-1) {
		return "Kundentyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kundentyp_name[_Kundentyp_index[i]:_Kundentyp_index[i+1]]
}
