// Code generated by jsonenums --type Blindarbeitszahler; DO NOT EDIT.

package blindarbeitszahler

import (
	"encoding/json"
	"fmt"
)

var (
	_BlindarbeitszahlerNameToValue = map[string]Blindarbeitszahler{
		"ANSCHLUSSNEHMER": ANSCHLUSSNEHMER,
		"LIEFERANT":       LIEFERANT,
	}

	_BlindarbeitszahlerValueToName = map[Blindarbeitszahler]string{
		ANSCHLUSSNEHMER: "ANSCHLUSSNEHMER",
		LIEFERANT:       "LIEFERANT",
	}
)

func init() {
	var v Blindarbeitszahler
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_BlindarbeitszahlerNameToValue = map[string]Blindarbeitszahler{
			interface{}(ANSCHLUSSNEHMER).(fmt.Stringer).String(): ANSCHLUSSNEHMER,
			interface{}(LIEFERANT).(fmt.Stringer).String():       LIEFERANT,
		}
	}
}

// MarshalJSON is generated so Blindarbeitszahler satisfies json.Marshaler.
func (r Blindarbeitszahler) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _BlindarbeitszahlerValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Blindarbeitszahler: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Blindarbeitszahler satisfies json.Unmarshaler.
func (r *Blindarbeitszahler) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Blindarbeitszahler should be a string, got %s", data)
	}
	v, ok := _BlindarbeitszahlerNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Blindarbeitszahler %q", s)
	}
	*r = v
	return nil
}
