// Code generated by "stringer --type Unterbrechbarkeit"; DO NOT EDIT.

package unterbrechbarkeit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UV-1]
	_ = x[NUV-2]
}

const _Unterbrechbarkeit_name = "UVNUV"

var _Unterbrechbarkeit_index = [...]uint8{0, 2, 5}

func (i Unterbrechbarkeit) String() string {
	i -= 1
	if i < 0 || i >= Unterbrechbarkeit(len(_Unterbrechbarkeit_index)-1) {
		return "Unterbrechbarkeit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Unterbrechbarkeit_name[_Unterbrechbarkeit_index[i]:_Unterbrechbarkeit_index[i+1]]
}
