// Code generated by "stringer --type RechnungspositionsZuschlag"; DO NOT EDIT.

package rechnungspositionszuschlag

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UMSPANNUNGSZUSCHLAG-1]
	_ = x[ALLEIN_GENUTZTE_BETRIEBSMITTEL-2]
	_ = x[ZUSCHLAG_ANPASSUNG-3]
	_ = x[ANPASSUNG_PAUSCHALE_NETZENTGELTREDUZIERUNG-4]
}

const _RechnungspositionsZuschlag_name = "UMSPANNUNGSZUSCHLAGALLEIN_GENUTZTE_BETRIEBSMITTELZUSCHLAG_ANPASSUNGANPASSUNG_PAUSCHALE_NETZENTGELTREDUZIERUNG"

var _RechnungspositionsZuschlag_index = [...]uint8{0, 19, 49, 67, 109}

func (i RechnungspositionsZuschlag) String() string {
	i -= 1
	if i < 0 || i >= RechnungspositionsZuschlag(len(_RechnungspositionsZuschlag_index)-1) {
		return "RechnungspositionsZuschlag(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RechnungspositionsZuschlag_name[_RechnungspositionsZuschlag_index[i]:_RechnungspositionsZuschlag_index[i+1]]
}
