// Code generated by "stringer --type Handelsunstimmigkeitstyp"; DO NOT EDIT.

package handelsunstimmigkeitstyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HANDELSRECHNUNG-1]
	_ = x[LIEFERSCHEIN_HANDELSUNSTIMMIGKEITSTYP-2]
	_ = x[LIEFERSCHEIN_GRUND_ARBEITSPREIS-3]
	_ = x[LIEFERSCHEIN_ARBEITS_LEISTUNGSPREIS-4]
}

const _Handelsunstimmigkeitstyp_name = "HANDELSRECHNUNGLIEFERSCHEIN_HANDELSUNSTIMMIGKEITSTYPLIEFERSCHEIN_GRUND_ARBEITSPREISLIEFERSCHEIN_ARBEITS_LEISTUNGSPREIS"

var _Handelsunstimmigkeitstyp_index = [...]uint8{0, 15, 52, 83, 118}

func (i Handelsunstimmigkeitstyp) String() string {
	i -= 1
	if i < 0 || i >= Handelsunstimmigkeitstyp(len(_Handelsunstimmigkeitstyp_index)-1) {
		return "Handelsunstimmigkeitstyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Handelsunstimmigkeitstyp_name[_Handelsunstimmigkeitstyp_index[i]:_Handelsunstimmigkeitstyp_index[i+1]]
}
