// Code generated by jsonenums --type Energieflussrichtung; DO NOT EDIT.

package energieflussrichtung

import (
	"encoding/json"
	"fmt"
)

var (
	_EnergieflussrichtungNameToValue = map[string]Energieflussrichtung{
		"VERBRAUCH": VERBRAUCH,
		"ERZEUGUNG": ERZEUGUNG,
	}

	_EnergieflussrichtungValueToName = map[Energieflussrichtung]string{
		VERBRAUCH: "VERBRAUCH",
		ERZEUGUNG: "ERZEUGUNG",
	}
)

func init() {
	var v Energieflussrichtung
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_EnergieflussrichtungNameToValue = map[string]Energieflussrichtung{
			interface{}(VERBRAUCH).(fmt.Stringer).String(): VERBRAUCH,
			interface{}(ERZEUGUNG).(fmt.Stringer).String(): ERZEUGUNG,
		}
	}
}

// MarshalJSON is generated so Energieflussrichtung satisfies json.Marshaler.
func (r Energieflussrichtung) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _EnergieflussrichtungValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Energieflussrichtung: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Energieflussrichtung satisfies json.Unmarshaler.
func (r *Energieflussrichtung) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Energieflussrichtung should be a string, got %s", data)
	}
	v, ok := _EnergieflussrichtungNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Energieflussrichtung %q", s)
	}
	*r = v
	return nil
}
