// Code generated by "stringer --type Energieflussrichtung"; DO NOT EDIT.

package energieflussrichtung

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VERBRAUCH-1]
	_ = x[ERZEUGUNG-2]
}

const _Energieflussrichtung_name = "VERBRAUCHERZEUGUNG"

var _Energieflussrichtung_index = [...]uint8{0, 9, 18}

func (i Energieflussrichtung) String() string {
	i -= 1
	if i < 0 || i >= Energieflussrichtung(len(_Energieflussrichtung_index)-1) {
		return "Energieflussrichtung(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Energieflussrichtung_name[_Energieflussrichtung_index[i]:_Energieflussrichtung_index[i+1]]
}
