// Code generated by jsonenums --type Plausibilisierungshinweis; DO NOT EDIT.

package plausibilisierungshinweis

import (
	"encoding/json"
	"fmt"
)

var (
	_PlausibilisierungshinweisNameToValue = map[string]Plausibilisierungshinweis{
		"KUNDENSELBSTABLESUNG":             KUNDENSELBSTABLESUNG,
		"LEERSTAND":                        LEERSTAND,
		"REALER_ZAEHLERUEBERLAUF_GEPRUEFT": REALER_ZAEHLERUEBERLAUF_GEPRUEFT,
		"PLAUSIBEL_WG_KONTROLLABLESUNG":    PLAUSIBEL_WG_KONTROLLABLESUNG,
		"PLAUSIBEL_WG_KUNDENHINWEIS":       PLAUSIBEL_WG_KUNDENHINWEIS,
		"AUSTAUSCH_DES_ERSATZWERTES":       AUSTAUSCH_DES_ERSATZWERTES,
		"RECHENWERT":                       RECHENWERT,
	}

	_PlausibilisierungshinweisValueToName = map[Plausibilisierungshinweis]string{
		KUNDENSELBSTABLESUNG:             "KUNDENSELBSTABLESUNG",
		LEERSTAND:                        "LEERSTAND",
		REALER_ZAEHLERUEBERLAUF_GEPRUEFT: "REALER_ZAEHLERUEBERLAUF_GEPRUEFT",
		PLAUSIBEL_WG_KONTROLLABLESUNG:    "PLAUSIBEL_WG_KONTROLLABLESUNG",
		PLAUSIBEL_WG_KUNDENHINWEIS:       "PLAUSIBEL_WG_KUNDENHINWEIS",
		AUSTAUSCH_DES_ERSATZWERTES:       "AUSTAUSCH_DES_ERSATZWERTES",
		RECHENWERT:                       "RECHENWERT",
	}
)

func init() {
	var v Plausibilisierungshinweis
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_PlausibilisierungshinweisNameToValue = map[string]Plausibilisierungshinweis{
			interface{}(KUNDENSELBSTABLESUNG).(fmt.Stringer).String():             KUNDENSELBSTABLESUNG,
			interface{}(LEERSTAND).(fmt.Stringer).String():                        LEERSTAND,
			interface{}(REALER_ZAEHLERUEBERLAUF_GEPRUEFT).(fmt.Stringer).String(): REALER_ZAEHLERUEBERLAUF_GEPRUEFT,
			interface{}(PLAUSIBEL_WG_KONTROLLABLESUNG).(fmt.Stringer).String():    PLAUSIBEL_WG_KONTROLLABLESUNG,
			interface{}(PLAUSIBEL_WG_KUNDENHINWEIS).(fmt.Stringer).String():       PLAUSIBEL_WG_KUNDENHINWEIS,
			interface{}(AUSTAUSCH_DES_ERSATZWERTES).(fmt.Stringer).String():       AUSTAUSCH_DES_ERSATZWERTES,
			interface{}(RECHENWERT).(fmt.Stringer).String():                       RECHENWERT,
		}
	}
}

// MarshalJSON is generated so Plausibilisierungshinweis satisfies json.Marshaler.
func (r Plausibilisierungshinweis) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _PlausibilisierungshinweisValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Plausibilisierungshinweis: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Plausibilisierungshinweis satisfies json.Unmarshaler.
func (r *Plausibilisierungshinweis) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Plausibilisierungshinweis should be a string, got %s", data)
	}
	v, ok := _PlausibilisierungshinweisNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Plausibilisierungshinweis %q", s)
	}
	*r = v
	return nil
}
