// Code generated by "stringer --type Plausibilisierungshinweis"; DO NOT EDIT.

package plausibilisierungshinweis

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KUNDENSELBSTABLESUNG-1]
	_ = x[LEERSTAND-2]
	_ = x[REALER_ZAEHLERUEBERLAUF_GEPRUEFT-3]
	_ = x[PLAUSIBEL_WG_KONTROLLABLESUNG-4]
	_ = x[PLAUSIBEL_WG_KUNDENHINWEIS-5]
	_ = x[AUSTAUSCH_DES_ERSATZWERTES-6]
	_ = x[RECHENWERT-7]
}

const _Plausibilisierungshinweis_name = "KUNDENSELBSTABLESUNGLEERSTANDREALER_ZAEHLERUEBERLAUF_GEPRUEFTPLAUSIBEL_WG_KONTROLLABLESUNGPLAUSIBEL_WG_KUNDENHINWEISAUSTAUSCH_DES_ERSATZWERTESRECHENWERT"

var _Plausibilisierungshinweis_index = [...]uint8{0, 20, 29, 61, 90, 116, 142, 152}

func (i Plausibilisierungshinweis) String() string {
	i -= 1
	if i < 0 || i >= Plausibilisierungshinweis(len(_Plausibilisierungshinweis_index)-1) {
		return "Plausibilisierungshinweis(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Plausibilisierungshinweis_name[_Plausibilisierungshinweis_index[i]:_Plausibilisierungshinweis_index[i+1]]
}
