// Code generated by jsonenums --type Plausibilisierungshinweis; DO NOT EDIT.

package plausibilisierungshinweis

import (
	"encoding/json"
	"fmt"
)

var (
	_PlausibilisierungshinweisNameToValue = map[string]Plausibilisierungshinweis{
		"Z83_KUNDENSELBSTABLESUNG":           Z83_KUNDENSELBSTABLESUNG,
		"Z84_LEERSTAND":                      Z84_LEERSTAND,
		"Z85_REALERZAEHLERUEBERLAUFGEPRUEFT": Z85_REALERZAEHLERUEBERLAUFGEPRUEFT,
		"Z86_PLAUSIBELWGKONTROLLABLESUNG":    Z86_PLAUSIBELWGKONTROLLABLESUNG,
		"Z87_PLAUSIBELWGKUNDENHINWEIS":       Z87_PLAUSIBELWGKUNDENHINWEIS,
		"ZC3_AUSTAUSCHDESERSATZWERTES":       ZC3_AUSTAUSCHDESERSATZWERTES,
		"ZR5_RECHENWERT":                     ZR5_RECHENWERT,
	}

	_PlausibilisierungshinweisValueToName = map[Plausibilisierungshinweis]string{
		Z83_KUNDENSELBSTABLESUNG:           "Z83_KUNDENSELBSTABLESUNG",
		Z84_LEERSTAND:                      "Z84_LEERSTAND",
		Z85_REALERZAEHLERUEBERLAUFGEPRUEFT: "Z85_REALERZAEHLERUEBERLAUFGEPRUEFT",
		Z86_PLAUSIBELWGKONTROLLABLESUNG:    "Z86_PLAUSIBELWGKONTROLLABLESUNG",
		Z87_PLAUSIBELWGKUNDENHINWEIS:       "Z87_PLAUSIBELWGKUNDENHINWEIS",
		ZC3_AUSTAUSCHDESERSATZWERTES:       "ZC3_AUSTAUSCHDESERSATZWERTES",
		ZR5_RECHENWERT:                     "ZR5_RECHENWERT",
	}
)

func init() {
	var v Plausibilisierungshinweis
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_PlausibilisierungshinweisNameToValue = map[string]Plausibilisierungshinweis{
			interface{}(Z83_KUNDENSELBSTABLESUNG).(fmt.Stringer).String():           Z83_KUNDENSELBSTABLESUNG,
			interface{}(Z84_LEERSTAND).(fmt.Stringer).String():                      Z84_LEERSTAND,
			interface{}(Z85_REALERZAEHLERUEBERLAUFGEPRUEFT).(fmt.Stringer).String(): Z85_REALERZAEHLERUEBERLAUFGEPRUEFT,
			interface{}(Z86_PLAUSIBELWGKONTROLLABLESUNG).(fmt.Stringer).String():    Z86_PLAUSIBELWGKONTROLLABLESUNG,
			interface{}(Z87_PLAUSIBELWGKUNDENHINWEIS).(fmt.Stringer).String():       Z87_PLAUSIBELWGKUNDENHINWEIS,
			interface{}(ZC3_AUSTAUSCHDESERSATZWERTES).(fmt.Stringer).String():       ZC3_AUSTAUSCHDESERSATZWERTES,
			interface{}(ZR5_RECHENWERT).(fmt.Stringer).String():                     ZR5_RECHENWERT,
		}
	}
}

// MarshalJSON is generated so Plausibilisierungshinweis satisfies json.Marshaler.
func (r Plausibilisierungshinweis) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _PlausibilisierungshinweisValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Plausibilisierungshinweis: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Plausibilisierungshinweis satisfies json.Unmarshaler.
func (r *Plausibilisierungshinweis) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Plausibilisierungshinweis should be a string, got %s", data)
	}
	v, ok := _PlausibilisierungshinweisNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Plausibilisierungshinweis %q", s)
	}
	*r = v
	return nil
}
