// Code generated by "stringer --type Preisgarantietyp"; DO NOT EDIT.

package preisgarantietyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ALLE_PREISBESTANDTEILE_NETTO-1]
	_ = x[PREISBESTANDTEILE_OHNE_ABGABEN-2]
	_ = x[NUR_ENERGIEPREIS-3]
}

const _Preisgarantietyp_name = "ALLE_PREISBESTANDTEILE_NETTOPREISBESTANDTEILE_OHNE_ABGABENNUR_ENERGIEPREIS"

var _Preisgarantietyp_index = [...]uint8{0, 28, 58, 74}

func (i Preisgarantietyp) String() string {
	i -= 1
	if i < 0 || i >= Preisgarantietyp(len(_Preisgarantietyp_index)-1) {
		return "Preisgarantietyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Preisgarantietyp_name[_Preisgarantietyp_index[i]:_Preisgarantietyp_index[i+1]]
}
