// Code generated by "stringer --type BerechnungsformelNotwendigkeit"; DO NOT EDIT.

package berechnungsformelnotwendigkeit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BERECHNUNGSFORMEL_NOTWENDIG-1]
	_ = x[BERECHNUNGSFORMEL_TRIVIAL-2]
	_ = x[BERECHNUNGSFORMEL_NICHT_NOTWENDIG-3]
}

const _BerechnungsformelNotwendigkeit_name = "BERECHNUNGSFORMEL_NOTWENDIGBERECHNUNGSFORMEL_TRIVIALBERECHNUNGSFORMEL_NICHT_NOTWENDIG"

var _BerechnungsformelNotwendigkeit_index = [...]uint8{0, 27, 52, 85}

func (i BerechnungsformelNotwendigkeit) String() string {
	i -= 1
	if i < 0 || i >= BerechnungsformelNotwendigkeit(len(_BerechnungsformelNotwendigkeit_index)-1) {
		return "BerechnungsformelNotwendigkeit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BerechnungsformelNotwendigkeit_name[_BerechnungsformelNotwendigkeit_index[i]:_BerechnungsformelNotwendigkeit_index[i+1]]
}
