// Code generated by jsonenums --type BerechnungsformelNotwendigkeit; DO NOT EDIT.

package berechnungsformelnotwendigkeit

import (
	"encoding/json"
	"fmt"
)

var (
	_BerechnungsformelNotwendigkeitNameToValue = map[string]BerechnungsformelNotwendigkeit{
		"BERECHNUNGSFORMEL_NOTWENDIG":             BERECHNUNGSFORMEL_NOTWENDIG,
		"BERECHNUNGSFORMEL_TRIVIAL":               BERECHNUNGSFORMEL_TRIVIAL,
		"BERECHNUNGSFORMEL_NICHT_NOTWENDIG":       BERECHNUNGSFORMEL_NICHT_NOTWENDIG,
		"BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN": BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN,
	}

	_BerechnungsformelNotwendigkeitValueToName = map[BerechnungsformelNotwendigkeit]string{
		BERECHNUNGSFORMEL_NOTWENDIG:             "BERECHNUNGSFORMEL_NOTWENDIG",
		BERECHNUNGSFORMEL_TRIVIAL:               "BERECHNUNGSFORMEL_TRIVIAL",
		BERECHNUNGSFORMEL_NICHT_NOTWENDIG:       "BERECHNUNGSFORMEL_NICHT_NOTWENDIG",
		BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN: "BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN",
	}
)

func init() {
	var v BerechnungsformelNotwendigkeit
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_BerechnungsformelNotwendigkeitNameToValue = map[string]BerechnungsformelNotwendigkeit{
			interface{}(BERECHNUNGSFORMEL_NOTWENDIG).(fmt.Stringer).String():             BERECHNUNGSFORMEL_NOTWENDIG,
			interface{}(BERECHNUNGSFORMEL_TRIVIAL).(fmt.Stringer).String():               BERECHNUNGSFORMEL_TRIVIAL,
			interface{}(BERECHNUNGSFORMEL_NICHT_NOTWENDIG).(fmt.Stringer).String():       BERECHNUNGSFORMEL_NICHT_NOTWENDIG,
			interface{}(BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN).(fmt.Stringer).String(): BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN,
		}
	}
}

// MarshalJSON is generated so BerechnungsformelNotwendigkeit satisfies json.Marshaler.
func (r BerechnungsformelNotwendigkeit) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _BerechnungsformelNotwendigkeitValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid BerechnungsformelNotwendigkeit: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so BerechnungsformelNotwendigkeit satisfies json.Unmarshaler.
func (r *BerechnungsformelNotwendigkeit) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BerechnungsformelNotwendigkeit should be a string, got %s", data)
	}
	v, ok := _BerechnungsformelNotwendigkeitNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid BerechnungsformelNotwendigkeit %q", s)
	}
	*r = v
	return nil
}
