package statuszusatz

// Statuszusatz represents the Status Code (MSCONS SG10 STS 4405)
//go:generate stringer --type Statuszusatz
//go:generate jsonenums --type Statuszusatz
type Statuszusatz int

const (
	// TARIF_1
	TARIF_1 Statuszusatz = iota + 1

	// TARIF_2
	TARIF_2

	// TARIF_3
	TARIF_3

	// TARIF_4
	TARIF_4

	// TARIF_5
	TARIF_5

	// TARIF_6
	TARIF_6

	// TARIF_7
	TARIF_7

	// TARIF_8
	TARIF_8

	// TARIF_9
	TARIF_9

	//ZAEHLERSTAND_ZUM_BEGINN_DER_ANGEGEBENEN_ENERGIEMENGE_VORHANDEN_UND_KOMMUNIZIERT: Z36
	ZAEHLERSTAND_ZUM_BEGINN_DER_ANGEGEBENEN_ENERGIEMENGE_VORHANDEN_UND_KOMMUNIZIERT

	ZAEHLERSTAND_ZUM_ENDE_DER_ANGEGEBENEN_ENERGIEMENGE_VORHANDEN_UND_KOMMUNIZIERT

	ZAEHLERSTAND_ZUM_BEGINN_DER_ANGEGEBENEN_ENERGIEMENGE_NICHT_VORHANDEN_DA_MENGENABGRENZUNG

	ZAEHLERSTAND_ZUM_ENDE_DER_ANGEGEBENEN_ENERGIEMENGE_NICHT_VORHANDEN_DA_MENGENABGRENZUNG

	KEIN_ZUGANG

	KOMMUNIKATIONSSTOERUNG

	NETZAUSFALL

	SPANNUNGSAUSFALL

	STATUS_GERAETEWECHSEL

	KALIBRIERUNG

	GERAET_ARBEITET_AUSSERHALB_DER_BETRIEBSBEDINGUNGEN

	MESSEINRICHTUNG_GESTOERT_DEFEKT

	UNSICHERHEIT_MESSUNG

	KUNDENSELBSTABLESUNG

	LEERSTAND

	REALER_ZAEHLERUEBERLAUF_GEPRUEFT

	PLAUSIBEL_WG_KONTROLLABLESUNG

	PLAUSIBEL_WG_KUNDENHINWEIS

	VERGLEICHSMESSUNG_GEEICHT

	VERGLEICHSMESSUNG_NICHT_GEEICHT

	MESSWERTNACHBILDUNG_AUS_GEEICHTEN_WERTEN

	MESSWERTNACHBILDUNG_AUS_NICHT_GEEICHTEN_WERTEN

	INTERPOLATION

	HALTEWERT

	BILANZIERUNG_NETZABSCHNITT

	HISTORISCHE_MESSWERTE

	BERUECKSICHTIGUNG_STOERMENGENZAEHLWERK

	MENGENUMWERTUNG_VOLLSTAENDIG

	UHRZEIT_GESTELLT_SYNCHRONISATION

	MESSWERT_UNPLAUSIBEL

	FALSCHER_WANDLERFAKTOR

	FEHLERHAFTE_ABLESUNG

	AENDERUNG_DER_BERECHNUNG

	UMBAU_DER_MESSLOKATION

	DATENBEARBEITUNGSFEHLER

	BRENNWERTKORREKTUR

	Z_ZAHL_KORREKTUR

	STOERUNG_DEFEKT_MESSEINRICHTUNG

	AENDERUNG_TARIFSCHALTZEITEN

	TARIFSCHALTGERAET_DEFEKT

	AUSTAUSCH_DES_ERSATZWERTES

	IMPULSWERTIGKEIT_NICHT_AUSREICHEND

	UMSTELLUNG_GASQUALITAET

	STATISTISCHE_METHODE

	ENERGIEMENGE_IN_UNGEMESSENEM_ZEITINTERVALL

	ENERGIEMENGE_AUS_DEM_UNGEPAIRTEN_ZEITINTERVALL

	AUFTEILUNG

	VERWENDUNG_VON_WERTEN_DES_STOERMENGENZAEHLWERKS

	UMGANGS_UND_KORREKTURMENGEN

	WARTUNGSARBEITEN_AN_GEEICHTEM_MESSGERAET

	GESTOERTE_WERTE

	WARTUNGSARBEITEN_AN_EICHRECHTSKONFORMEN_MESSGERAETEN

	KONSISTENZ_UND_SYNCHRONPRUEFUNG

	RECHENWERT
)
