// Code generated by "stringer --type Kostenklasse"; DO NOT EDIT.

package kostenklasse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZERO-1]
}

const _Kostenklasse_name = "ZERO"

var _Kostenklasse_index = [...]uint8{0, 4}

func (i Kostenklasse) String() string {
	i -= 1
	if i < 0 || i >= Kostenklasse(len(_Kostenklasse_index)-1) {
		return "Kostenklasse(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kostenklasse_name[_Kostenklasse_index[i]:_Kostenklasse_index[i+1]]
}
