// Code generated by jsonenums --type Oekolabel; DO NOT EDIT.

package oekolabel

import (
	"encoding/json"
	"fmt"
)

var (
	_OekolabelNameToValue = map[string]Oekolabel{
		"GASGREEN_GRUENER_STROM": GASGREEN_GRUENER_STROM,
		"GASGREEN":               GASGREEN,
		"GRUENER_STROM_GOLD":     GRUENER_STROM_GOLD,
		"GRUENER_STROM_SILBER":   GRUENER_STROM_SILBER,
		"GRUENER_STROM":          GRUENER_STROM,
		"GRUENES_GAS":            GRUENES_GAS,
		"NATURWATT_STROM":        NATURWATT_STROM,
		"OK_POWER":               OK_POWER,
		"RENEWABLE_PLUS":         RENEWABLE_PLUS,
		"WATERGREEN":             WATERGREEN,
		"WATERGREEN_PLUS":        WATERGREEN_PLUS,
	}

	_OekolabelValueToName = map[Oekolabel]string{
		GASGREEN_GRUENER_STROM: "GASGREEN_GRUENER_STROM",
		GASGREEN:               "GASGREEN",
		GRUENER_STROM_GOLD:     "GRUENER_STROM_GOLD",
		GRUENER_STROM_SILBER:   "GRUENER_STROM_SILBER",
		GRUENER_STROM:          "GRUENER_STROM",
		GRUENES_GAS:            "GRUENES_GAS",
		NATURWATT_STROM:        "NATURWATT_STROM",
		OK_POWER:               "OK_POWER",
		RENEWABLE_PLUS:         "RENEWABLE_PLUS",
		WATERGREEN:             "WATERGREEN",
		WATERGREEN_PLUS:        "WATERGREEN_PLUS",
	}
)

func init() {
	var v Oekolabel
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_OekolabelNameToValue = map[string]Oekolabel{
			interface{}(GASGREEN_GRUENER_STROM).(fmt.Stringer).String(): GASGREEN_GRUENER_STROM,
			interface{}(GASGREEN).(fmt.Stringer).String():               GASGREEN,
			interface{}(GRUENER_STROM_GOLD).(fmt.Stringer).String():     GRUENER_STROM_GOLD,
			interface{}(GRUENER_STROM_SILBER).(fmt.Stringer).String():   GRUENER_STROM_SILBER,
			interface{}(GRUENER_STROM).(fmt.Stringer).String():          GRUENER_STROM,
			interface{}(GRUENES_GAS).(fmt.Stringer).String():            GRUENES_GAS,
			interface{}(NATURWATT_STROM).(fmt.Stringer).String():        NATURWATT_STROM,
			interface{}(OK_POWER).(fmt.Stringer).String():               OK_POWER,
			interface{}(RENEWABLE_PLUS).(fmt.Stringer).String():         RENEWABLE_PLUS,
			interface{}(WATERGREEN).(fmt.Stringer).String():             WATERGREEN,
			interface{}(WATERGREEN_PLUS).(fmt.Stringer).String():        WATERGREEN_PLUS,
		}
	}
}

// MarshalJSON is generated so Oekolabel satisfies json.Marshaler.
func (r Oekolabel) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _OekolabelValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Oekolabel: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Oekolabel satisfies json.Unmarshaler.
func (r *Oekolabel) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Oekolabel should be a string, got %s", data)
	}
	v, ok := _OekolabelNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Oekolabel %q", s)
	}
	*r = v
	return nil
}
