// Code generated by "stringer --type Oekolabel"; DO NOT EDIT.

package oekolabel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GASGREEN_GRUENER_STROM-1]
	_ = x[GASGREEN-2]
	_ = x[GRUENER_STROM_GOLD-3]
	_ = x[GRUENER_STROM_SILBER-4]
	_ = x[GRUENER_STROM-5]
	_ = x[GRUENES_GAS-6]
	_ = x[NATURWATT_STROM-7]
	_ = x[OK_POWER-8]
	_ = x[RENEWABLE_PLUS-9]
	_ = x[WATERGREEN-10]
	_ = x[WATERGREEN_PLUS-11]
}

const _Oekolabel_name = "GASGREEN_GRUENER_STROMGASGREENGRUENER_STROM_GOLDGRUENER_STROM_SILBERGRUENER_STROMGRUENES_GASNATURWATT_STROMOK_POWERRENEWABLE_PLUSWATERGREENWATERGREEN_PLUS"

var _Oekolabel_index = [...]uint8{0, 22, 30, 48, 68, 81, 92, 107, 115, 129, 139, 154}

func (i Oekolabel) String() string {
	i -= 1
	if i < 0 || i >= Oekolabel(len(_Oekolabel_index)-1) {
		return "Oekolabel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Oekolabel_name[_Oekolabel_index[i]:_Oekolabel_index[i+1]]
}
