// Code generated by jsonenums --type Auftragsstornogrund; DO NOT EDIT.

package auftragsstornogrund

import (
	"encoding/json"
	"fmt"
)

var (
	_AuftragsstornogrundNameToValue = map[string]Auftragsstornogrund{
		"STORNIERUNG_DER_ENTSPERRUNG_ERFOLGT":             STORNIERUNG_DER_ENTSPERRUNG_ERFOLGT,
		"STORNIERUNG_DER_SPERRUNG_ERFOLGT":                STORNIERUNG_DER_SPERRUNG_ERFOLGT,
		"STORNIERUNG_DER_ENTSPERRUNG_NICHT_MEHR_MOEGLICH": STORNIERUNG_DER_ENTSPERRUNG_NICHT_MEHR_MOEGLICH,
		"STORNIERUNG_DER_SPERRUNG_NICHT_MEHR_MOEGLICH":    STORNIERUNG_DER_SPERRUNG_NICHT_MEHR_MOEGLICH,
		"STORNIERUNG_DER_SPERRUNG_BIS_ZUM_VORTAG_ERFOLGT": STORNIERUNG_DER_SPERRUNG_BIS_ZUM_VORTAG_ERFOLGT,
	}

	_AuftragsstornogrundValueToName = map[Auftragsstornogrund]string{
		STORNIERUNG_DER_ENTSPERRUNG_ERFOLGT:             "STORNIERUNG_DER_ENTSPERRUNG_ERFOLGT",
		STORNIERUNG_DER_SPERRUNG_ERFOLGT:                "STORNIERUNG_DER_SPERRUNG_ERFOLGT",
		STORNIERUNG_DER_ENTSPERRUNG_NICHT_MEHR_MOEGLICH: "STORNIERUNG_DER_ENTSPERRUNG_NICHT_MEHR_MOEGLICH",
		STORNIERUNG_DER_SPERRUNG_NICHT_MEHR_MOEGLICH:    "STORNIERUNG_DER_SPERRUNG_NICHT_MEHR_MOEGLICH",
		STORNIERUNG_DER_SPERRUNG_BIS_ZUM_VORTAG_ERFOLGT: "STORNIERUNG_DER_SPERRUNG_BIS_ZUM_VORTAG_ERFOLGT",
	}
)

func init() {
	var v Auftragsstornogrund
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_AuftragsstornogrundNameToValue = map[string]Auftragsstornogrund{
			interface{}(STORNIERUNG_DER_ENTSPERRUNG_ERFOLGT).(fmt.Stringer).String():             STORNIERUNG_DER_ENTSPERRUNG_ERFOLGT,
			interface{}(STORNIERUNG_DER_SPERRUNG_ERFOLGT).(fmt.Stringer).String():                STORNIERUNG_DER_SPERRUNG_ERFOLGT,
			interface{}(STORNIERUNG_DER_ENTSPERRUNG_NICHT_MEHR_MOEGLICH).(fmt.Stringer).String(): STORNIERUNG_DER_ENTSPERRUNG_NICHT_MEHR_MOEGLICH,
			interface{}(STORNIERUNG_DER_SPERRUNG_NICHT_MEHR_MOEGLICH).(fmt.Stringer).String():    STORNIERUNG_DER_SPERRUNG_NICHT_MEHR_MOEGLICH,
			interface{}(STORNIERUNG_DER_SPERRUNG_BIS_ZUM_VORTAG_ERFOLGT).(fmt.Stringer).String(): STORNIERUNG_DER_SPERRUNG_BIS_ZUM_VORTAG_ERFOLGT,
		}
	}
}

// MarshalJSON is generated so Auftragsstornogrund satisfies json.Marshaler.
func (r Auftragsstornogrund) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _AuftragsstornogrundValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Auftragsstornogrund: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Auftragsstornogrund satisfies json.Unmarshaler.
func (r *Auftragsstornogrund) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Auftragsstornogrund should be a string, got %s", data)
	}
	v, ok := _AuftragsstornogrundNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Auftragsstornogrund %q", s)
	}
	*r = v
	return nil
}
