// Code generated by jsonenums --type InformationWeitereTechnischeRessource; DO NOT EDIT.

package informationweiteretechnischeressource

import (
	"encoding/json"
	"fmt"
)

var (
	_InformationWeitereTechnischeRessourceNameToValue = map[string]InformationWeitereTechnischeRessource{
		"WEITERE_EINRICHTUNG_VORHANDEN":       WEITERE_EINRICHTUNG_VORHANDEN,
		"KEINE_WEITERE_EINRICHTUNG_VORHANDEN": KEINE_WEITERE_EINRICHTUNG_VORHANDEN,
	}

	_InformationWeitereTechnischeRessourceValueToName = map[InformationWeitereTechnischeRessource]string{
		WEITERE_EINRICHTUNG_VORHANDEN:       "WEITERE_EINRICHTUNG_VORHANDEN",
		KEINE_WEITERE_EINRICHTUNG_VORHANDEN: "KEINE_WEITERE_EINRICHTUNG_VORHANDEN",
	}
)

func init() {
	var v InformationWeitereTechnischeRessource
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_InformationWeitereTechnischeRessourceNameToValue = map[string]InformationWeitereTechnischeRessource{
			interface{}(WEITERE_EINRICHTUNG_VORHANDEN).(fmt.Stringer).String():       WEITERE_EINRICHTUNG_VORHANDEN,
			interface{}(KEINE_WEITERE_EINRICHTUNG_VORHANDEN).(fmt.Stringer).String(): KEINE_WEITERE_EINRICHTUNG_VORHANDEN,
		}
	}
}

// MarshalJSON is generated so InformationWeitereTechnischeRessource satisfies json.Marshaler.
func (r InformationWeitereTechnischeRessource) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _InformationWeitereTechnischeRessourceValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid InformationWeitereTechnischeRessource: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so InformationWeitereTechnischeRessource satisfies json.Unmarshaler.
func (r *InformationWeitereTechnischeRessource) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("InformationWeitereTechnischeRessource should be a string, got %s", data)
	}
	v, ok := _InformationWeitereTechnischeRessourceNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid InformationWeitereTechnischeRessource %q", s)
	}
	*r = v
	return nil
}
