// Code generated by "stringer --type Vertragsstatus"; DO NOT EDIT.

package vertragsstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INARBEIT-1]
	_ = x[UEBERMITTELT-2]
	_ = x[ANGENOMMEN-3]
	_ = x[AKTIV-4]
	_ = x[ABGELEHNT-5]
	_ = x[WIDERRUFEN-6]
	_ = x[STORNIERT-7]
	_ = x[GEKUENDIGT-8]
	_ = x[BEENDET-9]
}

const _Vertragsstatus_name = "INARBEITUEBERMITTELTANGENOMMENAKTIVABGELEHNTWIDERRUFENSTORNIERTGEKUENDIGTBEENDET"

var _Vertragsstatus_index = [...]uint8{0, 8, 20, 30, 35, 44, 54, 63, 73, 80}

func (i Vertragsstatus) String() string {
	i -= 1
	if i < 0 || i >= Vertragsstatus(len(_Vertragsstatus_index)-1) {
		return "Vertragsstatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Vertragsstatus_name[_Vertragsstatus_index[i]:_Vertragsstatus_index[i+1]]
}
