// Code generated by "stringer --type GrundlageEnergiemenge"; DO NOT EDIT.

package grundlageenergiemenge

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Z36_ZAEHLERSTANDZUMBEGINDERANGEGEBENENENERGIEMENGEVORHANDENUNDKOMMUNIZIERT-1]
	_ = x[Z37_ZAEHLERSTANDZUMENDEDERANGEGEBENENENERGIEMENGEVORHANDENUNDKOMMUNIZIERT-2]
	_ = x[Z38_ZAEHLERSTANDZUMBEGINDERANGEGEBENENENERGIEMENGENICHTVORHANDENDAMENGENABGRENZUNG-3]
	_ = x[Z39_ZAEHLERSTANDZUMENDEDERANGEGEBENENENERGIEMENGENICHTVORHANDENDAMENGENABGRENZUNG-4]
}

const _GrundlageEnergiemenge_name = "Z36_ZAEHLERSTANDZUMBEGINDERANGEGEBENENENERGIEMENGEVORHANDENUNDKOMMUNIZIERTZ37_ZAEHLERSTANDZUMENDEDERANGEGEBENENENERGIEMENGEVORHANDENUNDKOMMUNIZIERTZ38_ZAEHLERSTANDZUMBEGINDERANGEGEBENENENERGIEMENGENICHTVORHANDENDAMENGENABGRENZUNGZ39_ZAEHLERSTANDZUMENDEDERANGEGEBENENENERGIEMENGENICHTVORHANDENDAMENGENABGRENZUNG"

var _GrundlageEnergiemenge_index = [...]uint16{0, 74, 147, 229, 310}

func (i GrundlageEnergiemenge) String() string {
	i -= 1
	if i < 0 || i >= GrundlageEnergiemenge(len(_GrundlageEnergiemenge_index)-1) {
		return "GrundlageEnergiemenge(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _GrundlageEnergiemenge_name[_GrundlageEnergiemenge_index[i]:_GrundlageEnergiemenge_index[i+1]]
}
