// Code generated by "stringer --type Rechnungstyp"; DO NOT EDIT.

package rechnungstyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Endkundenrechnung-1]
	_ = x[Netznutzungsrechnung-2]
	_ = x[Mehrmindermengenrechnung-3]
	_ = x[Messstellenbetriebsrechnung-4]
	_ = x[Beschaffungsrechnung-5]
	_ = x[Ausgleichsenergierechnung-6]
	_ = x[Abschlagsrechnung-7]
	_ = x[WiMRechnung-8]
	_ = x[SelbstAusgestellteRechnungMeMi-9]
}

const _Rechnungstyp_name = "EndkundenrechnungNetznutzungsrechnungMehrmindermengenrechnungMessstellenbetriebsrechnungBeschaffungsrechnungAusgleichsenergierechnungAbschlagsrechnungWiMRechnungSelbstAusgestellteRechnungMeMi"

var _Rechnungstyp_index = [...]uint8{0, 17, 37, 61, 88, 108, 133, 150, 161, 191}

func (i Rechnungstyp) String() string {
	i -= 1
	if i < 0 || i >= Rechnungstyp(len(_Rechnungstyp_index)-1) {
		return "Rechnungstyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Rechnungstyp_name[_Rechnungstyp_index[i]:_Rechnungstyp_index[i+1]]
}
