// Code generated by jsonenums --type Vertragsart; DO NOT EDIT.

package vertragsart

import (
	"encoding/json"
	"fmt"
)

var (
	_VertragsartNameToValue = map[string]Vertragsart{
		"ENERGIELIEFERVERTRAG":       ENERGIELIEFERVERTRAG,
		"NETZNUTZUNG":                NETZNUTZUNG,
		"BILANZIERUNGSVERTRAG":       BILANZIERUNGSVERTRAG,
		"MESSSTELLENBETRIEBSVERTRAG": MESSSTELLENBETRIEBSVERTRAG,
		"BUENDELVERTRAG":             BUENDELVERTRAG,
		"NETZNUTZUNGSVERTRAG":        NETZNUTZUNGSVERTRAG,
	}

	_VertragsartValueToName = map[Vertragsart]string{
		ENERGIELIEFERVERTRAG:       "ENERGIELIEFERVERTRAG",
		NETZNUTZUNG:                "NETZNUTZUNG",
		BILANZIERUNGSVERTRAG:       "BILANZIERUNGSVERTRAG",
		MESSSTELLENBETRIEBSVERTRAG: "MESSSTELLENBETRIEBSVERTRAG",
		BUENDELVERTRAG:             "BUENDELVERTRAG",
		NETZNUTZUNGSVERTRAG:        "NETZNUTZUNGSVERTRAG",
	}
)

func init() {
	var v Vertragsart
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_VertragsartNameToValue = map[string]Vertragsart{
			interface{}(ENERGIELIEFERVERTRAG).(fmt.Stringer).String():       ENERGIELIEFERVERTRAG,
			interface{}(NETZNUTZUNG).(fmt.Stringer).String():                NETZNUTZUNG,
			interface{}(BILANZIERUNGSVERTRAG).(fmt.Stringer).String():       BILANZIERUNGSVERTRAG,
			interface{}(MESSSTELLENBETRIEBSVERTRAG).(fmt.Stringer).String(): MESSSTELLENBETRIEBSVERTRAG,
			interface{}(BUENDELVERTRAG).(fmt.Stringer).String():             BUENDELVERTRAG,
			interface{}(NETZNUTZUNGSVERTRAG).(fmt.Stringer).String():        NETZNUTZUNGSVERTRAG,
		}
	}
}

// MarshalJSON is generated so Vertragsart satisfies json.Marshaler.
func (r Vertragsart) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _VertragsartValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Vertragsart: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Vertragsart satisfies json.Unmarshaler.
func (r *Vertragsart) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Vertragsart should be a string, got %s", data)
	}
	v, ok := _VertragsartNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Vertragsart %q", s)
	}
	*r = v
	return nil
}
