// Code generated by "stringer --type Vertragsart"; DO NOT EDIT.

package vertragsart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ENERGIELIEFERVERTRAG-1]
	_ = x[NETZNUTZUNG-2]
	_ = x[BILANZIERUNGSVERTRAG-3]
	_ = x[MESSSTELLENBETRIEBSVERTRAG-4]
	_ = x[BUENDELVERTRAG-5]
}

const _Vertragsart_name = "EnergieliefervertragNetznutzungBilanzierungsvertragMessstellenbetriebsvertragBuendelvertrag"

var _Vertragsart_index = [...]uint8{0, 20, 31, 51, 77, 91}

func (i Vertragsart) String() string {
	i -= 1
	if i < 0 || i >= Vertragsart(len(_Vertragsart_index)-1) {
		return "Vertragsart(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Vertragsart_name[_Vertragsart_index[i]:_Vertragsart_index[i+1]]
}
