// Code generated by "stringer --type Sonderrechnungsart"; DO NOT EDIT.

package sonderrechnungsart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KONZESSIONSABGABE_TESTAT-1]
	_ = x[INDIVIDUELL_ATYPISCH-2]
	_ = x[INDIVIDUELL_SINGULAER-3]
	_ = x[KWKG_UMLAGE-4]
	_ = x[OFFSHORE_UMLAGE-5]
	_ = x[P19_STROM_NEV_UMLAGE-6]
	_ = x[P18_ABLAV-7]
	_ = x[KONZESSIONSABGABE_WECHSEL_RLM-8]
}

const _Sonderrechnungsart_name = "KONZESSIONSABGABE_TESTATINDIVIDUELL_ATYPISCHINDIVIDUELL_SINGULAERKWKG_UMLAGEOFFSHORE_UMLAGEP19_STROM_NEV_UMLAGEP18_ABLAVKONZESSIONSABGABE_WECHSEL_RLM"

var _Sonderrechnungsart_index = [...]uint8{0, 24, 44, 65, 76, 91, 111, 120, 149}

func (i Sonderrechnungsart) String() string {
	i -= 1
	if i < 0 || i >= Sonderrechnungsart(len(_Sonderrechnungsart_index)-1) {
		return "Sonderrechnungsart(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Sonderrechnungsart_name[_Sonderrechnungsart_index[i]:_Sonderrechnungsart_index[i+1]]
}
