// Code generated by "stringer --type TechnischeRessourceVerbrauchsart"; DO NOT EDIT.

package technischeressourceverbrauchsart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KRAFT_LICHT-1]
	_ = x[WAERME-2]
	_ = x[E_MOBILITAET-3]
	_ = x[STRASSENBELEUCHTUNG-4]
}

const _TechnischeRessourceVerbrauchsart_name = "KRAFT_LICHTWAERMEE_MOBILITAETSTRASSENBELEUCHTUNG"

var _TechnischeRessourceVerbrauchsart_index = [...]uint8{0, 11, 17, 29, 48}

func (i TechnischeRessourceVerbrauchsart) String() string {
	i -= 1
	if i < 0 || i >= TechnischeRessourceVerbrauchsart(len(_TechnischeRessourceVerbrauchsart_index)-1) {
		return "TechnischeRessourceVerbrauchsart(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TechnischeRessourceVerbrauchsart_name[_TechnischeRessourceVerbrauchsart_index[i]:_TechnischeRessourceVerbrauchsart_index[i+1]]
}
