// Code generated by jsonenums --type Befestigungsart; DO NOT EDIT.

package befestigungsart

import (
	"encoding/json"
	"fmt"
)

var (
	_BefestigungsartNameToValue = map[string]Befestigungsart{
		"STECKTECHNIK": STECKTECHNIK,
		"DREIPUNKT":    DREIPUNKT,
		"HUTSCHIENE":   HUTSCHIENE,
		"EINSTUTZEN":   EINSTUTZEN,
		"ZWEISTUTZEN":  ZWEISTUTZEN,
	}

	_BefestigungsartValueToName = map[Befestigungsart]string{
		STECKTECHNIK: "STECKTECHNIK",
		DREIPUNKT:    "DREIPUNKT",
		HUTSCHIENE:   "HUTSCHIENE",
		EINSTUTZEN:   "EINSTUTZEN",
		ZWEISTUTZEN:  "ZWEISTUTZEN",
	}
)

func init() {
	var v Befestigungsart
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_BefestigungsartNameToValue = map[string]Befestigungsart{
			interface{}(STECKTECHNIK).(fmt.Stringer).String(): STECKTECHNIK,
			interface{}(DREIPUNKT).(fmt.Stringer).String():    DREIPUNKT,
			interface{}(HUTSCHIENE).(fmt.Stringer).String():   HUTSCHIENE,
			interface{}(EINSTUTZEN).(fmt.Stringer).String():   EINSTUTZEN,
			interface{}(ZWEISTUTZEN).(fmt.Stringer).String():  ZWEISTUTZEN,
		}
	}
}

// MarshalJSON is generated so Befestigungsart satisfies json.Marshaler.
func (r Befestigungsart) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _BefestigungsartValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Befestigungsart: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Befestigungsart satisfies json.Unmarshaler.
func (r *Befestigungsart) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Befestigungsart should be a string, got %s", data)
	}
	v, ok := _BefestigungsartNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Befestigungsart %q", s)
	}
	*r = v
	return nil
}
