// Code generated by jsonenums --type Tarifkalkulationsmethode; DO NOT EDIT.

package tarifkalkulationsmethode

import (
	"encoding/json"
	"fmt"
)

var (
	_TarifkalkulationsmethodeNameToValue = map[string]Tarifkalkulationsmethode{
		"STAFFELN":               STAFFELN,
		"ZONEN":                  ZONEN,
		"BESTABRECHNUNG_STAFFEL": BESTABRECHNUNG_STAFFEL,
		"PAKETPREIS":             PAKETPREIS,
	}

	_TarifkalkulationsmethodeValueToName = map[Tarifkalkulationsmethode]string{
		STAFFELN:               "STAFFELN",
		ZONEN:                  "ZONEN",
		BESTABRECHNUNG_STAFFEL: "BESTABRECHNUNG_STAFFEL",
		PAKETPREIS:             "PAKETPREIS",
	}
)

func init() {
	var v Tarifkalkulationsmethode
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_TarifkalkulationsmethodeNameToValue = map[string]Tarifkalkulationsmethode{
			interface{}(STAFFELN).(fmt.Stringer).String():               STAFFELN,
			interface{}(ZONEN).(fmt.Stringer).String():                  ZONEN,
			interface{}(BESTABRECHNUNG_STAFFEL).(fmt.Stringer).String(): BESTABRECHNUNG_STAFFEL,
			interface{}(PAKETPREIS).(fmt.Stringer).String():             PAKETPREIS,
		}
	}
}

// MarshalJSON is generated so Tarifkalkulationsmethode satisfies json.Marshaler.
func (r Tarifkalkulationsmethode) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _TarifkalkulationsmethodeValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Tarifkalkulationsmethode: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Tarifkalkulationsmethode satisfies json.Unmarshaler.
func (r *Tarifkalkulationsmethode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Tarifkalkulationsmethode should be a string, got %s", data)
	}
	v, ok := _TarifkalkulationsmethodeNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Tarifkalkulationsmethode %q", s)
	}
	*r = v
	return nil
}
