// Code generated by "stringer --type Tarifkalkulationsmethode"; DO NOT EDIT.

package tarifkalkulationsmethode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STAFFELN-1]
	_ = x[ZONEN-2]
	_ = x[BESTABRECHNUNG_STAFFEL-3]
	_ = x[PAKETPREIS-4]
}

const _Tarifkalkulationsmethode_name = "STAFFELNZONENBESTABRECHNUNG_STAFFELPAKETPREIS"

var _Tarifkalkulationsmethode_index = [...]uint8{0, 8, 13, 35, 45}

func (i Tarifkalkulationsmethode) String() string {
	i -= 1
	if i < 0 || i >= Tarifkalkulationsmethode(len(_Tarifkalkulationsmethode_index)-1) {
		return "Tarifkalkulationsmethode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Tarifkalkulationsmethode_name[_Tarifkalkulationsmethode_index[i]:_Tarifkalkulationsmethode_index[i+1]]
}
