// Code generated by "stringer --type Zeiteinheit"; DO NOT EDIT.

package zeiteinheit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Sekunde-1]
	_ = x[Minute-2]
	_ = x[Stunde-3]
	_ = x[ViertelStunde-4]
	_ = x[Tag-5]
	_ = x[Woche-6]
	_ = x[Monat-7]
	_ = x[Quartal-8]
	_ = x[Halbjahr-9]
	_ = x[Jahr-10]
}

const _Zeiteinheit_name = "SekundeMinuteStundeViertelStundeTagWocheMonatQuartalHalbjahrJahr"

var _Zeiteinheit_index = [...]uint8{0, 7, 13, 19, 32, 35, 40, 45, 52, 60, 64}

func (i Zeiteinheit) String() string {
	i -= 1
	if i < 0 || i >= Zeiteinheit(len(_Zeiteinheit_index)-1) {
		return "Zeiteinheit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Zeiteinheit_name[_Zeiteinheit_index[i]:_Zeiteinheit_index[i+1]]
}
