// Code generated by "stringer --type ZaehlzeitdefinitionTyp"; DO NOT EDIT.

package zaehlzeitdefinitiontyp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WAERMEPUMPE-1]
	_ = x[NACHTSPEICHERHEIZUNG-2]
	_ = x[SCHWACHLASTZEITFENSTER-3]
	_ = x[SONSTIGE-4]
	_ = x[HOCHLASTZEITFENSTER-5]
}

const _ZaehlzeitdefinitionTyp_name = "WAERMEPUMPENACHTSPEICHERHEIZUNGSCHWACHLASTZEITFENSTERSONSTIGEHOCHLASTZEITFENSTER"

var _ZaehlzeitdefinitionTyp_index = [...]uint8{0, 11, 31, 53, 61, 80}

func (i ZaehlzeitdefinitionTyp) String() string {
	i -= 1
	if i < 0 || i >= ZaehlzeitdefinitionTyp(len(_ZaehlzeitdefinitionTyp_index)-1) {
		return "ZaehlzeitdefinitionTyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ZaehlzeitdefinitionTyp_name[_ZaehlzeitdefinitionTyp_index[i]:_ZaehlzeitdefinitionTyp_index[i+1]]
}
