// Code generated by "stringer --type Netznutzungsvertragsart"; DO NOT EDIT.

package netznutzungsvertragsart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KUNDEN_NB-1]
	_ = x[LIEFERANTEN_NB-2]
}

const _Netznutzungsvertragsart_name = "KUNDEN_NBLIEFERANTEN_NB"

var _Netznutzungsvertragsart_index = [...]uint8{0, 9, 23}

func (i Netznutzungsvertragsart) String() string {
	i -= 1
	if i < 0 || i >= Netznutzungsvertragsart(len(_Netznutzungsvertragsart_index)-1) {
		return "Netznutzungsvertragsart(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Netznutzungsvertragsart_name[_Netznutzungsvertragsart_index[i]:_Netznutzungsvertragsart_index[i+1]]
}
