// Code generated by jsonenums --type KategorieTechnischeRessource; DO NOT EDIT.

package kategorietechnischeressource

import (
	"encoding/json"
	"fmt"
)

var (
	_KategorieTechnischeRessourceNameToValue = map[string]KategorieTechnischeRessource{
		"FAELLT_UNTER_14A":       FAELLT_UNTER_14A,
		"FAELLT_NICHT_UNTER_14A": FAELLT_NICHT_UNTER_14A,
	}

	_KategorieTechnischeRessourceValueToName = map[KategorieTechnischeRessource]string{
		FAELLT_UNTER_14A:       "FAELLT_UNTER_14A",
		FAELLT_NICHT_UNTER_14A: "FAELLT_NICHT_UNTER_14A",
	}
)

func init() {
	var v KategorieTechnischeRessource
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_KategorieTechnischeRessourceNameToValue = map[string]KategorieTechnischeRessource{
			interface{}(FAELLT_UNTER_14A).(fmt.Stringer).String():       FAELLT_UNTER_14A,
			interface{}(FAELLT_NICHT_UNTER_14A).(fmt.Stringer).String(): FAELLT_NICHT_UNTER_14A,
		}
	}
}

// MarshalJSON is generated so KategorieTechnischeRessource satisfies json.Marshaler.
func (r KategorieTechnischeRessource) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _KategorieTechnischeRessourceValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid KategorieTechnischeRessource: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so KategorieTechnischeRessource satisfies json.Unmarshaler.
func (r *KategorieTechnischeRessource) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("KategorieTechnischeRessource should be a string, got %s", data)
	}
	v, ok := _KategorieTechnischeRessourceNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid KategorieTechnischeRessource %q", s)
	}
	*r = v
	return nil
}
