// Code generated by jsonenums --type Bearbeitungsstatus; DO NOT EDIT.

package bearbeitungsstatus

import (
	"encoding/json"
	"fmt"
)

var (
	_BearbeitungsstatusNameToValue = map[string]Bearbeitungsstatus{
		"OFFEN":          OFFEN,
		"IN_BEARBEITUNG": IN_BEARBEITUNG,
		"ABGESCHLOSSEN":  ABGESCHLOSSEN,
		"STORNIERT":      STORNIERT,
		"QUITTIERT":      QUITTIERT,
		"IGNORIERT":      IGNORIERT,
	}

	_BearbeitungsstatusValueToName = map[Bearbeitungsstatus]string{
		OFFEN:          "OFFEN",
		IN_BEARBEITUNG: "IN_BEARBEITUNG",
		ABGESCHLOSSEN:  "ABGESCHLOSSEN",
		STORNIERT:      "STORNIERT",
		QUITTIERT:      "QUITTIERT",
		IGNORIERT:      "IGNORIERT",
	}
)

func init() {
	var v Bearbeitungsstatus
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_BearbeitungsstatusNameToValue = map[string]Bearbeitungsstatus{
			interface{}(OFFEN).(fmt.Stringer).String():          OFFEN,
			interface{}(IN_BEARBEITUNG).(fmt.Stringer).String(): IN_BEARBEITUNG,
			interface{}(ABGESCHLOSSEN).(fmt.Stringer).String():  ABGESCHLOSSEN,
			interface{}(STORNIERT).(fmt.Stringer).String():      STORNIERT,
			interface{}(QUITTIERT).(fmt.Stringer).String():      QUITTIERT,
			interface{}(IGNORIERT).(fmt.Stringer).String():      IGNORIERT,
		}
	}
}

// MarshalJSON is generated so Bearbeitungsstatus satisfies json.Marshaler.
func (r Bearbeitungsstatus) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _BearbeitungsstatusValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Bearbeitungsstatus: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Bearbeitungsstatus satisfies json.Unmarshaler.
func (r *Bearbeitungsstatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Bearbeitungsstatus should be a string, got %s", data)
	}
	v, ok := _BearbeitungsstatusNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Bearbeitungsstatus %q", s)
	}
	*r = v
	return nil
}
