// Code generated by "stringer --type Bearbeitungsstatus"; DO NOT EDIT.

package bearbeitungsstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OFFEN-1]
	_ = x[IN_BEARBEITUNG-2]
	_ = x[ABGESCHLOSSEN-3]
	_ = x[STORNIERT-4]
	_ = x[QUITTIERT-5]
	_ = x[IGNORIERT-6]
}

const _Bearbeitungsstatus_name = "OFFENIN_BEARBEITUNGABGESCHLOSSENSTORNIERTQUITTIERTIGNORIERT"

var _Bearbeitungsstatus_index = [...]uint8{0, 5, 19, 32, 41, 50, 59}

func (i Bearbeitungsstatus) String() string {
	i -= 1
	if i < 0 || i >= Bearbeitungsstatus(len(_Bearbeitungsstatus_index)-1) {
		return "Bearbeitungsstatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Bearbeitungsstatus_name[_Bearbeitungsstatus_index[i]:_Bearbeitungsstatus_index[i+1]]
}
