// Code generated by "stringer --type Erzeugungsart"; DO NOT EDIT.

package erzeugungsart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KWK-1]
	_ = x[WIND-2]
	_ = x[SOLAR-3]
	_ = x[KERNKRAFT-4]
	_ = x[WASSER-5]
	_ = x[GEOTHERMIE-6]
	_ = x[BIOMASSE-7]
	_ = x[KOHLE-8]
	_ = x[GAS-9]
	_ = x[SONSTIGE-10]
	_ = x[SONSTIGE_EEG-11]
}

const _Erzeugungsart_name = "KWKWINDSOLARKERNKRAFTWASSERGEOTHERMIEBIOMASSEKOHLEGASSONSTIGESONSTIGE_EEG"

var _Erzeugungsart_index = [...]uint8{0, 3, 7, 12, 21, 27, 37, 45, 50, 53, 61, 73}

func (i Erzeugungsart) String() string {
	i -= 1
	if i < 0 || i >= Erzeugungsart(len(_Erzeugungsart_index)-1) {
		return "Erzeugungsart(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Erzeugungsart_name[_Erzeugungsart_index[i]:_Erzeugungsart_index[i+1]]
}
